import { db } from "@/db";
import {
  users, stores, products, cartItems, orders, automationRules, aiActivityLogs,
} from "@/db/schema";
import { desc } from "drizzle-orm";

export async function ensureDemoDataSeeded() {
  try {
    const existing = await db.select().from(users).limit(1);
    if (existing.length > 0) return existing[0];

    // ── 1. OPERATOR USER ───────────────────────────────────────────────────────
    const [demoUser] = await db.insert(users).values({
      email: "operator@bharatdrop.in",
      name: "Rahul Sharma",
      passwordHash: "bharatdrop2026",
      role: "Chief Automation Officer",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
      aiAutoPilotEnabled: true,
      minProfitMarginPct: "35.00",
      autoFulfillOrders: true,
      maxDailySpendInr: "200000.00",
      gstRegistered: true,
      gstNumber: "27AAPFU0939F1ZV",
      defaultMarginPct: "40.00",
    }).returning();

    // ── 2. INDIAN MARKETPLACE STORES ──────────────────────────────────────────
    const insertedStores = await db.insert(stores).values([
      {
        userId: demoUser.id,
        name: "BharatDrop — Meesho Flagship",
        platform: "Meesho",
        storeUrl: "meesho.com/bharatdrop",
        status: "Connected",
        totalProductsCount: 48,
        currency: "INR",
        commissionPct: "0.00", // Meesho zero commission
      },
      {
        userId: demoUser.id,
        name: "BharatDrop — Flipkart Assured",
        platform: "Flipkart",
        storeUrl: "seller.flipkart.com/bharatdrop",
        status: "Connected",
        totalProductsCount: 22,
        currency: "INR",
        commissionPct: "8.00",
      },
      {
        userId: demoUser.id,
        name: "BharatDrop — Amazon India FBA",
        platform: "Amazon India",
        storeUrl: "amazon.in/s?me=BHARATDROP",
        status: "Connected",
        totalProductsCount: 18,
        currency: "INR",
        commissionPct: "12.00",
      },
      {
        userId: demoUser.id,
        name: "BharatDrop — Glowroad",
        platform: "Glowroad",
        storeUrl: "glowroad.com/shop/bharatdrop",
        status: "Connected",
        totalProductsCount: 31,
        currency: "INR",
        commissionPct: "0.00",
      },
    ]).returning();

    const meeshoStoreId = insertedStores[0].id;
    const flipkartStoreId = insertedStores[1].id;
    const amazonStoreId = insertedStores[2].id;
    const glowroadStoreId = insertedStores[3].id;

    // ── 3. REAL INDIAN DROPSHIPPING PRODUCTS (INR, real SKUs) ────────────────
    const productRows = [
      // ── ELECTRONICS & GADGETS ────────────────────────────────────────────────
      {
        userId: demoUser.id, storeId: meeshoStoreId,
        sku: "BD-USB-HUB-4P-01",
        title: "Portronics Mport 7C USB 3.0 7-in-1 Type-C Hub with HDMI 4K, PD 100W, SD/TF Card Reader",
        category: "Electronics & Gadgets",
        imageUrl: "https://images.unsplash.com/photo-1625948515291-69bc9a6f8c87?w=600&auto=format&fit=crop&q=80",
        brand: "Portronics",
        supplierName: "RK Electronics Wholesale, Lamington Road Mumbai",
        supplierCity: "Mumbai, Maharashtra",
        supplierCostInr: "420.00", shippingCostInr: "65.00", gstPct: "18.00",
        sellingPriceInr: "999.00", mrpInr: "1499.00",
        customMarginPct: "42.00", netProfitInr: "334.00",
        aiScore: 97, viralVelocityScore: 94,
        stockCount: 850, moq: 1, hsnCode: "85176990",
        aiMarketingCopy: "7-in-1 dongle ek kaam ka — 4K HDMI, 100W fast charge, USB 3.0 hi-speed, SD reader — सब एक में। Office aur WFH dono ke liye perfect.",
        aiTargetAudience: "WFH professionals, college students, MacBook users, Tier-1 & Tier-2 Indian cities",
        salesCount24h: 74,
      },
      {
        userId: demoUser.id, storeId: flipkartStoreId,
        sku: "BD-BT-EARBUD-02",
        title: "boAt Airdopes 141 ANC Bluetooth 5.3 TWS Earbuds 42H Playtime, IPX4, ENx Mic — Blazing Black",
        category: "Electronics & Gadgets",
        imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80",
        brand: "boAt",
        supplierName: "Imagine Marketing (boAt) Authorised Distributor, Delhi",
        supplierCity: "New Delhi",
        supplierCostInr: "680.00", shippingCostInr: "50.00", gstPct: "18.00",
        sellingPriceInr: "1499.00", mrpInr: "2990.00",
        customMarginPct: "44.00", netProfitInr: "584.00",
        aiScore: 98, viralVelocityScore: 97,
        stockCount: 1420, moq: 1, hsnCode: "85183000",
        aiMarketingCopy: "boAt Airdopes 141 — 42 ghante ka battery, ANC se cancel karo shor, quad mic se baat karo crystal clear. India ka #1 bestseller.",
        aiTargetAudience: "Students, commuters, gym goers, 18–35 demographic across India",
        salesCount24h: 112,
      },
      {
        userId: demoUser.id, storeId: amazonStoreId,
        sku: "BD-SMART-BULB-03",
        title: "Wipro 9W Smart LED Bulb WiFi B22, 16M Colours, Works with Alexa & Google Home — Pack of 2",
        category: "Smart Home",
        imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&fit=crop&q=80",
        brand: "Wipro",
        supplierName: "Wipro Consumer Care Dist., Bengaluru",
        supplierCity: "Bengaluru, Karnataka",
        supplierCostInr: "340.00", shippingCostInr: "55.00", gstPct: "12.00",
        sellingPriceInr: "799.00", mrpInr: "1198.00",
        customMarginPct: "38.00", netProfitInr: "248.00",
        aiScore: 93, viralVelocityScore: 88,
        stockCount: 620, moq: 2, hsnCode: "94054090",
        aiMarketingCopy: "Wipro Smart Bulb se ghar ko Smart Home banao — Alexa se bolo, phone se control karo. 16 million colours, schedule timer, automatic sunrise-sunset mode.",
        aiTargetAudience: "Urban homeowners, newly married couples, Tier-1 India smart home enthusiasts",
        salesCount24h: 38,
      },
      {
        userId: demoUser.id, storeId: meeshoStoreId,
        sku: "BD-NECK-FAN-04",
        title: "3-Speed Bladeless Wearable Neck Fan USB-C Rechargeable 2000mAh, 360° Airflow — Summer Essential",
        category: "Wellness & Lifestyle",
        imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&auto=format&fit=crop&q=80",
        brand: "CoolBreeze India",
        supplierName: "Surat Gadget Wholesale Mkt, Ring Road",
        supplierCity: "Surat, Gujarat",
        supplierCostInr: "180.00", shippingCostInr: "60.00", gstPct: "18.00",
        sellingPriceInr: "499.00", mrpInr: "899.00",
        customMarginPct: "45.00", netProfitInr: "178.00",
        aiScore: 96, viralVelocityScore: 99,
        stockCount: 2100, moq: 1, hsnCode: "84145190",
        aiMarketingCopy: "Gaadi mein, office mein, bahar ghoomte waqt — yeh bladeless neck fan hamesha saath. USB-C se charge karo, 8 ghante chalo. India ki garmi ka asli solution.",
        aiTargetAudience: "Students, office workers, outdoor vendors, Indian summer market (March–June)",
        salesCount24h: 189,
      },
      {
        userId: demoUser.id, storeId: flipkartStoreId,
        sku: "BD-YOGA-MAT-05",
        title: "Boldfit Anti-Slip TPE Yoga Mat 6mm Extra Thick with Carry Strap — Purple/Grey (183cm x 61cm)",
        category: "Sports & Fitness",
        imageUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&auto=format&fit=crop&q=80",
        brand: "Boldfit",
        supplierName: "Boldfit Sports Pvt Ltd, Gurugram",
        supplierCity: "Gurugram, Haryana",
        supplierCostInr: "290.00", shippingCostInr: "80.00", gstPct: "12.00",
        sellingPriceInr: "699.00", mrpInr: "1499.00",
        customMarginPct: "40.00", netProfitInr: "244.00",
        aiScore: 91, viralVelocityScore: 87,
        stockCount: 780, moq: 1, hsnCode: "39269099",
        aiMarketingCopy: "Yoga mat jab thick ho, TPE material se bana ho, aur slip na kare — tab workout hoti hai asli. Boldfit ka 6mm mat lete ho toh joint pain bhi nahi.",
        aiTargetAudience: "Yoga practitioners, women 25–45, fitness influencers, apartment gym users",
        salesCount24h: 31,
      },
      {
        userId: demoUser.id, storeId: amazonStoreId,
        sku: "BD-STEEL-BOTTLE-06",
        title: "Milton Thermosteel Flip Lid Flask 1000ml — 24H Cold/18H Hot, 100% Leak-Proof (Assorted Colour)",
        category: "Kitchen & Dining",
        imageUrl: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80",
        brand: "Milton",
        supplierName: "Milton Industries Ltd, Bhiwandi Dist",
        supplierCity: "Thane, Maharashtra",
        supplierCostInr: "210.00", shippingCostInr: "70.00", gstPct: "12.00",
        sellingPriceInr: "549.00", mrpInr: "995.00",
        customMarginPct: "37.00", netProfitInr: "159.00",
        aiScore: 89, viralVelocityScore: 82,
        stockCount: 960, moq: 1, hsnCode: "73239990",
        aiMarketingCopy: "Office, gym, school, travel — Milton Thermosteel har jagah saath. 24 ghante thanda, 18 ghante garam. Ek baar kharido, saalon chale.",
        aiTargetAudience: "Students, working professionals, mothers, school kids — pan-India",
        salesCount24h: 44,
      },
      {
        userId: demoUser.id, storeId: glowroadStoreId,
        sku: "BD-SAREE-CLIP-07",
        title: "Vama Fashions Saree Shapewear Petticoat with Canvas Waistband, Nylon Dupion — Free Size (Beige)",
        category: "Women's Fashion",
        imageUrl: "https://images.unsplash.com/photo-1583391733956-6c78276477e1?w=600&auto=format&fit=crop&q=80",
        brand: "Vama Fashions",
        supplierName: "Surat Textile Market, Ring Road Fabric Hub",
        supplierCity: "Surat, Gujarat",
        supplierCostInr: "120.00", shippingCostInr: "50.00", gstPct: "5.00",
        sellingPriceInr: "349.00", mrpInr: "599.00",
        customMarginPct: "45.00", netProfitInr: "143.00",
        aiScore: 94, viralVelocityScore: 96,
        stockCount: 3200, moq: 1, hsnCode: "62042200",
        aiMarketingCopy: "Saree pehanna ab aur bhi comfortable — canvas waistband gir nahi ta, shape deta hai, aur free size mein ata hai. Surat ka bestselling petticoat.",
        aiTargetAudience: "Indian women 20–55, saree wearers, festival shoppers, Meesho resellers",
        salesCount24h: 234,
      },
      {
        userId: demoUser.id, storeId: meeshoStoreId,
        sku: "BD-TRIMMER-08",
        title: "Philips MG7715/65 MultiGroomer 15-in-1 Waterproof Beard & Hair Trimmer, Self-Sharpening Blade",
        category: "Personal Care & Grooming",
        imageUrl: "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=600&auto=format&fit=crop&q=80",
        brand: "Philips",
        supplierName: "Philips India Authorised Channel, Mumbai",
        supplierCity: "Mumbai, Maharashtra",
        supplierCostInr: "1080.00", shippingCostInr: "55.00", gstPct: "18.00",
        sellingPriceInr: "2299.00", mrpInr: "4995.00",
        customMarginPct: "46.00", netProfitInr: "930.00",
        aiScore: 96, viralVelocityScore: 93,
        stockCount: 540, moq: 1, hsnCode: "85102000",
        aiMarketingCopy: "Ek trimmer, 15 attachments — beard, mustache, body hair, nose, ear sab ek machine se. Philips ki quality pe trust karo.",
        aiTargetAudience: "Men 18–40, urban metro population, gifting for birthdays/festivals",
        salesCount24h: 58,
      },
      {
        userId: demoUser.id, storeId: flipkartStoreId,
        sku: "BD-LED-STRIP-09",
        title: "Syska 5M WiFi Smart LED Strip Lights RGB+IC, App & Voice Control, Music Sync — Cut to Size",
        category: "Smart Home",
        imageUrl: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=600&auto=format&fit=crop&q=80",
        brand: "Syska",
        supplierName: "Syska LED Lights India Pvt Ltd, Noida",
        supplierCity: "Noida, Uttar Pradesh",
        supplierCostInr: "390.00", shippingCostInr: "60.00", gstPct: "18.00",
        sellingPriceInr: "899.00", mrpInr: "1799.00",
        customMarginPct: "40.00", netProfitInr: "296.00",
        aiScore: 95, viralVelocityScore: 97,
        stockCount: 1100, moq: 1, hsnCode: "94054090",
        aiMarketingCopy: "Gaming room, bedroom, TV backlight — Syska 5M RGB strip. Alexa aur Google se bolo, phone se control karo. Music pe sync hota hai!",
        aiTargetAudience: "Gamers, college students room decor, urban flat owners, home improvement buyers",
        salesCount24h: 97,
      },
      {
        userId: demoUser.id, storeId: amazonStoreId,
        sku: "BD-FOOD-PROC-10",
        title: "Prestige Nippy Plus 400W Mini Food Processor & Chopper with 3 Stainless Steel Blades, 0.5L Bowl",
        category: "Kitchen & Dining",
        imageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&auto=format&fit=crop&q=80",
        brand: "Prestige",
        supplierName: "TTK Prestige Ltd Authorised Dist, Chennai",
        supplierCity: "Chennai, Tamil Nadu",
        supplierCostInr: "520.00", shippingCostInr: "90.00", gstPct: "18.00",
        sellingPriceInr: "1199.00", mrpInr: "2195.00",
        customMarginPct: "39.00", netProfitInr: "410.00",
        aiScore: 90, viralVelocityScore: 84,
        stockCount: 420, moq: 1, hsnCode: "85094000",
        aiMarketingCopy: "Sabzi, chutney, masala — sab kuch 30 seconds mein. Prestige Nippy Plus ki 400W motor bandh hi nahi hoti. Indian kitchen ka best companion.",
        aiTargetAudience: "Homemakers, small family households, cooking enthusiasts — Tier-1 & Tier-2 India",
        salesCount24h: 22,
      },
      {
        userId: demoUser.id, storeId: glowroadStoreId,
        sku: "BD-KURTA-MEN-11",
        title: "Manyavar Men Printed Cotton Kurta Pajama Set — Festive Ethnic Wear (M/L/XL/XXL) Mustard",
        category: "Men's Ethnic Fashion",
        imageUrl: "https://images.unsplash.com/photo-1583391733956-6c78276477e1?w=600&auto=format&fit=crop&q=80",
        brand: "Manyavar",
        supplierName: "Surat Textile Wholesale, Umra",
        supplierCity: "Surat, Gujarat",
        supplierCostInr: "280.00", shippingCostInr: "70.00", gstPct: "5.00",
        sellingPriceInr: "699.00", mrpInr: "1299.00",
        customMarginPct: "43.00", netProfitInr: "254.00",
        aiScore: 92, viralVelocityScore: 91,
        stockCount: 1800, moq: 1, hsnCode: "62032200",
        aiMarketingCopy: "Diwali, Eid, Navratri, shaadi — Manyavar kurta pajama set se look bana zabardast. Cotton fabric, machine wash safe, festive print.",
        aiTargetAudience: "Men 22–50, festival buyers, wedding season, Meesho & Glowroad resellers",
        salesCount24h: 167,
      },
      {
        userId: demoUser.id, storeId: meeshoStoreId,
        sku: "BD-LAPTOP-TABLE-12",
        title: "Green Soul Jupiter Foldable Laptop Table with Dual Fan Cooling Pad & Adjustable Height (Wood/Black)",
        category: "Furniture & Storage",
        imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&auto=format&fit=crop&q=80",
        brand: "Green Soul",
        supplierName: "Green Soul Ergonomics, Noida Sector-6",
        supplierCity: "Noida, Uttar Pradesh",
        supplierCostInr: "680.00", shippingCostInr: "120.00", gstPct: "18.00",
        sellingPriceInr: "1599.00", mrpInr: "2999.00",
        customMarginPct: "41.00", netProfitInr: "579.00",
        aiScore: 93, viralVelocityScore: 89,
        stockCount: 390, moq: 1, hsnCode: "94034090",
        aiMarketingCopy: "Bed pe baith ke kaam karo bina back pain ke — foldable laptop table, cooling fan built-in, height adjust karo jaise chahiye. WFH must-have.",
        aiTargetAudience: "WFH employees, students, gamers, Tier-1 apartment dwellers",
        salesCount24h: 29,
      },
    ];

    const insertedProducts = await db.insert(products).values(productRows).returning();

    // ── 4. BUYER'S PERSONAL DROPSHIPPING CART ──────────────────────────────────
    const cartRows = [
      {
        userId: demoUser.id,
        productId: insertedProducts[0].id, // USB Hub
        productTitle: insertedProducts[0].title,
        productImageUrl: insertedProducts[0].imageUrl,
        sku: insertedProducts[0].sku,
        quantity: 3,
        customSellingPriceInr: "1099.00",
        supplierCostInr: insertedProducts[0].supplierCostInr,
        shippingCostInr: insertedProducts[0].shippingCostInr,
        gstPct: insertedProducts[0].gstPct,
        customMarginPct: "47.00",
        netProfitInr: "484.00",
        targetPlatform: "Amazon India",
        notes: "Bump price ₹100 — Amazon buyers pay premium for branded dongle",
      },
      {
        userId: demoUser.id,
        productId: insertedProducts[1].id, // boAt Earbuds
        productTitle: insertedProducts[1].title,
        productImageUrl: insertedProducts[1].imageUrl,
        sku: insertedProducts[1].sku,
        quantity: 5,
        customSellingPriceInr: "1349.00",
        supplierCostInr: insertedProducts[1].supplierCostInr,
        shippingCostInr: insertedProducts[1].shippingCostInr,
        gstPct: insertedProducts[1].gstPct,
        customMarginPct: "38.00",
        netProfitInr: "484.00",
        targetPlatform: "Flipkart",
        notes: "Price ₹150 neeche rakha Flipkart competition beat karne ke liye",
      },
      {
        userId: demoUser.id,
        productId: insertedProducts[3].id, // Neck Fan
        productTitle: insertedProducts[3].title,
        productImageUrl: insertedProducts[3].imageUrl,
        sku: insertedProducts[3].sku,
        quantity: 10,
        customSellingPriceInr: "549.00",
        supplierCostInr: insertedProducts[3].supplierCostInr,
        shippingCostInr: insertedProducts[3].shippingCostInr,
        gstPct: insertedProducts[3].gstPct,
        customMarginPct: "52.00",
        netProfitInr: "229.00",
        targetPlatform: "Meesho",
        notes: "Summer peak — margin badhao. Meesho pe 0% commission, extra profit.",
      },
      {
        userId: demoUser.id,
        productId: insertedProducts[6].id, // Saree Shapewear
        productTitle: insertedProducts[6].title,
        productImageUrl: insertedProducts[6].imageUrl,
        sku: insertedProducts[6].sku,
        quantity: 20,
        customSellingPriceInr: "399.00",
        supplierCostInr: insertedProducts[6].supplierCostInr,
        shippingCostInr: insertedProducts[6].shippingCostInr,
        gstPct: insertedProducts[6].gstPct,
        customMarginPct: "50.00",
        netProfitInr: "179.00",
        targetPlatform: "Glowroad",
        notes: "Festival season ke liye bulk — Navratri & Diwali combo listing",
      },
    ];

    await db.insert(cartItems).values(cartRows);

    // ── 5. LIVE ORDERS (Indian customers) ──────────────────────────────────────
    await db.insert(orders).values([
      {
        userId: demoUser.id, storeId: meeshoStoreId,
        orderNumber: "BD-M-10421", customerName: "Priya Patel",
        customerEmail: "priya.patel92@gmail.com", customerPhone: "9876543210",
        customerCity: "Ahmedabad", customerState: "Gujarat", customerPincode: "380001",
        productId: insertedProducts[3].id, productTitle: insertedProducts[3].title,
        quantity: 2, customerPaidInr: "998.00", supplierCostInr: "480.00",
        gstAmountInr: "90.00", platformCommissionInr: "0.00", netProfitInr: "356.00",
        fulfillmentStatus: "Delivered", supplierTrackingCode: "DELHIVERY7429018",
        carrierName: "Delhivery Surface", paymentMode: "UPI",
        aiDecisionLog: "AI matched Priya's order to Surat stock. Delhivery pickup confirmed in 4.2 hours. Delivered in 3 days.",
      },
      {
        userId: demoUser.id, storeId: flipkartStoreId,
        orderNumber: "BD-F-10422", customerName: "Amit Sharma",
        customerEmail: "amitsharma@hotmail.com", customerPhone: "9812345678",
        customerCity: "Lucknow", customerState: "Uttar Pradesh", customerPincode: "226001",
        productId: insertedProducts[1].id, productTitle: insertedProducts[1].title,
        quantity: 1, customerPaidInr: "1499.00", supplierCostInr: "730.00",
        gstAmountInr: "135.00", platformCommissionInr: "119.92", netProfitInr: "514.08",
        fulfillmentStatus: "In Transit", supplierTrackingCode: "EKART8834729",
        carrierName: "Ekart Logistics", paymentMode: "COD",
        aiDecisionLog: "COD order verified. Ekart pickup done from Delhi warehouse. Expected delivery: 2 days.",
      },
      {
        userId: demoUser.id, storeId: amazonStoreId,
        orderNumber: "BD-A-10423", customerName: "Sunita Mehta",
        customerEmail: "sunita.mehta@yahoo.in", customerPhone: "9988776655",
        customerCity: "Pune", customerState: "Maharashtra", customerPincode: "411001",
        productId: insertedProducts[2].id, productTitle: insertedProducts[2].title,
        quantity: 1, customerPaidInr: "799.00", supplierCostInr: "395.00",
        gstAmountInr: "48.00", platformCommissionInr: "95.88", netProfitInr: "260.12",
        fulfillmentStatus: "Auto-Ordered", supplierTrackingCode: "AMZIN5592018",
        carrierName: "Amazon Logistics", paymentMode: "Card",
        aiDecisionLog: "Amazon FBA order. AI auto-placed restock request to Bengaluru supplier. Estimated dispatch: 6 hours.",
      },
      {
        userId: demoUser.id, storeId: glowroadStoreId,
        orderNumber: "BD-G-10424", customerName: "Meena Joshi",
        customerEmail: "meena.joshi@gmail.com", customerPhone: "8765432109",
        customerCity: "Jaipur", customerState: "Rajasthan", customerPincode: "302001",
        productId: insertedProducts[6].id, productTitle: insertedProducts[6].title,
        quantity: 3, customerPaidInr: "1047.00", supplierCostInr: "510.00",
        gstAmountInr: "25.00", platformCommissionInr: "0.00", netProfitInr: "512.00",
        fulfillmentStatus: "AI Checking", supplierTrackingCode: "PENDING_DISPATCH",
        carrierName: "Shiprocket Bluedart", paymentMode: "UPI",
        aiDecisionLog: "Festival bulk order detected. AI verifying Surat supplier stock availability before dispatching.",
      },
      {
        userId: demoUser.id, storeId: meeshoStoreId,
        orderNumber: "BD-M-10425", customerName: "Ravi Kumar",
        customerEmail: "ravikumar.blr@gmail.com", customerPhone: "9900112233",
        customerCity: "Bengaluru", customerState: "Karnataka", customerPincode: "560001",
        productId: insertedProducts[8].id, productTitle: insertedProducts[8].title,
        quantity: 1, customerPaidInr: "899.00", supplierCostInr: "450.00",
        gstAmountInr: "81.00", platformCommissionInr: "0.00", netProfitInr: "368.00",
        fulfillmentStatus: "Incoming", supplierTrackingCode: "PENDING_AI_QUEUE",
        carrierName: "Shiprocket", paymentMode: "COD",
        aiDecisionLog: "New webhook order received from Meesho. Fraud check: SAFE. Auto-fulfillment queued in 1.8 seconds.",
      },
    ]);

    // ── 6. AUTOMATION RULES (India focused) ────────────────────────────────────
    await db.insert(automationRules).values([
      {
        userId: demoUser.id,
        name: "Meesho Viral Score ≥94 — Zero-Commission Auto-Publish",
        description: "Jab koi product ka AI score 94+ ho, Meesho pe automatically publish karo bina commission ke. India ke best drop channel.",
        triggerType: "VIRAL_SCORE_ABOVE", triggerThreshold: "94.00",
        actionType: "AUTO_IMPORT_AND_PUBLISH", actionParam: "Meesho + Glowroad India",
        isEnabled: true, executionCount: 47,
      },
      {
        userId: demoUser.id,
        name: "COD Order — Instant Delhivery Pickup Auto-Book",
        description: "COD order aate hi Delhivery surface pickup auto-schedule karo. 4-hour SLA for Tier-1 pincodes.",
        triggerType: "ORDER_RECEIVED", triggerThreshold: "0.00",
        actionType: "AUTO_FULFILL", actionParam: "Delhivery Surface + Ekart Backup",
        isEnabled: true, executionCount: 312,
      },
      {
        userId: demoUser.id,
        name: "Margin Floor 35% — Auto Price Bump (Elastic)",
        description: "Agar kisi product ka net margin 35% se neeche jaye (supplier rate increase), AI selling price automatically adjust kare.",
        triggerType: "MARGIN_BELOW", triggerThreshold: "35.00",
        actionType: "DYNAMIC_REPRICE", actionParam: "Maintain 35% floor + ₹9 rounding",
        isEnabled: true, executionCount: 14,
      },
      {
        userId: demoUser.id,
        name: "Surat Stock <50 Units — Switch to Bhiwandi Warehouse",
        description: "Jab Surat supplier stock 50 units se kam ho, auto-switch to Bhiwandi (Mumbai) backup fulfillment center.",
        triggerType: "STOCK_LOW", triggerThreshold: "50.00",
        actionType: "SWITCH_SUPPLIER", actionParam: "Bhiwandi Mumbai Express Depot",
        isEnabled: true, executionCount: 8,
      },
      {
        userId: demoUser.id,
        name: "Festival Season Demand — Bulk Price Boost (Oct–Nov)",
        description: "Navratri, Diwali, Bhai Dooj window mein fashion & home decor products ka price 12% auto-boost for max festival margin.",
        triggerType: "SEASONAL_FESTIVAL", triggerThreshold: "10.00",
        actionType: "DYNAMIC_REPRICE", actionParam: "+12% festival markup auto-apply",
        isEnabled: true, executionCount: 6,
      },
    ]);

    // ── 7. AI ACTIVITY STREAM ─────────────────────────────────────────────────
    await db.insert(aiActivityLogs).values([
      {
        userId: demoUser.id, agentName: "Scout-AI v4.2 // Meesho Radar",
        actionType: "TREND_DETECTED",
        message: "Neck fan ki demand 3x spike Meesho App search data mein. Surat supplier se MOQ-1 locked. Auto-publish to Meesho & Glowroad.",
        profitImpactInr: "178.00", status: "SUCCESS",
      },
      {
        userId: demoUser.id, agentName: "Zero-Touch Core // COD Auto-Fulfill",
        actionType: "ORDER_FULFILLED",
        message: "BD-M-10421 (Priya Patel, Ahmedabad) — Delhivery pickup confirmed ₹480 supplier paid. Net profit locked ₹356.",
        profitImpactInr: "356.00", status: "SUCCESS",
      },
      {
        userId: demoUser.id, agentName: "Reprice-Sentinel // GST Margin Guard",
        actionType: "PRICE_OPTIMIZED",
        message: "boAt Earbuds supplier cost ₹680 up se ₹640 ho gayi. Margin 44%→48%. Flipkart price maintained for competitiveness.",
        profitImpactInr: "40.00", status: "SUCCESS",
      },
      {
        userId: demoUser.id, agentName: "Cart-AI // Margin Advisor",
        actionType: "CART_MARGIN_ALERT",
        message: "USB Hub cart entry pe ₹1099 selling price: margin 47% — above your 35% floor. Approved for Amazon India listing.",
        profitImpactInr: "484.00", status: "INFO",
      },
      {
        userId: demoUser.id, agentName: "GST-Guard // Compliance Engine",
        actionType: "GST_CALCULATED",
        message: "BD-A-10423 ke liye IGST 12% = ₹48 automatically calculated. GSTIN 27AAPFU0939F1ZV se invoice generated.",
        profitImpactInr: "0.00", status: "SUCCESS",
      },
    ]);

    return demoUser;
  } catch (err) {
    console.error("Seed error:", err);
    return null;
  }
}
