import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { db } from "@/db";
import { storefrontOrders } from "@/db/schema";
import { eq } from "drizzle-orm";
import { appendPaymentMeta, readPaymentMeta } from "@/lib/payments/token-plan";
import { cashfreeBaseUrl, cashfreeCredentials, gatewayMode } from "@/lib/payments/gateway";
export const runtime="nodejs";export const dynamic="force-dynamic";
function appOrigin(req:Request){for(const value of [process.env.PUBLIC_APP_URL,process.env.NEXT_PUBLIC_SITE_URL,process.env.RENDER_EXTERNAL_URL,new URL(req.url).origin,"https://bharatshop-9w4a.onrender.com"]){try{if(!value)continue;const u=new URL(value);if(u.protocol==="https:"&&!/^(0\.0\.0\.0|127\.|localhost)/i.test(u.hostname))return u.origin;}catch{}}return"https://bharatshop-9w4a.onrender.com";}
export async function POST(req:Request){try{const {clientId,clientSecret}=cashfreeCredentials();if(!clientId||!clientSecret)return NextResponse.json({error:"Cashfree is not configured on the server"},{status:503});const body=(await req.json()) as {orderRefs?:unknown[];orderRef?:unknown};const rawRefs:unknown[]=Array.isArray(body.orderRefs)?body.orderRefs:[body.orderRef];const refs:string[]=[...new Set(rawRefs.map(x=>String(x||"").trim()).filter(Boolean))].slice(0,20);if(!refs.length)return NextResponse.json({error:"orderRef or orderRefs is required"},{status:400});return await db.transaction(async tx=>{const rows:Array<typeof storefrontOrders.$inferSelect>=[];for(const ref of [...refs].sort()){const[row]=await tx.select().from(storefrontOrders).where(eq(storefrontOrders.orderRef,ref)).limit(1).for("update");if(!row)return NextResponse.json({error:`Order ${ref} not found`},{status:404});rows.push(row);}if(rows.some(o=>!["PARTIAL_COD_CASHFREE","CASHFREE"].includes(String(o.paymentMode))))return NextResponse.json({error:"These orders are not assigned to Cashfree"},{status:409});if(rows.some(o=>!["TOKEN_PENDING","PAYMENT_PENDING","FAILED","TOKEN_FAILED"].includes(String(o.paymentStatus))))return NextResponse.json({error:"One or more orders are not payable in the current state"},{status:409});const amounts=rows.map(o=>String(o.paymentMode)==="PARTIAL_COD_CASHFREE"?Number(readPaymentMeta(o.notes??undefined,"confirmation_amount_inr")):Number(o.totalAmountInr)),total=Number(amounts.reduce((a,b)=>a+b,0).toFixed(2));if(!Number.isFinite(total)||total<1)return NextResponse.json({error:"Invalid confirmation amount"},{status:400});const previous=rows.map(o=>readPaymentMeta(o.notes??undefined,"cashfree_order_id"));
if(previous.some(Boolean)){
 if(!previous.every(id=>id&&id===previous[0]))return NextResponse.json({error:"Retry the original checkout group"},{status:409});
 const live=gatewayMode()==="live",base=cashfreeBaseUrl();
 const response=await fetch(`${base}/orders/${encodeURIComponent(previous[0])}`,{headers:{"x-client-id":clientId,"x-client-secret":clientSecret,"x-api-version":process.env.CASHFREE_API_VERSION||"2025-01-01"},cache:"no-store",signal:AbortSignal.timeout(15000)});
 if(!response.ok)return NextResponse.json({error:"Unable to resume Cashfree checkout"},{status:502});const existing=await response.json();
 if(Number(existing.order_amount)!==total||existing.order_currency!=="INR"||!existing.payment_session_id)return NextResponse.json({error:"Checkout amount or session does not match the gateway order"},{status:409});
 return NextResponse.json({provider:"cashfree",mode:live?"production":"sandbox",gatewayOrderId:previous[0],paymentSessionId:existing.payment_session_id,orderRefs:refs,confirmationAmountInr:total},{headers:{"Cache-Control":"no-store"}});
}
const gatewayOrderId=`BSCF${Date.now().toString(36).toUpperCase()}${Math.random().toString(36).slice(2,5).toUpperCase()}`.slice(0,45),origin=appOrigin(req),live=gatewayMode()==="live",base=cashfreeBaseUrl(),first=rows[0];const response=await fetch(`${base}/orders`,{method:"POST",signal:AbortSignal.timeout(15000),headers:{"x-client-id":clientId,"x-client-secret":clientSecret,"x-api-version":process.env.CASHFREE_API_VERSION||"2025-01-01","Content-Type":"application/json","x-idempotency-key":randomUUID()},body:JSON.stringify({order_id:gatewayOrderId,order_amount:total,order_currency:"INR",customer_details:{customer_id:`BS${first.id}`,customer_name:first.customerName,customer_email:first.customerEmail,customer_phone:first.customerPhone},order_meta:{return_url:`${origin}/checkout/success?provider=cashfree&gateway_order_id=${encodeURIComponent(gatewayOrderId)}`,notify_url:`${origin}/api/payments/cashfree/webhook`},order_note:`BharatShop confirmation for ${refs.length} order(s)`})});const payload=await response.json();if(!response.ok||!payload?.payment_session_id)return NextResponse.json({error:payload?.message||"Unable to create Cashfree order"},{status:502});for(const o of rows){const notes=appendPaymentMeta(o.notes??undefined,{cashfree_order_id:gatewayOrderId,gateway_amount_inr:total.toFixed(2)});await tx.update(storefrontOrders).set({notes,paymentStatus:String(o.paymentMode).startsWith("PARTIAL_COD_")?"TOKEN_PENDING":"PAYMENT_PENDING"}).where(eq(storefrontOrders.id,o.id));}return NextResponse.json({provider:"cashfree",mode:live?"production":"sandbox",gatewayOrderId,paymentSessionId:payload.payment_session_id,orderRefs:refs,confirmationAmountInr:total},{headers:{"Cache-Control":"no-store"}});});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Cashfree order creation failed"},{status:500});}}
