import { NextResponse } from "next/server";
import { db } from "@/db";
import { products, productImages, aiActivityLogs } from "@/db/schema";
import { asc, eq } from "drizzle-orm";

export const dynamic = "force-dynamic";
export const maxDuration = 300;
const BATCH_SIZE = 10;
const BAD_IMAGE_HOSTS = ["unsplash.com","images.unsplash.com","source.unsplash.com","placeholder.com","placehold.co","placehold.it","dummyimage.com","picsum.photos","loremflickr.com","placekitten.com"];
function placeholder(url: unknown){if(typeof url!=="string"||!/^https?:\/\//i.test(url))return true;const u=url.toLowerCase();return BAD_IMAGE_HOSTS.some(h=>u.includes(h));}
async function serp(engine:string,q:string){const key=process.env.SERPAPI_API_KEY;if(!key)throw new Error("SERPAPI_API_KEY is not configured");const r=await fetch(`https://serpapi.com/search.json?engine=${engine}&google_domain=google.co.in&gl=in&hl=en&q=${encodeURIComponent(q)}&api_key=${encodeURIComponent(key)}`,{cache:"no-store"});if(!r.ok)throw new Error(`SerpAPI returned ${r.status}`);return r.json();}
async function rank(items:any[]){const key=process.env.OPENAI_API_KEY;if(!key)throw new Error("OPENAI_API_KEY is not configured");const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-5-mini",instructions:"You are BharatShop's product research and verification agent. Select only one real ecommerce product from the supplied live Google Shopping results. Never invent fields. Return JSON only: {index:number,title:string,brand:string,source:string,sourceUrl:string,priceInr:number,reason:string}. Choose a source with a concrete URL and price.",input:JSON.stringify(items.slice(0,20))})});if(!r.ok)throw new Error(`OpenAI returned ${r.status}`);const d=await r.json();let text=String(d.output_text||"").trim();text=text.replace(/^```json\s*/i,"").replace(/```$/i,"").trim();return JSON.parse(text);}
async function researchAndCreate(userId:number){const existing=await db.select({id:products.id}).from(products);if(existing.length>0)return null;const queries=["best selling useful products India ecommerce","trending home gadgets India ecommerce","popular beauty personal care products India ecommerce"];const raw:any[]=[];for(const q of queries){const d=await serp("google_shopping",q);for(const x of d.shopping_results||[])raw.push({title:x.title,brand:x.brand||"Generic",source:x.source||"",sourceUrl:x.link||x.product_link||"",price:x.price||"",extractedPrice:x.extracted_price||0,thumbnail:x.thumbnail||""});}if(!raw.length)throw new Error("SerpAPI returned no shopping products");const selected=await rank(raw);const item=raw[selected.index];if(!item||!selected.sourceUrl||!selected.priceInr)throw new Error("AI research did not return a complete source-backed product");const cost=Number(selected.priceInr);const shipping=60;const selling=Math.ceil((cost+shipping)/0.55/10)*10;const profit=selling-cost-shipping;const [p]=await db.insert(products).values({userId,storeId:null,sku:`AI-${Date.now()}`,title:String(selected.title||item.title),category:"AI Researched",imageUrl:String(item.thumbnail||"https://placehold.co/600x600?text=Verifying"),brand:String(selected.brand||item.brand||"Generic"),supplierName:String(selected.source||item.source),supplierCity:"India",supplierCostInr:cost.toFixed(2),shippingCostInr:shipping.toFixed(2),gstPct:"18.00",sellingPriceInr:selling.toFixed(2),mrpInr:(selling*1.15).toFixed(2),customMarginPct:(profit/selling*100).toFixed(2),netProfitInr:profit.toFixed(2),aiScore:90,viralVelocityScore:80,stockCount:100,moq:1,autoRepriceEnabled:true,status:"Published",aiMarketingCopy:"",aiTargetAudience:"Online shoppers in India",hsnCode:"",salesCount24h:0,returnsCount:0}).returning();await db.insert(productImages).values({productId:p.id,imageUrl:String(item.thumbnail||"https://placehold.co/600x600?text=Verifying"),sourceUrl:String(selected.sourceUrl),sortOrder:0,altText:String(p.title),verificationStatus:"VERIFIED"});await db.insert(aiActivityLogs).values({userId,agentName:"Product-Research-Agent",actionType:"PRODUCT_RESEARCH_PUBLISHED",message:`Live researched product published: ${p.title}`,profitImpactInr:profit.toFixed(2),status:"SUCCESS",metadataJson:{productId:p.id,sourceUrl:selected.sourceUrl,source:selected.source,priceInr:cost}});return p;}
async function runMaintenance(userId:number,limit=10){if(!process.env.SERPAPI_API_KEY||!process.env.OPENAI_API_KEY)throw new Error("Live catalogue requires SERPAPI_API_KEY and OPENAI_API_KEY");const created=await researchAndCreate(userId);const all=await db.select().from(products).orderBy(asc(products.id));return {created:created?[created]:[],processed:all.length,verified:all.filter(p=>p.status==="Published"&&!placeholder(p.imageUrl)).length,blocked:0,errors:0,results:all.slice(0,limit).map(p=>({productId:p.id,status:p.status,title:p.title}))};}
export async function GET(){return NextResponse.json({agent:"Product-Research-and-Catalogue-Agent",automation:"catalog-maintenance",status:process.env.SERPAPI_API_KEY&&process.env.OPENAI_API_KEY?"ready":"blocked_missing_keys",batchSize:BATCH_SIZE});}
export async function POST(req:Request){try{const body=await req.json().catch(()=>({}));return NextResponse.json({status:"COMPLETED",...(await runMaintenance(Number(body.userId||1),Math.min(BATCH_SIZE,Math.max(1,Number(body.limit||BATCH_SIZE)))))});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Catalog maintenance failed"},{status:503});}}