"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, ChevronLeft, ChevronRight, Heart, Loader2, Minus, Plus, Search, ShieldCheck, ShoppingBag, Sparkles, Truck, X } from "lucide-react";

type Product={
  id:number;sku:string;title:string;category:string;brand:string;imageUrl:string;imageUrls?:string[];imageLabels?:string[];
  sellingPriceInr:string;mrpInr:string;stockCount:number;madeToOrder?:boolean;availabilityMode?:string;productionSupplier?:string;sizeOptions?:string[];
  aiMarketingCopy?:string;details?:{description?:string;colorOptions?:string;includedItems?:string;specificationsJson?:unknown;variantsJson?:unknown}|null;
};
type CartItem={product:Product;qty:number;size?:string};
const CATS=["ALL","Electronics & Gadgets","Wearables & Watches","Women's Fashion","Men's Fashion","Beauty & Skincare","Kitchen & Dining","Sports & Fitness","Personal Care & Grooming","Smart Home","Baby & Kids"];
const money=(v:string|number)=>`₹${Number(v||0).toLocaleString("en-IN")}`;
const discount=(m:string,p:string)=>{const a=Number(m),b=Number(p);return a>b&&a>0?Math.round((a-b)/a*100):0};
const customerCopy=(t?:string)=>String(t||"").replace(/ghar\s*baithe[^.!?]*[.!?]?/gi,"").replace(/(?:profit|margin|supplier|source|wholesale|meesho|dropship|earning|commission)[^.!?]*[.!?]?/gi,"").replace(/₹\s*[\d,]+\s*(?:per sale|profit|earning)[^.!?]*[.!?]?/gi,"").replace(/\s{2,}/g," ").trim()||"Carefully selected for quality, value and everyday usefulness.";

function Gallery({p}:{p:Product}){
  const imgs=useMemo(()=>Array.from(new Set([...(p.imageUrls||[]),p.imageUrl].filter(Boolean))).slice(0,8),[p]);
  const[i,setI]=useState(0);useEffect(()=>setI(0),[p.id]);
  return <div className="w-full min-w-0">
    <div className="relative w-full aspect-[4/3] sm:aspect-square max-h-[62vh] bg-white rounded-2xl border border-slate-100 flex items-center justify-center overflow-hidden">
      {imgs[i]?<img src={imgs[i]} alt={`${p.title} ${p.imageLabels?.[i]||`view ${i+1}`}`} className="w-full h-full object-contain p-2 sm:p-5"/>:<div className="text-slate-400">Image coming soon</div>}
      {imgs.length>1&&<><button type="button" aria-label="Previous image" onClick={()=>setI(x=>(x-1+imgs.length)%imgs.length)} className="absolute left-2 sm:left-3 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-white/95 shadow flex items-center justify-center"><ChevronLeft/></button><button type="button" aria-label="Next image" onClick={()=>setI(x=>(x+1)%imgs.length)} className="absolute right-2 sm:right-3 top-1/2 -translate-y-1/2 w-10 h-10 rounded-full bg-white/95 shadow flex items-center justify-center"><ChevronRight/></button><span className="absolute bottom-3 right-3 text-xs bg-slate-900/75 text-white rounded-full px-2 py-1">{i+1} / {imgs.length}</span></>}
    </div>
    <div className="flex gap-2 sm:gap-3 overflow-x-auto py-3 snap-x">{imgs.map((u,n)=><button type="button" key={`${u}-${n}`} aria-label={`View image ${n+1}`} onClick={()=>setI(n)} className={`flex-none w-16 h-16 sm:w-20 sm:h-20 snap-start rounded-xl border-2 bg-white overflow-hidden ${i===n?"border-orange-500":"border-slate-100"}`}><img src={u} alt="" className="w-full h-full object-contain"/></button>)}</div>
  </div>;
}

function Card({p,onOpen,onWish,wished}:{p:Product;onOpen:(p:Product)=>void;onWish:(id:number)=>void;wished:boolean}){
  const d=discount(p.mrpInr,p.sellingPriceInr);
  return <article className="group bg-white rounded-2xl border border-slate-100 hover:border-slate-200 hover:shadow-xl transition overflow-hidden">
    <div className="relative aspect-square bg-slate-50 flex items-center justify-center p-3 sm:p-5 cursor-pointer" onClick={()=>onOpen(p)}><img src={p.imageUrl} alt={p.title} className="w-full h-full object-contain group-hover:scale-105 transition"/>{p.madeToOrder?<span className="absolute top-3 left-3 bg-violet-600 text-white text-[10px] font-black rounded-full px-2 py-1">MADE TO ORDER</span>:d>0?<span className="absolute top-3 left-3 bg-red-500 text-white text-[10px] font-black rounded-full px-2 py-1">{d}% OFF</span>:null}<button type="button" aria-label="Add to wishlist" onClick={e=>{e.stopPropagation();onWish(p.id)}} className={`absolute top-3 right-3 w-9 h-9 rounded-full bg-white/95 shadow flex items-center justify-center ${wished?"text-red-500":"text-slate-500"}`}><Heart size={17} className={wished?"fill-current":""}/></button></div>
    <div className="p-3 sm:p-4"><p className="text-[10px] sm:text-[11px] font-black text-orange-600 uppercase tracking-wider">{p.brand}</p><h3 onClick={()=>onOpen(p)} className="font-bold text-sm text-slate-900 line-clamp-2 min-h-10 mt-1 cursor-pointer">{p.title}</h3>{p.madeToOrder&&<p className="text-[11px] text-violet-600 font-bold mt-1">Produced by {p.productionSupplier||"Qikink"} after you order</p>}<div className="flex items-baseline gap-2 mt-2"><span className="text-lg sm:text-xl font-black">{money(p.sellingPriceInr)}</span>{d>0&&<span className="text-xs text-slate-400 line-through">{money(p.mrpInr)}</span>}</div><button type="button" onClick={()=>onOpen(p)} className="mt-3 w-full h-10 rounded-xl bg-slate-900 text-white text-sm font-black">View product</button></div>
  </article>;
}

function Detail({p,onClose,onAdd,onBuy,wished,onWish}:{p:Product;onClose:()=>void;onAdd:(p:Product,q:number,size?:string)=>void;onBuy:(p:Product,q:number,size?:string)=>void;wished:boolean;onWish:(id:number)=>void}){
  const[q,setQ]=useState(1),[size,setSize]=useState(p.sizeOptions?.[0]||"");const d=discount(p.mrpInr,p.sellingPriceInr);const max=p.madeToOrder?10:Math.max(1,Number(p.stockCount)||1);const unavailable=!p.madeToOrder&&Number(p.stockCount)<=0;
  return <div className="fixed inset-0 z-[70] bg-slate-950/70 backdrop-blur-sm overflow-y-auto sm:p-5"><div className="min-h-full sm:min-h-0 sm:max-w-6xl sm:mx-auto bg-white sm:rounded-3xl shadow-2xl overflow-hidden">
    <div className="sticky top-0 z-10 bg-white flex justify-between items-center p-4 border-b"><span className="text-sm text-slate-500">Product details</span><button type="button" aria-label="Close product" onClick={onClose} className="w-10 h-10 rounded-full bg-slate-100 flex items-center justify-center"><X/></button></div>
    <div className="grid lg:grid-cols-2 gap-5 lg:gap-10 p-4 sm:p-7"><Gallery p={p}/><section><div className="flex items-center justify-between gap-3"><p className="text-xs font-black text-orange-600 uppercase tracking-widest">{p.brand}</p><button type="button" onClick={()=>onWish(p.id)} className={`flex items-center gap-2 text-sm font-bold ${wished?"text-red-500":"text-slate-500"}`}><Heart size={18} className={wished?"fill-current":""}/>{wished?"Saved":"Save"}</button></div><h1 className="text-2xl sm:text-4xl font-black leading-tight mt-2">{p.title}</h1>{p.madeToOrder&&<div className="mt-4 rounded-2xl bg-violet-50 border border-violet-100 p-4"><p className="font-black text-violet-800">Made to order by {p.productionSupplier||"Qikink"}</p><p className="text-sm text-violet-700 mt-1">BharatShop Studio creates the design; Qikink produces and fulfils the garment after your order enters the production queue.</p></div>}<p className="text-slate-600 leading-7 mt-5">{customerCopy(p.aiMarketingCopy)}</p><div className="flex flex-wrap items-end gap-3 mt-6"><b className="text-3xl sm:text-4xl">{money(p.sellingPriceInr)}</b>{d>0&&<><span className="line-through text-slate-400">{money(p.mrpInr)}</span><span className="font-black text-green-600">Save {money(Number(p.mrpInr)-Number(p.sellingPriceInr))}</span></>}</div>
      <div className="grid grid-cols-3 gap-2 sm:gap-3 mt-7"><div className="rounded-2xl bg-slate-50 p-3"><Truck className="w-5 text-orange-500"/><b className="text-[11px] sm:text-xs block mt-2">Doorstep delivery</b></div><div className="rounded-2xl bg-slate-50 p-3"><ShieldCheck className="w-5 text-green-500"/><b className="text-[11px] sm:text-xs block mt-2">Secure ordering</b></div><div className="rounded-2xl bg-slate-50 p-3"><Sparkles className="w-5 text-blue-500"/><b className="text-[11px] sm:text-xs block mt-2">Verified listing</b></div></div>
      {p.madeToOrder&&p.sizeOptions?.length?<div className="mt-6"><label className="text-sm font-black">Size</label><div className="flex flex-wrap gap-2 mt-2">{p.sizeOptions.map(s=><button type="button" key={s} onClick={()=>setSize(s)} className={`min-w-12 h-10 px-3 rounded-xl border font-bold text-sm ${size===s?"bg-slate-900 text-white border-slate-900":"border-slate-200"}`}>{s}</button>)}</div></div>:null}
      <div className="flex items-center gap-4 mt-7"><b className="text-sm">Quantity</b><div className="flex border rounded-xl"><button type="button" aria-label="Decrease quantity" onClick={()=>setQ(x=>Math.max(1,x-1))} className="p-3"><Minus size={16}/></button><span className="px-3 py-3 font-black">{q}</span><button type="button" aria-label="Increase quantity" onClick={()=>setQ(x=>Math.min(max,x+1))} className="p-3"><Plus size={16}/></button></div><span className={`text-sm font-bold ${unavailable?"text-red-600":"text-green-600"}`}>{p.madeToOrder?"Made after order":unavailable?"Currently unavailable":"In stock"}</span></div>
      <div className="flex gap-3 mt-6"><button type="button" disabled={unavailable} onClick={()=>onAdd(p,q,size||undefined)} className="flex-1 h-12 rounded-xl border-2 border-slate-900 font-black disabled:opacity-40">Add to bag</button><button type="button" disabled={unavailable} onClick={()=>onBuy(p,q,size||undefined)} className="flex-1 h-12 rounded-xl bg-orange-500 text-white font-black shadow-lg disabled:opacity-40">Buy now</button></div>
    </section></div>
    <div className="border-t p-5 sm:p-8 grid md:grid-cols-3 gap-5"><div><h3 className="font-black">Why you’ll love it</h3><p className="text-sm text-slate-500 mt-2">Clear pricing, strong product imagery and a simple BharatShop checkout.</p></div><div><h3 className="font-black">Product details</h3><p className="text-sm text-slate-500 mt-2">Brand: {p.brand}<br/>Category: {p.category}{p.details?.colorOptions?<><br/>Colours: {p.details.colorOptions}</>:null}</p></div><div><h3 className="font-black">Availability</h3><p className="text-sm text-slate-500 mt-2">{p.madeToOrder?`This design is produced on demand by ${p.productionSupplier||"Qikink"}; it is not presented as warehouse stock.`:"This item is sold from verified supplier availability."}</p></div></div>
  </div></div>;
}

function Checkout({items,onClose,onDone}:{items:CartItem[];onClose:()=>void;onDone:(refs:string[])=>void}){
  const[f,setF]=useState({name:"",email:"",phone:"",address:"",city:"",state:"",pincode:""}),[busy,setBusy]=useState(false),[err,setErr]=useState("");const total=items.reduce((s,x)=>s+Number(x.product.sellingPriceInr)*x.qty,0);
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setErr("");try{const refs:string[]=[];for(const item of items){const r=await fetch("/api/storefront/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customerName:f.name,customerEmail:f.email,customerPhone:f.phone,customerAddress:f.address,customerCity:f.city,customerState:f.state,customerPincode:f.pincode,productId:item.product.id,quantity:item.qty,selectedSize:item.size,paymentMode:"COD"})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to place order");refs.push(d.ref)}onDone(refs)}catch(e){setErr(e instanceof Error?e.message:"Please try again")}finally{setBusy(false)}}
  return <div className="fixed inset-0 z-[80] bg-slate-950/70 backdrop-blur-sm p-3 flex items-center justify-center"><form onSubmit={submit} className="w-full max-w-2xl max-h-[96vh] overflow-y-auto bg-white rounded-3xl shadow-2xl p-5 sm:p-6"><div className="flex justify-between items-start"><div><p className="text-xs font-black text-orange-600 uppercase tracking-wider">Secure checkout</p><h2 className="text-2xl font-black mt-1">Almost yours</h2></div><button type="button" aria-label="Close checkout" onClick={onClose} className="w-9 h-9 rounded-full bg-slate-100 flex items-center justify-center"><X size={18}/></button></div><div className="mt-5 space-y-3">{items.map((x,i)=><div key={`${x.product.id}-${x.size||i}`} className="flex gap-3 p-3 rounded-2xl bg-slate-50"><img src={x.product.imageUrl} alt="" className="w-16 h-16 object-contain bg-white rounded-xl"/><div className="flex-1"><p className="font-bold text-sm line-clamp-2">{x.product.title}</p>{x.size&&<p className="text-xs text-violet-600 font-bold">Size {x.size}</p>}<p className="text-orange-600 font-black">{money(x.product.sellingPriceInr)} × {x.qty}</p></div><b>{money(Number(x.product.sellingPriceInr)*x.qty)}</b></div>)}</div><div className="grid grid-cols-2 gap-3 mt-5">{[["name","Full name"],["phone","Phone number"],["email","Email address"],["address","Delivery address"],["city","City"],["state","State"],["pincode","Pincode"]].map(([k,ph])=><input key={k} required type={k==="email"?"email":"text"} pattern={k==="pincode"?"[0-9]{6}":undefined} value={(f as any)[k]} onChange={e=>setF({...f,[k]:e.target.value})} placeholder={ph} className={`${k==="address"||k==="email"?"col-span-2":""} h-11 rounded-xl border border-slate-200 px-3 text-sm focus:outline-none focus:ring-2 focus:ring-orange-200`}/>)}</div><div className="mt-4 rounded-2xl border p-4 flex gap-3"><Truck className="w-5 text-orange-500"/><div><b className="text-sm">Cash on Delivery</b><p className="text-xs text-slate-500">Qikink fashion orders enter production after order validation.</p></div></div>{err&&<p className="mt-3 p-3 rounded-xl bg-red-50 text-red-600 text-sm">{err}</p>}<div className="mt-5 flex justify-between items-center"><div><p className="text-xs text-slate-400">Order total</p><p className="text-2xl font-black">{money(total)}</p></div><button type="submit" disabled={busy} className="h-12 px-7 rounded-xl bg-orange-500 text-white font-black flex gap-2 items-center disabled:opacity-60">{busy?<Loader2 className="animate-spin" size={18}/>:<CheckCircle2 size={18}/>} {busy?"Placing…":"Place order"}</button></div></form></div>;
}

function Success({refs,onClose}:{refs:string[];onClose:()=>void}){return <div className="fixed inset-0 z-[90] bg-slate-950/70 backdrop-blur-sm flex items-center justify-center p-4"><div className="bg-white rounded-3xl p-8 max-w-md w-full text-center shadow-2xl"><CheckCircle2 className="w-14 h-14 text-green-500 mx-auto"/><h2 className="text-3xl font-black mt-4">Order confirmed</h2><p className="text-slate-500 mt-2">Your order is in BharatShop. We’ll move supplier items through fulfilment and Qikink fashion through the production queue.</p><div className="space-y-2 mt-5">{refs.map(r=><p key={r} className="font-mono font-black text-orange-600 bg-orange-50 rounded-xl p-3">{r}</p>)}</div><button type="button" onClick={onClose} className="w-full h-12 bg-slate-900 text-white rounded-xl font-black mt-6">Continue shopping</button></div></div>}

export default function StorePage(){
  const[products,setProducts]=useState<Product[]>([]),[category,setCategory]=useState("ALL"),[query,setQuery]=useState(""),[sort,setSort]=useState("aiScore"),[loading,setLoading]=useState(true),[selected,setSelected]=useState<Product|null>(null),[cart,setCart]=useState<CartItem[]>([]),[cartOpen,setCartOpen]=useState(false),[wishlist,setWishlist]=useState<number[]>([]),[checkout,setCheckout]=useState<CartItem[]|null>(null),[refs,setRefs]=useState<string[]>([]);
  useEffect(()=>{try{setWishlist(JSON.parse(localStorage.getItem("bharatshop-wishlist")||"[]"))}catch{}},[]);useEffect(()=>{localStorage.setItem("bharatshop-wishlist",JSON.stringify(wishlist))},[wishlist]);
  useEffect(()=>{let live=true;setLoading(true);const t=setTimeout(()=>{fetch(`/api/storefront/products?category=${encodeURIComponent(category)}&search=${encodeURIComponent(query)}&sort=${sort}&limit=96`).then(async r=>{if(!r.ok)throw new Error("Catalogue unavailable");return r.json()}).then(d=>{if(live)setProducts(d.products||[])}).catch(()=>{if(live)setProducts([])}).finally(()=>live&&setLoading(false))},query?250:0);return()=>{live=false;clearTimeout(t)}},[category,query,sort]);
  const add=(p:Product,q:number,size?:string)=>{setCart(c=>{const x=c.find(i=>i.product.id===p.id&&i.size===size);return x?c.map(i=>i.product.id===p.id&&i.size===size?{...i,qty:Math.min(p.madeToOrder?10:Number(p.stockCount)||99,i.qty+q)}:i):[...c,{product:p,qty:q,size}]});setSelected(null);setCartOpen(true)};
  const buy=(p:Product,q:number,size?:string)=>{setSelected(null);setCheckout([{product:p,qty:q,size}])},wish=(id:number)=>setWishlist(x=>x.includes(id)?x.filter(i=>i!==id):[...x,id]),cartTotal=cart.reduce((s,x)=>s+Number(x.product.sellingPriceInr)*x.qty,0),complete=(orderRefs:string[])=>{setRefs(orderRefs);setCheckout(null);setCart([])};
  return <main className="min-h-screen bg-slate-50 text-slate-900"><header className="sticky top-0 z-40 bg-white/95 backdrop-blur border-b"><div className="max-w-7xl mx-auto min-h-16 px-3 sm:px-4 py-2 flex items-center gap-2 sm:gap-3"><button type="button" onClick={()=>{setCategory("ALL");setQuery("")}} className="font-black text-xl sm:text-2xl tracking-tight text-orange-600">BharatShop</button><div className="flex-1 relative max-w-2xl ml-auto"><Search className="absolute left-3 top-3 w-4 text-slate-400"/><input aria-label="Search products" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products" className="w-full h-10 pl-9 pr-3 rounded-xl bg-slate-100 focus:bg-white border border-transparent focus:border-orange-200 outline-none"/></div><button type="button" aria-label="Open shopping bag" onClick={()=>setCartOpen(true)} className="relative w-10 h-10 rounded-xl bg-slate-900 text-white flex items-center justify-center"><ShoppingBag size={19}/>{cart.length>0&&<span className="absolute -top-1 -right-1 w-5 h-5 rounded-full bg-orange-500 text-[10px] font-black flex items-center justify-center">{cart.reduce((s,x)=>s+x.qty,0)}</span>}</button></div></header>
    <div className="bg-slate-900 text-white"><div className="max-w-7xl mx-auto px-4 py-3 flex items-center justify-between gap-4"><div><p className="text-xs text-orange-300 font-black uppercase tracking-widest">BharatShop</p><p className="font-black text-lg">Verified finds + original Qikink fashion.</p></div><button type="button" onClick={()=>document.getElementById("deals")?.scrollIntoView({behavior:"smooth"})} className="hidden sm:flex items-center gap-2 text-sm font-black">Shop now <ArrowRight size={16}/></button></div></div>
    <div className="border-b bg-white overflow-x-auto"><div className="max-w-7xl mx-auto px-4 flex gap-2 py-3">{CATS.map(c=><button type="button" key={c} onClick={()=>setCategory(c)} className={`whitespace-nowrap px-4 py-2 rounded-full text-xs font-black ${category===c?"bg-orange-500 text-white":"bg-slate-100 text-slate-600"}`}>{c.replace(" & Gadgets","")}</button>)}</div></div>
    <section id="deals" className="max-w-7xl mx-auto px-3 sm:px-4 pt-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black text-orange-600 uppercase tracking-widest">Live catalogue</p><h1 className="text-3xl sm:text-4xl font-black mt-1">Products worth opening.</h1><p className="text-slate-500 mt-2">Supplier-backed products and BharatShop Studio fashion produced by Qikink.</p></div><select aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm font-bold"><option value="aiScore">Recommended</option><option value="popular">Popular</option><option value="newest">New arrivals</option><option value="price_low">Price: Low to high</option><option value="price_high">Price: High to low</option></select></div>
      {loading?<div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 sm:gap-4 mt-7">{Array.from({length:8}).map((_,i)=><div key={i} className="aspect-[3/4] rounded-2xl bg-white border border-slate-100 animate-pulse"/>)}</div>:products.length?<><div className="flex items-center justify-between mt-6"><p className="text-sm text-slate-500"><b className="text-slate-900">{products.length}</b> products loaded</p>{products.some(p=>p.madeToOrder)&&<span className="text-xs font-bold text-violet-700 bg-violet-50 px-3 py-1.5 rounded-full">Qikink made-to-order fashion is live</span>}</div><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 sm:gap-4 mt-3">{products.map(p=><Card key={p.id} p={p} onOpen={setSelected} onWish={wish} wished={wishlist.includes(p.id)}/>)}</div></>:<div className="mt-8 rounded-3xl bg-white border p-10 text-center"><ShoppingBag className="mx-auto text-slate-300" size={42}/><h2 className="font-black text-xl mt-3">We’re refreshing the shelves.</h2><p className="text-slate-500 mt-1">Try another search or category.</p></div>}
    </section>
    <section className="max-w-7xl mx-auto px-4 py-12"><div className="rounded-3xl bg-white border p-6"><p className="font-black text-xl">BharatShop Studio</p><p className="text-sm text-slate-500 mt-1">Original men’s, women’s and kids’ fashion is designed in BharatShop and mapped to Qikink print-on-demand production. These products are explicitly shown as made to order rather than fake warehouse stock.</p></div></section>
    {selected&&<Detail p={selected} onClose={()=>setSelected(null)} onAdd={add} onBuy={buy} wished={wishlist.includes(selected.id)} onWish={wish}/>} {checkout&&<Checkout items={checkout} onClose={()=>setCheckout(null)} onDone={complete}/>} {refs.length>0&&<Success refs={refs} onClose={()=>setRefs([])}/>} 
    {cartOpen&&<div className="fixed inset-0 z-[60] bg-slate-950/50" onClick={()=>setCartOpen(false)}><aside onClick={e=>e.stopPropagation()} className="absolute right-0 top-0 h-full w-full max-w-md bg-white shadow-2xl p-5 flex flex-col"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Your bag</h2><p className="text-xs text-slate-400 mt-1">{cart.reduce((s,x)=>s+x.qty,0)} item(s)</p></div><button type="button" aria-label="Close bag" onClick={()=>setCartOpen(false)} className="w-9 h-9 rounded-full bg-slate-100 flex items-center justify-center"><X size={18}/></button></div>{cart.length===0?<div className="flex-1 flex flex-col items-center justify-center text-center"><ShoppingBag className="w-12 h-12 text-slate-200"/><p className="font-black mt-4">Your bag is waiting</p></div>:<><div className="flex-1 overflow-y-auto py-5 space-y-4">{cart.map((i,n)=><div key={`${i.product.id}-${i.size||n}`} className="flex gap-3"><img src={i.product.imageUrl} alt="" className="w-20 h-20 rounded-xl bg-slate-50 object-contain"/><div className="flex-1"><p className="font-bold text-sm line-clamp-2">{i.product.title}</p>{i.size&&<p className="text-xs font-bold text-violet-600">Size {i.size}</p>}<p className="font-black text-orange-600 mt-1">{money(i.product.sellingPriceInr)}</p><div className="flex items-center mt-2 border rounded-lg w-fit"><button type="button" onClick={()=>setCart(c=>c.map((x,idx)=>idx===n?{...x,qty:Math.max(1,x.qty-1)}:x))} className="p-1.5"><Minus size={13}/></button><span className="px-2 text-xs font-bold">{i.qty}</span><button type="button" onClick={()=>setCart(c=>c.map((x,idx)=>idx===n?{...x,qty:Math.min(x.product.madeToOrder?10:Number(x.product.stockCount)||99,x.qty+1)}:x))} className="p-1.5"><Plus size={13}/></button></div></div><button type="button" aria-label="Remove item" onClick={()=>setCart(c=>c.filter((_,idx)=>idx!==n))} className="text-slate-300 hover:text-red-500"><X size={16}/></button></div>)}</div><div className="border-t pt-5"><div className="flex justify-between mb-4"><span className="font-bold">Total</span><span className="text-xl font-black">{money(cartTotal)}</span></div><button type="button" onClick={()=>{setCheckout(cart);setCartOpen(false)}} className="w-full h-12 rounded-xl bg-orange-500 text-white font-black">Proceed to checkout</button></div></>}</aside></div>}
  </main>;
}
