import { NextResponse } from "next/server";
import { db } from "@/db";
import { productImages, productDetails, products } from "@/db/schema";
import { desc } from "drizzle-orm";

const BAD_IMAGE=/(?:unsplash\.com|source\.unsplash\.com|via\.placeholder\.com|placeholder\.com|placehold\.co|placehold\.it|dummyimage\.com|picsum\.photos|loremflickr\.com|placekitten\.com)/i;
const LOCAL_HOST=/^(?:0\.0\.0\.0|127(?:\.\d{1,3}){3}|localhost|\[::1\])$/i;
const APPROVED_SOURCE_MEDIA=new Set(["AI_VISION_VERIFIED","LOCAL_EVIDENCE_VERIFIED"]),APPROVED_SOURCE_PROVIDERS=new Set(["local-ai","local-evidence"]);
const MIN_IMAGES=4,MIN_CONFIDENCE=.75;
export const dynamic="force-dynamic";
const specsOf=(d:any)=>d?.specificationsJson&&typeof d.specificationsJson==="object"&&!Array.isArray(d.specificationsJson)?d.specificationsJson as Record<string,any>:{};
const madeToOrder=(d:any)=>String(specsOf(d).inventoryMode||"").toUpperCase()==="MADE_TO_ORDER"&&String(specsOf(d).productionSupplier||"").toLowerCase()==="qikink";
function publicOrigin(req:Request){for(const value of [process.env.PUBLIC_APP_URL,process.env.NEXT_PUBLIC_SITE_URL,process.env.RENDER_EXTERNAL_URL,new URL(req.url).origin,"https://bharatshop-9w4a.onrender.com"]){try{if(!value)continue;const u=new URL(value);if(u.protocol==="https:"&&!LOCAL_HOST.test(u.hostname))return u.origin;}catch{}}return"https://bharatshop-9w4a.onrender.com";}
function cleanUrl(value:unknown,origin:string){let raw=String(value||"").trim();if(!raw||BAD_IMAGE.test(raw))return"";try{const u=new URL(raw);if(LOCAL_HOST.test(u.hostname)&&u.pathname.startsWith("/api/fashion-art/"))raw=`${origin}${u.pathname}${u.search}`;}catch{return"";}return/^https:\/\//i.test(raw)&&!BAD_IMAGE.test(raw)?raw:"";}
function customerText(value:unknown){return String(value||"").split(/(?<=[.!?])\s+/).filter(sentence=>!/(?:qikink|deodap|supplier|source url|wholesale|dropship|margin|net profit|commission|rate card|procurement|fulfil(?:l)?ment partner|production partner)/i.test(sentence)).join(" ").replace(/\b(?:Qikink|DeoDap)\b/gi,"").replace(/\s{2,}/g," ").trim();}

export async function GET(req:Request){
 const{searchParams}=new URL(req.url),origin=publicOrigin(req),category=searchParams.get("category")||"",search=searchParams.get("search")||searchParams.get("query")||"",sort=searchParams.get("sort")||"aiScore",limit=Math.min(Math.max(parseInt(searchParams.get("limit")||"24",10)||24,1),96),page=Math.max(parseInt(searchParams.get("page")||"1",10)||1,1),featured=searchParams.get("featured")==="true",requestedId=Math.max(parseInt(searchParams.get("id")||"0",10)||0,0);
 const[all,imageRows,detailRows]=await Promise.all([db.select().from(products).orderBy(desc(products.aiScore)),db.select().from(productImages),db.select().from(productDetails)]),detailMap=new Map(detailRows.map(x=>[x.productId,x])),galleryMap=new Map<number,{url:string;label:string;order:number}[]>();
 for(const row of imageRows){const image=cleanUrl(row.imageUrl,origin);if(!image||!row.verifiedAt)continue;const d=detailMap.get(row.productId),s=specsOf(d),sourceBacked=APPROVED_SOURCE_MEDIA.has(String(row.verificationStatus))&&Number(row.verificationConfidence)>=MIN_CONFIDENCE&&APPROVED_SOURCE_PROVIDERS.has(String(row.verificationProvider)),originalFashion=String(row.verificationStatus)==="AI_GENERATED_ORIGINAL"&&String(row.verificationProvider)==="bharatshop-studio"&&String(s.designOrigin)==="BharatShop Studio"&&madeToOrder(d);if(!sourceBacked&&!originalFashion)continue;const current=galleryMap.get(row.productId)||[];if(!current.some(x=>x.url===image))current.push({url:image,label:customerText(row.altText),order:Number(row.sortOrder)||0});galleryMap.set(row.productId,current.sort((a,b)=>a.order-b.order).slice(0,8));}
 const publishable=all.filter(p=>{const gallery=galleryMap.get(p.id)||[],d=detailMap.get(p.id),mto=madeToOrder(d),validPricing=Number(p.sellingPriceInr)>0&&Number(p.mrpInr)>=Number(p.sellingPriceInr),availabilityValid=mto||Number(p.stockCount)>0;return p.status==="Published"&&Boolean(p.title)&&validPricing&&availabilityValid&&gallery.length>=MIN_IMAGES;});let filtered=publishable;if(requestedId)filtered=filtered.filter(p=>p.id===requestedId);if(featured)filtered=filtered.filter(p=>p.aiScore>=92);if(category&&category!=="ALL")filtered=filtered.filter(p=>p.category===category);if(search){const q=search.toLowerCase().trim();filtered=filtered.filter(p=>p.title.toLowerCase().includes(q)||p.brand.toLowerCase().includes(q)||p.category.toLowerCase().includes(q));}if(sort==="price_low")filtered.sort((a,b)=>Number(a.sellingPriceInr)-Number(b.sellingPriceInr));else if(sort==="price_high")filtered.sort((a,b)=>Number(b.sellingPriceInr)-Number(a.sellingPriceInr));else if(sort==="newest")filtered.sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime());else if(sort==="popular")filtered.sort((a,b)=>b.salesCount24h-a.salesCount24h);else filtered.sort((a,b)=>b.aiScore-a.aiScore);
 const total=filtered.length,offset=(page-1)*limit,paginated=filtered.slice(offset,offset+limit),customerProducts=paginated.map(p=>{const gallery=galleryMap.get(p.id)||[],imageUrls=gallery.map(x=>x.url).slice(0,8),imageLabels=imageUrls.map(u=>gallery.find(x=>x.url===u)?.label||""),d=detailMap.get(p.id),spec=specsOf(d),mto=madeToOrder(d),media=spec.media&&typeof spec.media==="object"&&!Array.isArray(spec.media)?spec.media as Record<string,unknown>:{},productVideos=Array.isArray(media.videos)?media.videos.filter(v=>typeof v==="string"&&/^https:\/\//i.test(v as string)):[],sizeOptions=Array.isArray(spec.sizes)?spec.sizes.map(String):[];return{id:p.id,sku:`BS-${p.id}`,title:p.title,category:p.category,brand:p.brand,imageUrl:imageUrls[0]||"",imageUrls,imageLabels,productVideos,sellingPriceInr:p.sellingPriceInr,mrpInr:p.mrpInr,stockCount:Number(p.stockCount)||0,madeToOrder:mto,availabilityMode:mto?"MADE_TO_ORDER":"IN_STOCK",sizeOptions,aiMarketingCopy:customerText(p.aiMarketingCopy),details:d?{description:customerText(d.description),includedItems:customerText(d.includedItems),dimensions:d.dimensions,weight:d.weight,material:d.material,colorOptions:d.colorOptions,warranty:customerText(d.warranty),countryOfOrigin:d.countryOfOrigin,careInstructions:customerText(d.careInstructions)}:null};}),catCounts:Record<string,number>={};publishable.forEach(p=>{const c=String(p.category||"Other").trim()||"Other";catCounts[c]=(catCounts[c]||0)+1;});return NextResponse.json({products:customerProducts,total,page,totalPages:Math.max(1,Math.ceil(total/limit)),categoryCount:catCounts,privacy:"customer-safe",availabilityPolicy:"Only customer-relevant availability is exposed."},{headers:{"Cache-Control":"no-store"}});
}
