import { NextResponse } from "next/server";
import { db } from "@/db";
import { storefrontOrders, orders, products, productDetails, aiActivityLogs } from "@/db/schema";
import { createHash, randomUUID } from "node:crypto";
import { desc, eq, sql } from "drizzle-orm";
import { getAdminUser } from "@/lib/admin-auth";
import { appendPaymentMeta, partialCodPlan, readPaymentMeta } from "@/lib/payments/token-plan";
import { inventoryReservationMeta, reserveInventory } from "@/lib/orders/inventory-reservation";

export const dynamic="force-dynamic";
function specsOf(details:any){return details?.specificationsJson&&typeof details.specificationsJson==="object"&&!Array.isArray(details.specificationsJson)?details.specificationsJson as Record<string,any>:{};}
async function backendAuthorized(req:Request){const expected=process.env.BHARATSHOP_AUTOMATION_TOKEN||process.env.AUTOMATION_TOKEN||"",supplied=req.headers.get("authorization")?.replace(/^Bearer\s+/i,"")||req.headers.get("x-automation-token")||"";if(expected&&supplied===expected)return true;return !!(await getAdminUser());}

export async function GET(req:Request){if(!(await backendAuthorized(req)))return NextResponse.json({error:"Backend authorization required"},{status:401});const{searchParams}=new URL(req.url),status=searchParams.get("status"),limit=Math.min(Math.max(parseInt(searchParams.get("limit")||"50"),1),100);const all=await db.select().from(storefrontOrders).orderBy(desc(storefrontOrders.orderedAt)).limit(limit),filtered=status&&status!=="ALL"?all.filter(o=>o.fulfillmentStatus===status):all;return NextResponse.json({orders:filtered,total:filtered.length},{headers:{"Cache-Control":"no-store"}});}

export async function POST(req:Request){
 try{
  const body=await req.json();if(!body||typeof body!=="object"||Array.isArray(body))return NextResponse.json({error:"Invalid order request"},{status:400});const{customerName,customerEmail,customerPhone,customerAddress,customerCity,customerState,customerPincode,productId,quantity=1,paymentMode="PARTIAL_COD_RAZORPAY",selectedSize}=body;
  if(!customerName||!customerEmail||!customerPhone||!customerAddress||!customerCity||!customerState||!customerPincode||!productId)return NextResponse.json({error:"Complete delivery and contact details are required"},{status:400});
  const qty=Number(quantity);if(!Number.isInteger(qty)||qty<1||qty>100)return NextResponse.json({error:"Quantity must be an integer between 1 and 100"},{status:400});
  if(!/^\d{6}$/.test(String(customerPincode)))return NextResponse.json({error:"A valid 6-digit pincode is required"},{status:400});
  const normalizedPaymentMode=String(paymentMode).toUpperCase();const allowed=["COD","RAZORPAY","CASHFREE","PARTIAL_COD_RAZORPAY","PARTIAL_COD_CASHFREE"];if(!allowed.includes(normalizedPaymentMode))return NextResponse.json({error:"Unsupported payment mode"},{status:400});
  const id=Number(productId);if(!Number.isSafeInteger(id)||id<1)return NextResponse.json({error:"Invalid product ID"},{status:400});
  const fields=[customerName,customerEmail,customerPhone,customerAddress,customerCity,customerState,customerPincode];
  if(fields.some(value=>typeof value!=="string"||!value.trim()||value.length>1000))return NextResponse.json({error:"Invalid delivery details"},{status:400});
  const key=req.headers.get("Idempotency-Key");
  if(key!==null&&!/^[A-Za-z0-9_-]{16,128}$/.test(key))return NextResponse.json({error:"Invalid idempotency key"},{status:400});
  const requestHash=createHash("sha256").update(JSON.stringify([...fields.map(value=>value.trim()),id,qty,normalizedPaymentMode,String(selectedSize||"").trim()])).digest("hex");
  const ref=key?`BS-WEB-${createHash("sha256").update(key).digest("hex")}`:`BS-WEB-${randomUUID()}`;
  return await db.transaction(async tx=>{
  if(key){
    // Serialize retries across workers without a schema change or an in-memory lock.
    await tx.execute(sql`select pg_advisory_xact_lock(hashtextextended(${ref}, 0))`);
    const[existing]=await tx.select().from(storefrontOrders).where(eq(storefrontOrders.orderRef,ref)).limit(1);
    if(existing){
      if(readPaymentMeta(existing.notes||"","checkout_request_hash")!==requestHash)return NextResponse.json({error:"This checkout key was already used for a different order"},{status:409});
      if(String(existing.paymentStatus||"").toUpperCase()==="CANCELLED"||String(existing.fulfillmentStatus||"").toUpperCase()==="CANCELLED")return NextResponse.json({error:"This checkout was cancelled. Start a new checkout attempt."},{status:409});
      const total=Number(existing.totalAmountInr),confirmation=Number(readPaymentMeta(existing.notes||"","confirmation_amount_inr")),cod=Number(readPaymentMeta(existing.notes||"","cod_balance_inr"));
      return NextResponse.json({ref,madeToOrder:readPaymentMeta(existing.notes||"","made_to_order")==="true",paymentMode:existing.paymentMode,paymentStatus:existing.paymentStatus,paymentPlan:{confirmationAmountInr:confirmation,codBalanceInr:cod,totalAmountInr:total,confirmationPct:total>0?Math.round(confirmation/total*10000)/100:0},message:"Existing order retrieved."},{status:200,headers:{"Cache-Control":"no-store"}});
    }
  }
  const[product]=await tx.select().from(products).where(eq(products.id,Number(productId))).limit(1);if(!product)return NextResponse.json({error:"Product not found"},{status:404});if(product.status!=="Published")return NextResponse.json({error:"Product is not currently published"},{status:409});
  const[details]=await tx.select().from(productDetails).where(eq(productDetails.productId,product.id)).limit(1),specs=specsOf(details),fashionBrand=["bharatshop studio","bharatdrip"].includes(String(product.brand||"").toLowerCase()),madeToOrder=product.supplierName==="Qikink"&&fashionBrand&&String(specs.inventoryMode||"").toUpperCase()==="MADE_TO_ORDER"&&String(specs.productionSupplier||"").toLowerCase()==="qikink";
  if(madeToOrder){const sizes=Array.isArray(specs.sizes)?specs.sizes.map(String):[],size=String(selectedSize||"").trim();if(!size||!sizes.includes(size))return NextResponse.json({error:"Please select a valid size",availableSizes:sizes},{status:400});if(qty>10)return NextResponse.json({error:"Made-to-order quantity is limited to 10 per item"},{status:400});}
  else if(Number(product.stockCount)<qty)return NextResponse.json({error:"Insufficient stock"},{status:409});
  const unitPrice=Number(product.sellingPriceInr),total=Number((unitPrice*qty).toFixed(2)),isPartial=normalizedPaymentMode.startsWith("PARTIAL_COD_");
  if(!Number.isFinite(unitPrice)||unitPrice<=0||!Number.isFinite(total))return NextResponse.json({error:"Product price is unavailable"},{status:409});
  const plan=isPartial?partialCodPlan({sellingPriceInr:unitPrice,netProfitInr:Number(product.netProfitInr),quantity:qty}):{strategy:"FULL_OR_LEGACY" as const,totalAmountInr:total,confirmationAmountInr:normalizedPaymentMode==="COD"?0:total,codBalanceInr:normalizedPaymentMode==="COD"?total:0,confirmationPct:normalizedPaymentMode==="COD"?0:100};
  const paymentStatus=isPartial?"TOKEN_PENDING":normalizedPaymentMode==="COD"?"PENDING":"PAYMENT_PENDING",fulfillmentStatus=isPartial?"TOKEN_PAYMENT_PENDING":madeToOrder?"PRODUCTION_REVIEW_REQUIRED":normalizedPaymentMode==="COD"?"RECHECK_REQUIRED":"PAYMENT_PENDING";
  if(!madeToOrder){const reservation=await reserveInventory(tx,product.id,qty);if(!reservation.reserved)return NextResponse.json({error:"Insufficient stock"},{status:409});}
  let note=madeToOrder?`Internal production route: product ${String(specs.qikinkProductCode||"")}; size ${String(selectedSize||"")}. Supplier submission is backend-only.`:"";
  note=appendPaymentMeta(note,{checkout_request_hash:requestHash,made_to_order:madeToOrder,payment_strategy:plan.strategy,confirmation_amount_inr:plan.confirmationAmountInr.toFixed(2),cod_balance_inr:plan.codBalanceInr.toFixed(2),payment_provider:isPartial?normalizedPaymentMode.replace("PARTIAL_COD_",""):normalizedPaymentMode,...inventoryReservationMeta(madeToOrder,qty)});
  const[created]=await tx.insert(storefrontOrders).values({orderRef:ref,customerName:String(customerName).trim(),customerEmail:String(customerEmail).trim(),customerPhone:String(customerPhone).trim(),customerAddress:String(customerAddress).trim(),customerCity:String(customerCity).trim(),customerState:String(customerState).trim(),customerPincode:String(customerPincode).trim(),productId:product.id,productTitle:product.title,productImageUrl:product.imageUrl,quantity:qty,sellingPriceInr:unitPrice.toFixed(2),totalAmountInr:total.toFixed(2),paymentMode:normalizedPaymentMode,paymentStatus,fulfillmentStatus,source:"own_website",notes:note}).returning();
  const supplierTotal=(Number(product.supplierCostInr)+Number(product.shippingCostInr))*qty,gstAmount=Number(product.supplierCostInr)*Number(product.gstPct)/100*qty,commission=total*.08,netProfit=total-supplierTotal-gstAmount-commission;
  const[core]=await tx.insert(orders).values({userId:product.userId,storeId:product.storeId,orderNumber:ref,customerName:created.customerName,customerEmail:created.customerEmail,customerPhone:created.customerPhone,customerAddress:created.customerAddress,customerCity:created.customerCity,customerState:created.customerState,customerPincode:created.customerPincode,productId:product.id,productTitle:product.title,quantity:qty,customerPaidInr:total.toFixed(2),supplierCostInr:supplierTotal.toFixed(2),gstAmountInr:gstAmount.toFixed(2),platformCommissionInr:commission.toFixed(2),netProfitInr:netProfit.toFixed(2),fulfillmentStatus,supplierTrackingCode:null,carrierName:madeToOrder?"Print-on-demand production":null,paymentMode:normalizedPaymentMode,paymentStatus,aiDecisionLog:`Storefront order ${ref}. Partial-COD policy=${isPartial}; confirmation=${plan.confirmationAmountInr}; COD balance=${plan.codBalanceInr}. CEO policy controls post-payment routing.`}).returning();
  await tx.insert(aiActivityLogs).values({userId:product.userId,agentName:"Storefront Order Gateway",actionType:isPartial?"PARTIAL_COD_TOKEN_REQUIRED":"STOREFRONT_ORDER",message:`Order ${ref} created. Payment gate=${paymentStatus}; fulfillment=${fulfillmentStatus}.`,profitImpactInr:String(core.netProfitInr),metadataJson:{productId:product.id,qty,selectedSize:madeToOrder?selectedSize:undefined,paymentMode:normalizedPaymentMode,confirmationAmountInr:plan.confirmationAmountInr,codBalanceInr:plan.codBalanceInr,madeToOrder},status:"SUCCESS"});
  return NextResponse.json({ref,madeToOrder,paymentMode:normalizedPaymentMode,paymentStatus,paymentPlan:{confirmationAmountInr:plan.confirmationAmountInr,codBalanceInr:plan.codBalanceInr,totalAmountInr:plan.totalAmountInr,confirmationPct:plan.confirmationPct},message:isPartial?"Pay the confirmation amount online; the remaining balance is payable on delivery.":"Order created."},{status:201,headers:{"Cache-Control":"no-store"}});
  });
 }catch(err:unknown){return NextResponse.json({error:err instanceof SyntaxError?"Invalid JSON request":"Unable to create order. Please retry."},{status:err instanceof SyntaxError?400:500});}
}

export async function PATCH(req:Request){if(!(await backendAuthorized(req)))return NextResponse.json({error:"Backend authorization required"},{status:401});try{const body=await req.json(),{id,fulfillmentStatus,trackingCode,carrierName}=body;if(!id)return NextResponse.json({error:"Order ID required"},{status:400});const allowedFulfillment=["TOKEN_PAYMENT_PENDING","RECHECK_REQUIRED","PURCHASE_PENDING","PAYMENT_PENDING","PRODUCTION_REVIEW_REQUIRED","CEO_ROUTING_READY","Received","AI Checking","Supplier Ordered","In Transit","Delivered","Cancelled","PAYMENT_BLOCKED"];if(fulfillmentStatus&&!allowedFulfillment.includes(fulfillmentStatus))return NextResponse.json({error:"Invalid fulfillment status"},{status:400});const[updated]=await db.update(storefrontOrders).set({...(fulfillmentStatus&&{fulfillmentStatus}),...(trackingCode&&{trackingCode:String(trackingCode)}),...(carrierName&&{carrierName:String(carrierName)}),...(fulfillmentStatus==="Delivered"&&{fulfilledAt:new Date()})}).where(eq(storefrontOrders.id,Number(id))).returning();if(!updated)return NextResponse.json({error:"Order not found"},{status:404});await db.update(orders).set({...(fulfillmentStatus&&{fulfillmentStatus}),...(trackingCode&&{supplierTrackingCode:String(trackingCode)}),...(carrierName&&{carrierName:String(carrierName)}),...(fulfillmentStatus==="Delivered"&&{fulfilledAt:new Date()})}).where(eq(orders.orderNumber,updated.orderRef));return NextResponse.json({order:updated});}catch(err:unknown){return NextResponse.json({error:err instanceof Error?err.message:"Error"},{status:500});}}
