import { NextResponse } from "next/server";
import { db } from "@/db";
import { storefrontOrders, orders, products, productDetails, aiActivityLogs } from "@/db/schema";
import { desc, eq } from "drizzle-orm";

export async function GET(req:Request){const{searchParams}=new URL(req.url),status=searchParams.get("status"),limit=Math.min(Math.max(parseInt(searchParams.get("limit")||"50"),1),100);const all=await db.select().from(storefrontOrders).orderBy(desc(storefrontOrders.orderedAt)).limit(limit),filtered=status&&status!=="ALL"?all.filter(o=>o.fulfillmentStatus===status):all;return NextResponse.json({orders:filtered,total:filtered.length});}

function specsOf(details:any){return details?.specificationsJson&&typeof details.specificationsJson==="object"&&!Array.isArray(details.specificationsJson)?details.specificationsJson as Record<string,any>:{};}

export async function POST(req:Request){
 try{
  const body=await req.json();const{customerName,customerEmail,customerPhone,customerAddress,customerCity,customerState,customerPincode,productId,quantity=1,paymentMode="COD",selectedSize}=body;
  if(!customerName||!customerEmail||!customerPhone||!productId)return NextResponse.json({error:"Name, email, phone, productId required"},{status:400});
  const qty=Number(quantity);if(!Number.isInteger(qty)||qty<1||qty>100)return NextResponse.json({error:"Quantity must be an integer between 1 and 100"},{status:400});
  const normalizedPaymentMode=String(paymentMode).toUpperCase();if(!["COD","RAZORPAY","CASHFREE"].includes(normalizedPaymentMode))return NextResponse.json({error:"Unsupported payment mode"},{status:400});
  const[product]=await db.select().from(products).where(eq(products.id,Number(productId))).limit(1);if(!product)return NextResponse.json({error:"Product not found"},{status:404});if(product.status!=="Published")return NextResponse.json({error:"Product is not currently published"},{status:409});
  const[details]=await db.select().from(productDetails).where(eq(productDetails.productId,product.id)).limit(1);const specs=specsOf(details);const madeToOrder=product.supplierName==="Qikink"&&product.brand==="BharatShop Studio"&&String(specs.inventoryMode||"").toUpperCase()==="MADE_TO_ORDER"&&String(specs.productionSupplier||"").toLowerCase()==="qikink";
  if(madeToOrder){
    const sizes=Array.isArray(specs.sizes)?specs.sizes.map(String):[];const size=String(selectedSize||"").trim();if(!size||!sizes.includes(size))return NextResponse.json({error:"Please select a valid size for this Qikink made-to-order product",availableSizes:sizes},{status:400});if(qty>10)return NextResponse.json({error:"Made-to-order fashion quantity is limited to 10 per checkout"},{status:400});
  }else if(Number(product.stockCount)<qty)return NextResponse.json({error:"Insufficient stock"},{status:409});
  const unitPrice=Number(product.sellingPriceInr),total=(unitPrice*qty).toFixed(2),ref=`BS-WEB-${Date.now().toString(36).toUpperCase()}`;const paymentStatus="PENDING";
  const fulfillmentStatus=madeToOrder?"QIKINK_SUBMISSION_APPROVAL_REQUIRED":(normalizedPaymentMode==="COD"?"RECHECK_REQUIRED":"PAYMENT_PENDING");
  const note=madeToOrder?`BharatShop Studio made-to-order fashion. Qikink product ${String(specs.qikinkProductCode||"")}; size ${String(selectedSize||"")}. Customer order accepted; automatic Qikink supplier submission requires a connected Qikink account/API plus approval.`:"";
  const[created]=await db.insert(storefrontOrders).values({orderRef:ref,customerName:String(customerName).trim(),customerEmail:String(customerEmail).trim(),customerPhone:String(customerPhone).trim(),customerAddress:String(customerAddress||"").trim(),customerCity:String(customerCity||"").trim(),customerState:String(customerState||"").trim(),customerPincode:String(customerPincode||"").trim(),productId:product.id,productTitle:product.title,productImageUrl:product.imageUrl,quantity:qty,sellingPriceInr:unitPrice.toFixed(2),totalAmountInr:total,paymentMode:normalizedPaymentMode,paymentStatus,fulfillmentStatus,source:"own_website",notes:note}).returning();
  const supplierTotal=(Number(product.supplierCostInr)+Number(product.shippingCostInr))*qty,gstAmount=Number(product.supplierCostInr)*Number(product.gstPct)/100*qty,commission=Number(total)*.08,netProfit=Number(total)-supplierTotal-gstAmount-commission;
  const[core]=await db.insert(orders).values({userId:product.userId,storeId:product.storeId,orderNumber:ref,customerName:created.customerName,customerEmail:created.customerEmail,customerPhone:created.customerPhone,customerAddress:created.customerAddress,customerCity:created.customerCity,customerState:created.customerState,customerPincode:created.customerPincode,productId:product.id,productTitle:product.title,quantity:qty,customerPaidInr:total,supplierCostInr:supplierTotal.toFixed(2),gstAmountInr:gstAmount.toFixed(2),platformCommissionInr:commission.toFixed(2),netProfitInr:netProfit.toFixed(2),fulfillmentStatus,supplierTrackingCode:null,carrierName:madeToOrder?"Qikink":null,paymentMode:normalizedPaymentMode,paymentStatus,aiDecisionLog:madeToOrder?`${note} No supplier order was placed automatically.`:`Storefront order ${ref} created. source=own_website; payment=${normalizedPaymentMode}; fulfillment gate=${fulfillmentStatus}; CEO authorization required before supplier purchase.`}).returning();
  await db.insert(aiActivityLogs).values({userId:product.userId,agentName:madeToOrder?"Qikink Fashion Order Gateway":"Website-Storefront // Order Gateway",actionType:madeToOrder?"QIKINK_FASHION_ORDER_QUEUED":"STOREFRONT_ORDER",message:madeToOrder?`New Qikink made-to-order request ${ref} for ${product.title}, size ${String(selectedSize||"")}, qty ${qty}. Awaiting supplier submission integration/approval.`:`New website order ${ref} — ${String(customerName).trim()} ordered ${product.title.slice(0,50)} × ${qty}. Total: ₹${total}. Gate: ${fulfillmentStatus}`,profitImpactInr:String(core.netProfitInr),metadataJson:madeToOrder?{productId:product.id,qikinkProductCode:specs.qikinkProductCode,selectedSize,qty,fulfillmentStatus}:undefined,status:"SUCCESS"});
  return NextResponse.json({order:created,fulfillmentOrder:core,ref,madeToOrder,productionSupplier:madeToOrder?"Qikink":product.supplierName,selectedSize:madeToOrder?String(selectedSize):undefined},{status:201});
 }catch(err:unknown){return NextResponse.json({error:err instanceof Error?err.message:"Order error"},{status:500});}
}

export async function PATCH(req:Request){try{const body=await req.json(),{id,fulfillmentStatus,trackingCode,carrierName}=body;if(!id)return NextResponse.json({error:"Order ID required"},{status:400});const allowedFulfillment=["RECHECK_REQUIRED","PURCHASE_PENDING","PAYMENT_PENDING","Received","AI Checking","Supplier Ordered","QIKINK_SUBMISSION_APPROVAL_REQUIRED","QIKINK_PRODUCTION_PENDING","QIKINK_ORDERED","In Transit","Delivered","Cancelled"];if(fulfillmentStatus&&!allowedFulfillment.includes(fulfillmentStatus))return NextResponse.json({error:"Invalid fulfillment status"},{status:400});const[updated]=await db.update(storefrontOrders).set({...(fulfillmentStatus&&{fulfillmentStatus}),...(trackingCode&&{trackingCode:String(trackingCode)}),...(carrierName&&{carrierName:String(carrierName)}),...(fulfillmentStatus==="Delivered"&&{fulfilledAt:new Date()})}).where(eq(storefrontOrders.id,Number(id))).returning();if(!updated)return NextResponse.json({error:"Order not found"},{status:404});await db.update(orders).set({...(fulfillmentStatus&&{fulfillmentStatus}),...(trackingCode&&{supplierTrackingCode:String(trackingCode)}),...(carrierName&&{carrierName:String(carrierName)}),...(fulfillmentStatus==="Delivered"&&{fulfilledAt:new Date()})}).where(eq(orders.orderNumber,updated.orderRef));return NextResponse.json({order:updated});}catch(err:unknown){return NextResponse.json({error:err instanceof Error?err.message:"Error"},{status:500});}}
export const dynamic="force-dynamic";
