import { serpSearch, openAIJson } from "@/lib/ai/agent-tools";
import { aiConfigured } from "@/lib/ai/provider";
import {NextResponse} from "next/server";
import {db} from "@/db"; import {products,productDetails} from "@/db/schema"; import {eq} from "drizzle-orm";
const FASHION=/(fashion|women|woman|men|man|saree|sari|kurti|kurta|dress|shirt|tshirt|t-shirt|jeans|trouser|lehenga|salwar|apparel|clothing|streetwear|hoodie|jogger|cargo|footwear|shoe|sandal)/i;
async function google(q:string){return serpSearch(q)}
async function extract(input:any){return openAIJson("Use ONLY supplied evidence. Never invent sizes, measurements, colours, materials or variants. Return JSON {availableSizes:string[],sizeChart:[{size:string,chestCm?:string,lengthCm?:string}],colors:string[],variants:string[],description:string,specifications:object}. Missing evidence must be empty arrays/strings.", input)}
export async function POST(req:Request){try{const token=req.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(!process.env.BHARATSHOP_AUTOMATION_TOKEN||token!==process.env.BHARATSHOP_AUTOMATION_TOKEN)return NextResponse.json({error:"Unauthorized"},{status:401});if(!process.env.SEARXNG_URL||!aiConfigured())return NextResponse.json({error:"SEARXNG_URL and AI_BASE_URL are required"},{status:503});const body=await req.json().catch(()=>({}));const limit=Math.max(1,Math.min(50,Number(body.limit||50)));const all=await db.select().from(products).where(eq(products.status,"Published"));const rows=all.filter(p=>FASHION.test(`${p.category} ${p.title}`)).slice(0,limit);let enriched=0;for(const p of rows){try{const d=await google(`${p.title} ${p.brand} official size chart available sizes colours`);const sources=(d.organic_results||[]).slice(0,8).map((x:any)=>({title:x.title,link:x.link,snippet:x.snippet}));if(!sources.length)continue;const out=await extract({product:{title:p.title,brand:p.brand,category:p.category},sources});const sizes=Array.isArray(out.availableSizes)?out.availableSizes.filter(Boolean):[];const chart=Array.isArray(out.sizeChart)?out.sizeChart.filter((x:any)=>x?.size):[];const colors=Array.isArray(out.colors)?out.colors.filter(Boolean):[];if(!sizes.length&&!chart.length&&!colors.length)continue;const existing=await db.select().from(productDetails).where(eq(productDetails.productId,p.id)).limit(1);const specs={...(out.specifications&&typeof out.specifications==="object"?out.specifications:{}),availableSizes:sizes,sizeChart:chart,verifiedSources:sources.map((s:any)=>s.link)};if(existing[0])await db.update(productDetails).set({description:String(out.description||existing[0].description||""),specificationsJson:specs,variantsJson:Array.isArray(out.variants)&&out.variants.length?out.variants:sizes,colorOptions:colors.join(", "),verificationStatus:"VERIFIED",verifiedAt:new Date(),updatedAt:new Date()}).where(eq(productDetails.productId,p.id));else await db.insert(productDetails).values({productId:p.id,description:String(out.description||""),specificationsJson:specs,variantsJson:sizes,colorOptions:colors.join(", "),verificationStatus:"VERIFIED",verifiedAt:new Date(),updatedAt:new Date()});enriched++}catch(e){console.error(`fashion ${p.id}:`,e instanceof Error?e.message:"failed")}}return NextResponse.json({status:"COMPLETED",processed:rows.length,enriched,rule:"Only evidence-backed sizes, size charts and colour variants are published."})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Fashion enrichment failed"},{status:500})}}
export const dynamic = "force-dynamic";
