import { NextResponse } from "next/server";
import { pool } from "@/db";

export const dynamic="force-dynamic";
const CEO_DELEGATED_ACTIONS=new Set(["DISCOVERY","SOURCE_VERIFY","LISTING_PUBLISH","IMAGE_RESOLVE","FASHION_ENRICH","FASHION_STUDIO","ORDER_RECHECK","TRACKING"]);
const BLOCKED_PAYLOAD_KEY=/(?:spend|budget|refund|payout|withdraw|credential|secret|password|token|delete|drop|truncate|reset|wipe|purchase|charge|debit|bank)/i;

async function ensureTable(){await pool.query(`CREATE TABLE IF NOT EXISTS ceo_approvals (id SERIAL PRIMARY KEY,title TEXT NOT NULL,action_type TEXT NOT NULL,payload JSONB NOT NULL DEFAULT '{}'::jsonb,reason TEXT NOT NULL DEFAULT '',risk_level TEXT NOT NULL DEFAULT 'MEDIUM',status TEXT NOT NULL DEFAULT 'PENDING',requested_by TEXT NOT NULL DEFAULT 'BHARATSHOP CEO',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),decided_at TIMESTAMPTZ,decision_note TEXT NOT NULL DEFAULT '')`);}
async function audit(agent:string,event:string,status:string,summary:string,evidence:any,approvalId:number){await pool.query(`CREATE TABLE IF NOT EXISTS agent_audit_records (id SERIAL PRIMARY KEY,agent_name TEXT NOT NULL,event_type TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'INFO',summary TEXT NOT NULL DEFAULT '',evidence JSONB NOT NULL DEFAULT '{}'::jsonb,approval_id INTEGER,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await pool.query(`INSERT INTO agent_audit_records(agent_name,event_type,status,summary,evidence,approval_id) VALUES($1,$2,$3,$4,$5,$6)`,[agent,event,status,summary,JSON.stringify(evidence||{}),approvalId]);}
function operatorAuthorized(req:Request){const expected=process.env.BHARATSHOP_OPERATOR_APPROVAL_TOKEN,supplied=req.headers.get("x-operator-approval-token")||"";return!!expected&&supplied===expected;}
function automationToken(){return process.env.BHARATSHOP_AUTOMATION_TOKEN||process.env.AUTOMATION_TOKEN||"";}
function automationAuthorized(req:Request){const expected=automationToken();if(!expected)return false;const supplied=req.headers.get("authorization")?.replace(/^Bearer\s+/i,"")||req.headers.get("x-automation-token")||"";return supplied===expected;}
function unsafePayload(value:unknown):boolean{if(Array.isArray(value))return value.some(unsafePayload);if(value&&typeof value==="object")return Object.entries(value as Record<string,unknown>).some(([k,v])=>BLOCKED_PAYLOAD_KEY.test(k)||unsafePayload(v));return false;}
function delegatedApprovalAllowed(approval:any){const action=String(approval?.action_type||"").toUpperCase(),risk=String(approval?.risk_level||"MEDIUM").toUpperCase(),requester=String(approval?.requested_by||"").toUpperCase();return CEO_DELEGATED_ACTIONS.has(action)&&["LOW","MEDIUM"].includes(risk)&&requester.includes("CEO")&&!unsafePayload(approval?.payload);}
function syntheticAcceptanceApproval(approval:any){return String(approval?.status||"").toUpperCase()==="PENDING"&&/^production acceptance\b/i.test(String(approval?.title||"").trim());}

export async function GET(){try{await ensureTable();const result=await pool.query(`SELECT id,title,action_type,payload,reason,risk_level,status,requested_by,created_at,decided_at,decision_note FROM ceo_approvals WHERE NOT (status='PENDING' AND title ILIKE 'Production acceptance%') ORDER BY created_at DESC LIMIT 50`);return NextResponse.json({approvals:result.rows,quarantine:{legacySyntheticAcceptance:true,destructiveCleanup:false},delegation:{enabled:true,allowedActions:[...CEO_DELEGATED_ACTIONS],humanOnly:["paid advertising/spend","supplier purchase/payment","refunds/payouts","credentials/secrets","destructive database actions"]}});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Approval queue unavailable"},{status:500});}}

export async function POST(req:Request){
 try{
  await ensureTable();const body=await req.json(),action=String(body.action||"");if(!["approve","reject"].includes(action))return NextResponse.json({error:"action must be approve or reject"},{status:400});const id=Number(body.id);if(!Number.isInteger(id))return NextResponse.json({error:"Valid approval id required"},{status:400});
  const before=await pool.query(`SELECT * FROM ceo_approvals WHERE id=$1 LIMIT 1`,[id]),candidate=before.rows[0];if(!candidate)return NextResponse.json({error:"Approval not found"},{status:404});if(syntheticAcceptanceApproval(candidate))return NextResponse.json({error:"Legacy synthetic production-acceptance approval is quarantined and cannot be executed",code:"SYNTHETIC_APPROVAL_QUARANTINED"},{status:409});
  const human=operatorAuthorized(req),ceoDelegated=action==="approve"&&automationAuthorized(req)&&delegatedApprovalAllowed(candidate);if(!human&&!ceoDelegated)return NextResponse.json({error:"This action requires human authorization or must qualify for bounded CEO delegation",delegationEligible:delegatedApprovalAllowed(candidate)},{status:403,headers:{"Cache-Control":"no-store"}});
  const actor=human?"human operator":"delegated CEO authority",note=String(body.note||(action==="approve"?`Approved by ${actor}`:`Rejected by ${actor}`));
  const result=await pool.query(`UPDATE ceo_approvals SET status=$1,decided_at=NOW(),decision_note=$2 WHERE id=$3 AND status='PENDING' RETURNING *`,[action==="approve"?"APPROVED":"REJECTED",note,id]),approval=result.rows[0];if(!approval)return NextResponse.json({error:"Approval not found or already decided"},{status:409});
  if(action==="reject"){await audit(String(approval.requested_by||"AI CEO"),"APPROVAL_REJECTED","REJECTED",`${actor} rejected ${approval.action_type}.`,{reason:approval.reason,decisionNote:note},id);return NextResponse.json({approval,execution:"BLOCKED"});}
  await audit(String(approval.requested_by||"AI CEO"),ceoDelegated?"CEO_DELEGATED_APPROVAL":"HUMAN_APPROVAL_GRANTED","SUCCESS",`${actor} approved ${approval.action_type}.`,{riskLevel:approval.risk_level,reason:approval.reason,delegated:ceoDelegated},id);
  const token=automationToken();if(!token){await pool.query(`UPDATE ceo_approvals SET status='EXECUTION_FAILED',decision_note=$2 WHERE id=$1`,[id,`${note}; automation token missing`]);return NextResponse.json({error:"Automation token is not configured",approval:{...approval,status:"EXECUTION_FAILED"},execution:"EXECUTION_FAILED"},{status:503});}
  const origin=new URL(req.url).origin,exec=await fetch(`${origin}/api/agent-execute`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,"x-automation-token":token},body:JSON.stringify({actionType:approval.action_type,payload:approval.payload,agentName:approval.requested_by,approvalId:id}),cache:"no-store",signal:AbortSignal.timeout(250000)}),raw=await exec.text();let execution:any;try{execution=JSON.parse(raw)}catch{execution={raw:raw.slice(0,4000)}}const succeeded=exec.ok&&execution?.status==="EXECUTED";
  await pool.query(`UPDATE ceo_approvals SET decision_note=CASE WHEN decision_note='' THEN $2 ELSE decision_note||'; '||$2 END WHERE id=$1`,[id,succeeded?`${note}; execution confirmed`:`${note}; execution failed or blocked`]);await audit(String(approval.requested_by||"AI CEO"),"APPROVAL_EXECUTION_RESULT",succeeded?"SUCCESS":"FAILED",succeeded?`Approved ${approval.action_type} executed.`:`Approved ${approval.action_type} failed; no success is claimed.`,{approval,execution,delegated:ceoDelegated},id);const final=await pool.query(`SELECT * FROM ceo_approvals WHERE id=$1 LIMIT 1`,[id]);return NextResponse.json({approval:final.rows[0]||{...approval,status:succeeded?"EXECUTED":"EXECUTION_FAILED"},execution:succeeded?"EXECUTED":"EXECUTION_FAILED",delegated:ceoDelegated,result:execution},{status:succeeded?200:422});
 }catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Approval update failed"},{status:500});}
}
