import { NextResponse } from "next/server";
import { db } from "@/db";
import { products, aiActivityLogs, marketingCampaigns } from "@/db/schema";
import { desc } from "drizzle-orm";
import { listProducts, health as cjHealth } from "@/lib/integrations/cj";
export const dynamic="force-dynamic";
const requiredEnv=["CJ_ACCESS_TOKEN"] as const;
export async function GET(){const cj=await cjHealth();const campaigns=await db.select().from(marketingCampaigns).orderBy(desc(marketingCampaigns.createdAt)).limit(10);const liveProducts=await db.select().from(products).orderBy(desc(products.updatedAt)).limit(10);const missing=requiredEnv.filter(k=>!process.env[k]);return NextResponse.json({status:cj.connected?"SOURCE_CONNECTED":"SOURCE_CONFIGURATION_REQUIRED",source:cj,liveProductCount:liveProducts.length,recentCampaigns:campaigns.length,requiredEnvironment:missing,workflow:{source:cj.connected,verify:cj.connected,calculate:cj.connected,select:cj.connected,listing:true,creative:true,advertise:campaigns.length>0,order:true,recheck:true,fulfill:cj.connected,track:cj.connected,learn:true}})}
export async function POST(req:Request){try{const body=await req.json().catch(()=>({}));const keyword=String(body.keyword||"");const userId=Number(body.userId||1);const minMarginPct=Number(body.minMarginPct||35);const fx=Number(body.usdInr||90);const candidates=await listProducts(keyword,1,Math.min(Number(body.size||20),100));const evaluated=candidates.map(p=>{const cost=p.priceUsd*fx;const shipping=Number(body.shippingInr||120);const gst=cost*.18;const selling=Math.ceil((cost+shipping+gst)/Math.max(.01,1-minMarginPct/100));const profit=selling-cost-shipping-gst;const marginPct=selling?profit/selling*100:0;return {...p,supplierCostInr:+cost.toFixed(2),shippingCostInr:shipping,gstPct:18,sellingPriceInr:selling,netProfitInr:+profit.toFixed(2),marginPct:+marginPct.toFixed(2),verified:p.stock>0&&!!p.imageUrl&&marginPct>=minMarginPct}}).sort((a,b)=>Number(b.verified)-Number(a.verified)||b.marginPct-a.marginPct);const qualified=evaluated.filter(p=>p.verified);const selected=qualified[0];await db.insert(aiActivityLogs).values({userId,agentName:"Live-Sourcing-Orchestrator",actionType:"SOURCE_DISCOVERY_COMPLETED",message:`Live source evaluated ${candidates.length} candidates; ${qualified.length} passed verification/economics.`,profitImpactInr:selected?.netProfitInr?.toFixed(2)||"0.00",metadataJson:{candidates:evaluated},status:selected?"SUCCESS":"WARNING"});if(selected){const metadata={selected,pricingBasis:"ACTUAL_CUSTOMER_CART_PRICE",verification:{stock:selected.stock,marginPct:selected.marginPct,imageUrl:selected.imageUrl}};await db.insert(aiActivityLogs).values({userId,agentName:"Live-Sourcing-Orchestrator",actionType:"SOURCE_VERIFIED_AND_SELECTED",message:`AI verified and selected ${selected.name} from live source evidence.`,profitImpactInr:selected.netProfitInr.toFixed(2),metadataJson:metadata,status:"SUCCESS"});await db.insert(aiActivityLogs).values({userId,agentName:"Live-Sourcing-Orchestrator",actionType:"SOURCE_SELECTED",message:`AI selected ${selected.name} after stock, cart economics and margin checks.`,profitImpactInr:selected.netProfitInr.toFixed(2),metadataJson:metadata,status:"SUCCESS"});}return NextResponse.json({pipeline:"Source → Verify → Calculate → Select",candidates:evaluated,selected:selected||null,status:selected?"READY_FOR_LISTING":"NO_QUALIFIED_PRODUCT"})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Live sourcing failed"},{status:503})}}
