import { NextResponse } from "next/server";
import { db } from "@/db";
import { aiActivityLogs } from "@/db/schema";
import { desc, eq } from "drizzle-orm";
import { openAIJson } from "@/lib/ai/agent-tools";
import { aiConfigured, aiProviderName } from "@/lib/ai/provider";
import { agentPrompt } from "@/lib/agents/contracts";
import { GOOGLE_INTELLIGENCE_POLICY, loadSharedAgentKnowledge } from "@/lib/agents/live-intelligence";
export const dynamic="force-dynamic";
export async function GET(req:Request){try{const {searchParams}=new URL(req.url);const userId=Number(searchParams.get("userId")??1);const logs=await db.select().from(aiActivityLogs).where(eq(aiActivityLogs.userId,userId)).orderBy(desc(aiActivityLogs.createdAt)).limit(200);const buckets:Record<string,{events:number;profitImpactInr:number}>={};for(const l of logs){const key=l.agentName||"unknown";buckets[key]??={events:0,profitImpactInr:0};buckets[key].events+=1;buckets[key].profitImpactInr+=Number(l.profitImpactInr||0);}let externalEvidence:any[]=[];let evidenceError="";try{externalEvidence=await loadSharedAgentKnowledge(20,"BharatShop India ecommerce fashion streetwear sourcing marketing conversion COD RTO advertising");}catch(e){evidenceError=e instanceof Error?e.message:String(e);}let analysis=null;let modelError="";if((logs.length||externalEvidence.length)&&aiConfigured()){try{analysis=await openAIJson(agentPrompt("learning"),{observations:buckets,recentOperations:logs.slice(0,50),externalMarketEvidence:externalEvidence,externalEvidencePolicy:GOOGLE_INTELLIGENCE_POLICY,learningObjective:"Separate BharatShop observed outcomes from external market context. Produce evidence-backed recommendations that can improve sourcing, assortment, creative, conversion, operations and advertising without weakening any hard gate."},{timeoutMs:10000,maxTokens:1200});}catch(e){modelError=e instanceof Error?e.message:String(e);}}return NextResponse.json({agent:"Learning-Agent",status:aiConfigured()?"ready":"blocked_missing_local_ai",provider:aiProviderName(),expertiseStandard:"doctoral-level evidence synthesis, statistics, operations research and ecommerce learning rigor",inputs:["source price changes","delivery time","cancellations","returns/RTO","profit","advertising performance","Google Trends India","Google News ecommerce/fashion market context"],observations:buckets,externalEvidencePolicy:GOOGLE_INTELLIGENCE_POLICY,externalEvidence,evidenceError:evidenceError||undefined,analysis,modelError:modelError||undefined,recent:logs.slice(0,30),promptVersion:"agent-suite-v3-google-evidence"});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Learning analysis failed"},{status:503})}}
