import React from "react";
import { AbsoluteFill, Img, interpolate, spring, useCurrentFrame, useVideoConfig } from "remotion";

export function ProductAd({
  title = "BharatShop",
  subtitle = "AI-picked product",
  cta = "Shop now",
  imageUrl = "",
  accent = "#f97316",
}) {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const intro = spring({ frame, fps, config: { damping: 16, stiffness: 120 } });
  const fade = interpolate(frame, [0, 12, 420, 449], [0, 1, 1, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const imageScale = interpolate(frame, [0, 450], [1.02, 1.12]);

  return (
    <AbsoluteFill style={{ background: "#070b12", color: "white", fontFamily: "Arial, Helvetica, sans-serif", opacity: fade }}>
      <AbsoluteFill style={{ background: `radial-gradient(circle at 85% 10%, ${accent}55, transparent 38%), linear-gradient(135deg, #05070b 0%, #111827 100%)` }} />
      {imageUrl ? (
        <div style={{ position: "absolute", right: 54, top: 54, width: 470, height: 972, borderRadius: 44, overflow: "hidden", boxShadow: "0 30px 80px rgba(0,0,0,.45)" }}>
          <Img src={imageUrl} style={{ width: "100%", height: "100%", objectFit: "cover", transform: `scale(${imageScale})` }} />
        </div>
      ) : null}
      <div style={{ position: "absolute", left: 64, top: 82, width: imageUrl ? 470 : 950, transform: `translateY(${(1 - intro) * 40}px)`, opacity: intro }}>
        <div style={{ display: "inline-flex", border: `1px solid ${accent}88`, background: `${accent}22`, color: accent, padding: "14px 20px", borderRadius: 999, fontSize: 24, fontWeight: 800, letterSpacing: 2 }}>BHARATSHOP AI CREATIVE</div>
        <h1 style={{ margin: "44px 0 18px", fontSize: imageUrl ? 78 : 102, lineHeight: .96, letterSpacing: -4, maxWidth: 900 }}>{title}</h1>
        <p style={{ margin: 0, fontSize: 34, lineHeight: 1.25, color: "#cbd5e1", maxWidth: 760 }}>{subtitle}</p>
      </div>
      <div style={{ position: "absolute", left: 64, bottom: 70, display: "flex", alignItems: "center", gap: 20 }}>
        <div style={{ background: accent, color: "#0b0f16", padding: "20px 34px", borderRadius: 18, fontWeight: 900, fontSize: 30 }}>{cta}</div>
        <div style={{ color: "#94a3b8", fontSize: 22 }}>Generated by BharatShop × Remotion</div>
      </div>
    </AbsoluteFill>
  );
}
