import { NextResponse } from "next/server";
import { db, pool } from "@/db";
import { orders, products, storefrontOrders, aiActivityLogs } from "@/db/schema";
import { and, desc, eq } from "drizzle-orm";
export const dynamic="force-dynamic";export const maxDuration=300;
function token(){return process.env.BHARATSHOP_AUTOMATION_TOKEN||process.env.AUTOMATION_TOKEN||"";}
function authorized(req:Request){const expected=token();if(!expected)return false;const supplied=req.headers.get("authorization")?.replace(/^Bearer\s+/i,"")||req.headers.get("x-automation-token")||"";return supplied===expected;}
async function jsonCall(origin:string,path:string,body:unknown){const t=token(),r=await fetch(`${origin}${path}`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`,"x-automation-token":t},body:JSON.stringify(body),cache:"no-store",signal:AbortSignal.timeout(180000)}),raw=await r.text();let data:any;try{data=JSON.parse(raw)}catch{data={raw:raw.slice(0,3000)}}return{ok:r.ok,status:r.status,data};}
async function ensureTables(){await pool.query(`CREATE TABLE IF NOT EXISTS ceo_approvals (id SERIAL PRIMARY KEY,title TEXT NOT NULL,action_type TEXT NOT NULL,payload JSONB NOT NULL DEFAULT '{}'::jsonb,reason TEXT NOT NULL DEFAULT '',risk_level TEXT NOT NULL DEFAULT 'MEDIUM',status TEXT NOT NULL DEFAULT 'PENDING',requested_by TEXT NOT NULL DEFAULT 'BHARATSHOP CEO',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),decided_at TIMESTAMPTZ,decision_note TEXT NOT NULL DEFAULT '')`);}
export async function POST(req:Request){if(!authorized(req))return NextResponse.json({error:"Unauthorized"},{status:401});try{await ensureTables();const origin=new URL(req.url).origin,delegatedApprovals:any[]=[],ordersHandled:any[]=[];
 const pending=await pool.query(`SELECT id,title,action_type,risk_level,requested_by FROM ceo_approvals WHERE status='PENDING' AND title NOT ILIKE 'Production acceptance%' ORDER BY created_at ASC LIMIT 20`);for(const approval of pending.rows){const outcome=await jsonCall(origin,"/api/ceo-approvals",{action:"approve",id:approval.id,note:"Approved by bounded CEO delegation during autonomous operations cycle."});if(outcome.ok||outcome.status!==403)delegatedApprovals.push({id:approval.id,actionType:approval.action_type,httpStatus:outcome.status,execution:outcome.data?.execution,delegated:outcome.data?.delegated===true});}
 const rows=await db.select({order:orders,product:products,storefront:storefrontOrders}).from(orders).leftJoin(products,eq(orders.productId,products.id)).leftJoin(storefrontOrders,eq(orders.orderNumber,storefrontOrders.orderRef)).where(and(eq(orders.paymentStatus,"TOKEN_PAID"),eq(orders.fulfillmentStatus,"CEO_ROUTING_READY"))).orderBy(desc(orders.orderedAt)).limit(10);
 for(const row of rows){const o=row.order,p=row.product,s=row.storefront;if(!p){ordersHandled.push({orderId:o.id,status:"BLOCKED_NO_PRODUCT"});continue;}if(String(p.supplierName).toLowerCase()==="qikink"){await db.update(orders).set({fulfillmentStatus:"PRODUCTION_REVIEW_REQUIRED",aiDecisionLog:`${o.aiDecisionLog}; ceo_authorized=true; route=made_to_order_production; autonomous_ceo_at=${new Date().toISOString()}`}).where(eq(orders.id,o.id));if(s)await db.update(storefrontOrders).set({fulfillmentStatus:"PRODUCTION_REVIEW_REQUIRED"}).where(eq(storefrontOrders.id,s.id));await db.insert(aiActivityLogs).values({userId:o.userId,agentName:"CEO Order Router",actionType:"CEO_PRODUCTION_ROUTE_AUTHORIZED",message:`${o.orderNumber}: verified token received; CEO routed made-to-order item to production review. No external supplier submission is falsely claimed.`,profitImpactInr:o.netProfitInr,metadataJson:{orderId:o.id,productId:p.id},status:"SUCCESS"});ordersHandled.push({orderId:o.id,status:"PRODUCTION_REVIEW_REQUIRED",ceoAuthorized:true});continue;}
  const recheck=await jsonCall(origin,"/api/agents/recheck",{orderId:o.id,minMarginPct:Number(process.env.CEO_MIN_MARGIN_PCT??25)});if(!recheck.ok||recheck.data?.passed!==true){ordersHandled.push({orderId:o.id,status:"RECHECK_HELD",httpStatus:recheck.status,reason:recheck.data?.error||recheck.data?.economics?.ai?.reason||"Live source evidence did not pass"});continue;}const authorize=await jsonCall(origin,"/api/orders/purchase-queue",{orderId:o.id,action:"authorize"});if(s&&authorize.ok)await db.update(storefrontOrders).set({fulfillmentStatus:"PURCHASE_PENDING"}).where(eq(storefrontOrders.id,s.id));ordersHandled.push({orderId:o.id,status:authorize.ok?"CEO_AUTHORIZED_PURCHASE_PENDING":"AUTHORIZATION_FAILED",recheckPassed:true,httpStatus:authorize.status});}
 return NextResponse.json({status:"COMPLETED",authority:"BOUNDED_CEO_DELEGATION",delegatedApprovals,ordersHandled,humanOnly:["external supplier purchase submission until supplier API is connected","paid ad spend","refunds/payouts","credential changes","destructive database operations"]});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"CEO delegation cycle failed"},{status:500});}}
export async function GET(req:Request){return POST(req);}
