"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, Bot, Check, ChevronRight, CircleAlert, FileSearch, Gauge, MessageSquare, Play, RefreshCw, ShieldCheck, Sparkles, Terminal, X, Zap } from "lucide-react";

type Agent = { id:string; name:string; icon:string; role:string; endpoint:string; capabilities:string[]; status:"ready"|"attention"|"unknown" };
type Message = { role:"user"|"assistant"; content:string };
type Approval = { id:number; title:string; action_type:string; reason:string; risk_level:string; status:string; created_at:string };

const AGENTS:Agent[] = [
 {id:"ceo",name:"AI CEO",icon:"👔",role:"Command, decisions, coordination & escalation",endpoint:"/api/ceo-chat",capabilities:["reasoning","web research","approvals","team coordination"],status:"ready"},
 {id:"discovery",name:"Product Research",icon:"🔎",role:"Find products, trends and supplier opportunities",endpoint:"/api/agents/discovery",capabilities:["live shopping search","source comparison","margin guard"],status:"ready"},
 {id:"verification",name:"Source Verification",icon:"🛡️",role:"Validate sources, economics and eligibility",endpoint:"/api/agents/source-verify",capabilities:["source evidence","economics gate","selection"],status:"ready"},
 {id:"images",name:"Image & Media",icon:"🖼️",role:"Recover and verify real product imagery",endpoint:"/api/catalog/image-resolve",capabilities:["image recovery","multi-angle gallery","media verification"],status:"ready"},
 {id:"fashion",name:"Fashion Enrichment",icon:"👗",role:"Clothing details, variants, sizing and media",endpoint:"/api/catalog/fashion-enrich",capabilities:["women's clothing","men's clothing","variants","size evidence"],status:"ready"},
 {id:"listing",name:"Listing & Marketing",icon:"📝",role:"Customer-facing product presentation",endpoint:"/api/agents/listing",capabilities:["listing copy","creative","positioning"],status:"ready"},
 {id:"learning",name:"Learning & Analytics",icon:"🧠",role:"Measure outcomes and turn evidence into lessons",endpoint:"/api/agents/learning",capabilities:["performance audit","lessons","risk detection"],status:"ready"},
 {id:"advertising",name:"Advertising",icon:"📣",role:"Campaign preparation and channel readiness",endpoint:"/api/agents/advertising",capabilities:["campaigns","channel status","performance"],status:"ready"},
 {id:"orders",name:"Order Re-check",icon:"🔄",role:"Re-check live supplier economics before fulfilment",endpoint:"/api/agents/recheck",capabilities:["price","stock","shipping","margin"],status:"ready"},
 {id:"tracking",name:"Fulfilment & Tracking",icon:"🚚",role:"Supplier purchase lifecycle and tracking",endpoint:"/api/agents/tracking",capabilities:["tracking","supplier lifecycle","delivery"],status:"ready"},
];

const card="rounded-2xl border border-slate-800 bg-slate-900/75";
const pill=(status:string)=>status==="ready"?"bg-emerald-500/10 text-emerald-300 border-emerald-500/20":status==="attention"?"bg-orange-500/10 text-orange-300 border-orange-500/20":"bg-slate-800 text-slate-400 border-slate-700";

export default function DashboardV2(){
 const [data,setData]=useState<any>(null); const [selected,setSelected]=useState("ceo"); const [messages,setMessages]=useState<Message[]>([{role:"assistant",content:"BharatShop AI Command Centre online. I can coordinate the team, inspect evidence, audit work and prepare actions. Select any agent to communicate with it."}]);
 const [question,setQuestion]=useState(""); const [busy,setBusy]=useState(false); const [auditing,setAuditing]=useState<string|null>(null); const [approvals,setApprovals]=useState<Approval[]>([]); const [notice,setNotice]=useState("");
 const load=useCallback(async()=>{const r=await fetch("/api/overview?limit=25",{cache:"no-store"}).catch(()=>null);const d=r&&r.ok?await r.json().catch(()=>null):null;setData(d);const a=await fetch("/api/ceo-approvals",{cache:"no-store"}).then(x=>x.json()).catch(()=>({}));setApprovals(Array.isArray(a.approvals)?a.approvals.filter((x:Approval)=>x.status==="PENDING"):[]);},[]);
 useEffect(()=>{void load();const t=setInterval(()=>void load(),30000);return()=>clearInterval(t)},[load]);
 const agent=useMemo(()=>AGENTS.find(a=>a.id===selected)||AGENTS[0],[selected]);
 const context=useMemo(()=>({kpis:data?.kpis,products:data?.products,orders:data?.orders?.slice?.(0,20),activityLogs:data?.activityLogs,refreshLogs:data?.refreshLogs,categoryDistribution:data?.categoryDistribution}),[data]);
 async function ask(text?:string){const q=(text??question).trim();if(!q||busy)return;const routed=agent.id==="ceo"?q:`Act as the ${agent.name} inside BharatShop. The operator is speaking directly to you. Focus only on your domain, inspect the supplied dashboard evidence, explain VERIFIED FACTS vs inference, and recommend or prepare safe actions. If another agent is needed, say exactly which agent and why. Operator request: ${q}`;const next=[...messages,{role:"user" as const,content:q}];setMessages(next);setQuestion("");setBusy(true);try{const r=await fetch("/api/ceo-chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:routed,messages:next,context:{...context,selectedAgent:agent.name,agentRole:agent.role}})});const d=await r.json();setMessages(v=>[...v,{role:"assistant",content:d.reply||d.error||"No response."}]);await load();}catch{setMessages(v=>[...v,{role:"assistant",content:"The AI service could not respond. No action was executed."}]);}finally{setBusy(false)}}
 async function audit(a:Agent){setAuditing(a.id);setSelected(a.id);setNotice(`Auditing ${a.name}…`);try{const q=`Run a detailed audit of your work. Inspect available BharatShop evidence and report: what you are responsible for; what you actually completed; successful vs failed work; products/orders affected; evidence quality; missing or suspicious data; business/profit impact; blockers; and exact fixes. Do not invent activity. If you cannot directly inspect a metric, say so.`;await ask(q);setNotice(`${a.name} audit completed in the AI conversation.`)}finally{setAuditing(null)}}
 async function decide(id:number,action:"approve"|"reject"){await fetch("/api/ceo-approvals",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,action})});await load()}
 async function refresh(){setNotice("Refreshing live command-centre data…");await load();setNotice("Live data refreshed.")}
 return <main className="min-h-screen bg-[#070b12] text-slate-100"><div className="max-w-[1600px] mx-auto p-4 md:p-7 space-y-5">
  <header className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><div className="text-orange-400 font-mono text-xs tracking-[.22em]">BHARATSHOP // COMMAND CENTRE V2</div><h1 className="text-3xl md:text-4xl font-black mt-1">AI Operations Command Centre</h1><p className="text-slate-400 mt-2 max-w-3xl">CEO → Agents → Tools → Evidence → Audit → Approval → Action → Result</p></div><div className="flex gap-2"><button onClick={()=>void refresh()} className="rounded-xl border border-slate-700 bg-slate-900 px-4 py-2.5 text-sm flex gap-2 items-center"><RefreshCw size={16}/> Refresh</button><a href="/" target="_blank" rel="noreferrer" className="rounded-xl bg-orange-500 text-slate-950 px-4 py-2.5 text-sm font-bold">Open Storefront</a></div></header>
  {notice&&<div className="rounded-xl border border-orange-500/20 bg-orange-500/5 px-4 py-3 text-sm text-orange-200">{notice}</div>}
  <section className="grid grid-cols-2 lg:grid-cols-6 gap-3">{[["Products",data?.kpis?.activeProductsCount??"—"],["Revenue","₹"+Number(data?.kpis?.totalRevenueInr||0).toLocaleString("en-IN")],["Net profit","₹"+Number(data?.kpis?.totalNetProfitInr||0).toLocaleString("en-IN")],["Margin",(data?.kpis?.avgMarginPct??"—")+"%"],["Orders",data?.orders?.length??"—"],["Pending approvals",approvals.length]].map(([k,v])=><div className={`${card} p-4`} key={String(k)}><div className="text-[11px] uppercase tracking-wider text-slate-500">{k}</div><div className="text-xl font-black mt-1">{v}</div></div>)}</section>
  <div className="grid xl:grid-cols-[330px_1fr_410px] gap-5 items-start">
   <aside className={`${card} overflow-hidden`}><div className="p-4 border-b border-slate-800 flex items-center justify-between"><div><h2 className="font-bold">AI Team</h2><p className="text-xs text-slate-500">Talk, inspect or audit any agent</p></div><Bot size={19} className="text-orange-400"/></div><div className="max-h-[760px] overflow-y-auto p-2">{AGENTS.map(a=><button key={a.id} onClick={()=>setSelected(a.id)} className={`w-full text-left rounded-xl p-3 mb-1 transition ${selected===a.id?"bg-orange-500/10 border border-orange-500/25":"hover:bg-slate-800/70 border border-transparent"}`}><div className="flex items-start gap-3"><span className="text-xl">{a.icon}</span><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><span className="font-semibold text-sm">{a.name}</span><span className={`text-[9px] border rounded-full px-1.5 py-0.5 ${pill(a.status)}`}>{a.status.toUpperCase()}</span></div><p className="text-[11px] text-slate-500 mt-1 leading-4">{a.role}</p></div></div></button>)}</div></aside>
   <section className={`${card} min-h-[760px] flex flex-col overflow-hidden`}><div className="p-5 border-b border-slate-800 flex items-center gap-3"><div className="h-11 w-11 rounded-xl bg-orange-500/10 border border-orange-500/20 flex items-center justify-center text-2xl">{agent.icon}</div><div className="flex-1"><div className="flex items-center gap-2"><h2 className="font-bold text-lg">{agent.name}</h2><span className={`text-[9px] border rounded-full px-2 py-0.5 ${pill(agent.status)}`}>{agent.status}</span></div><p className="text-xs text-slate-500">{agent.role}</p></div><button onClick={()=>void audit(agent)} disabled={!!auditing} className="rounded-lg border border-slate-700 px-3 py-2 text-xs font-semibold flex items-center gap-2"><FileSearch size={14}/>{auditing===agent.id?"Auditing…":"Run audit"}</button></div><div className="flex-1 overflow-y-auto p-4 space-y-3">{messages.map((m,i)=><div key={i} className={`max-w-[90%] rounded-2xl p-3.5 text-sm whitespace-pre-wrap ${m.role==="assistant"?"bg-slate-950 border border-slate-800 mr-auto":"bg-orange-500 text-slate-950 ml-auto"}`}>{m.content}</div>)}{busy&&<div className="bg-slate-950 border border-slate-800 rounded-2xl p-3.5 text-sm text-slate-400">{agent.name} is reasoning over the available evidence…</div>}</div><div className="p-4 border-t border-slate-800"><div className="flex flex-wrap gap-2 mb-3">{["Give me a status update","Audit your recent work","What is blocking you?","What should you do next?"] .map(x=><button key={x} onClick={()=>void ask(x)} className="text-[11px] rounded-full border border-slate-700 px-3 py-1.5 text-slate-400 hover:text-white">{x}</button>)}</div><div className="flex gap-2"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void ask()}} placeholder={`Talk directly to ${agent.name}…`} className="flex-1 rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-sm outline-none focus:border-orange-500"/><button onClick={()=>void ask()} disabled={!question.trim()||busy} className="rounded-xl bg-orange-500 text-slate-950 px-4 disabled:opacity-40"><MessageSquare size={18}/></button></div></div></section>
   <aside className="space-y-5"><section className={`${card} overflow-hidden`}><div className="p-4 border-b border-slate-800 flex items-center gap-2"><ShieldCheck size={18} className="text-emerald-400"/><div><h2 className="font-bold">Approval Desk</h2><p className="text-xs text-slate-500">Human gate for consequential actions</p></div></div><div className="p-3 space-y-2">{approvals.length===0?<div className="p-5 text-center text-sm text-slate-500">No pending approvals.</div>:approvals.map(a=><div key={a.id} className="rounded-xl bg-slate-950 border border-slate-800 p-3"><div className="font-semibold text-sm">{a.title}</div><div className="text-[11px] text-slate-500 mt-1">{a.reason}</div><div className="flex justify-between items-center mt-3"><span className="text-[9px] uppercase text-orange-300">{a.risk_level} · {a.action_type}</span><div className="flex gap-1"><button onClick={()=>void decide(a.id,"reject")} className="rounded-lg border border-slate-700 p-2"><X size={13}/></button><button onClick={()=>void decide(a.id,"approve")} className="rounded-lg bg-emerald-500 text-slate-950 p-2"><Check size={13}/></button></div></div></div>)}</div></section>
    <section className={`${card} p-4`}><div className="flex items-center gap-2 mb-3"><Activity size={17} className="text-orange-400"/><h2 className="font-bold">Live Evidence Feed</h2></div><div className="space-y-2 max-h-80 overflow-y-auto">{(data?.activityLogs||[]).slice(0,12).map((l:any,i:number)=><div key={i} className="rounded-lg bg-slate-950/80 p-2.5 border border-slate-800"><div className="flex justify-between gap-2 text-[10px]"><span className="font-semibold text-slate-300">{l.agentName||"AI Agent"}</span><span className={l.status==="SUCCESS"?"text-emerald-400":"text-orange-300"}>{l.status||"LOG"}</span></div><div className="text-[11px] text-slate-500 mt-1">{l.message||l.actionType}</div></div>)}{!(data?.activityLogs||[]).length&&<div className="text-xs text-slate-500">No recent activity evidence returned.</div>}</div></section>
    <section className={`${card} p-4`}><h2 className="font-bold mb-3">System Controls</h2><div className="grid grid-cols-2 gap-2"><button onClick={()=>void ask("Review the entire dashboard and identify the three highest-priority problems. Do not change anything yet.")} className="rounded-xl border border-slate-700 p-3 text-left text-xs"><CircleAlert size={15} className="mb-2 text-orange-400"/>Find problems</button><button onClick={()=>void ask("Review current catalogue quality, especially products with missing or weak imagery, and tell me exactly what the image and fashion agents should fix first.")} className="rounded-xl border border-slate-700 p-3 text-left text-xs"><Sparkles size={15} className="mb-2 text-orange-400"/>Catalogue audit</button><button onClick={()=>void ask("Find current high-margin product opportunities worth researching next, including premium watches, and create an approval request only if a consequential action is required.")} className="rounded-xl border border-slate-700 p-3 text-left text-xs"><Zap size={15} className="mb-2 text-orange-400"/>Find opportunities</button><button onClick={()=>void ask("Give me a CEO-level report of what every agent is doing, what is blocked, and what should happen next.")} className="rounded-xl border border-slate-700 p-3 text-left text-xs"><Gauge size={15} className="mb-2 text-orange-400"/>CEO report</button></div></section></aside>
  </div>
  <section className={`${card} p-4`}><div className="flex items-center gap-2 mb-3"><Terminal size={17} className="text-orange-400"/><h2 className="font-bold">Tool & Evidence Map</h2></div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-2">{AGENTS.map(a=><div key={a.id} className="rounded-xl bg-slate-950 border border-slate-800 p-3"><div className="flex justify-between"><span className="text-sm font-semibold">{a.icon} {a.name}</span><span className="text-emerald-400 text-[9px]">SERVER TOOL</span></div><div className="text-[10px] text-slate-500 mt-2">{a.endpoint}</div><div className="flex flex-wrap gap-1 mt-2">{a.capabilities.map(c=><span key={c} className="rounded bg-slate-900 px-1.5 py-1 text-[9px] text-slate-400">{c}</span>)}</div></div>)}</div></section>
 </div></main>
}
