"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, Bot, Check, CircleAlert, FileSearch, Gauge, MessageSquare, RefreshCw, ShieldCheck, Sparkles, Terminal, X, Zap } from "lucide-react";

type Agent={id:string;name:string;icon:string;role:string;capabilities:string[]};
type Message={role:"user"|"assistant";content:string};
type Approval={id:number;title:string;action_type:string;reason:string;risk_level:string;status:string;created_at:string};
type AuditState={records:any[];recentActivity:any[];blockers:any[]};

const AGENTS:Agent[]=[
{id:"ceo",name:"AI CEO",icon:"👔",role:"Business command, problem solving, priorities and coordination",capabilities:["live status","root-cause analysis","approvals","team coordination"]},
{id:"discovery",name:"Product Research",icon:"🔎",role:"Find and compare real product opportunities",capabilities:["supplier research","trend evidence","margin guard"]},
{id:"verification",name:"Source Verification",icon:"🛡️",role:"Validate sources, pricing, availability and economics",capabilities:["source evidence","economics gate","selection"]},
{id:"images",name:"Image & Media",icon:"🖼️",role:"Build verified product galleries",capabilities:["image recovery","multi-angle gallery","media verification"]},
{id:"fashion",name:"Fashion Designer",icon:"👗",role:"Create original men, women and kids fashion for Qikink production",capabilities:["original design","Qikink mapping","sizes","made-to-order"]},
{id:"listing",name:"Listing & Marketing",icon:"📝",role:"Turn verified facts into customer-ready listings",capabilities:["listing copy","positioning","publication"]},
{id:"learning",name:"Learning & Analytics",icon:"🧠",role:"Measure outcomes and identify weak points",capabilities:["performance audit","lessons","risk detection"]},
{id:"advertising",name:"Advertising",icon:"📣",role:"Prepare campaigns without spending until approved",capabilities:["campaign plans","channel readiness","performance"]},
{id:"orders",name:"Order Re-check",icon:"🔄",role:"Re-check supplier economics before fulfilment",capabilities:["price","stock","shipping","margin"]},
{id:"tracking",name:"Fulfilment & Tracking",icon:"🚚",role:"Coordinate supplier production and tracking",capabilities:["Qikink production","tracking","delivery"]},
];

const card="rounded-2xl border border-slate-800 bg-slate-900/75";
const welcome=(a:Agent):Message=>({role:"assistant",content:a.id==="ceo"?"I’m running BharatShop from the live business data. Ask me what is working, what is broken, what I should fix next, or tell me the outcome you want.":`I’m handling ${a.name}. Ask me what is happening in this area and I’ll explain the real status, the problem, and the next action.`});

export default function DashboardV2(){
  const[data,setData]=useState<any>(null),[selected,setSelected]=useState("ceo"),[conversations,setConversations]=useState<Record<string,Message[]>>({ceo:[welcome(AGENTS[0])]}),[question,setQuestion]=useState(""),[busy,setBusy]=useState(false),[auditing,setAuditing]=useState<string|null>(null),[approvals,setApprovals]=useState<Approval[]>([]),[audit,setAudit]=useState<AuditState>({records:[],recentActivity:[],blockers:[]}),[notice,setNotice]=useState("");

  const load=useCallback(async()=>{
    const r=await fetch("/api/overview?limit=40",{cache:"no-store"}).catch(()=>null);const d=r&&r.ok?await r.json().catch(()=>null):null;setData(d);
    const a=await fetch("/api/ceo-approvals",{cache:"no-store"}).then(x=>x.json()).catch(()=>({}));setApprovals(Array.isArray(a.approvals)?a.approvals.filter((x:Approval)=>x.status==="PENDING"):[]);
  },[]);
  const loadAudit=useCallback(async(a:Agent)=>{const r=await fetch(`/api/agent-audit?agent=${encodeURIComponent(a.name)}`,{cache:"no-store"}).catch(()=>null);const d=r&&r.ok?await r.json().catch(()=>null):null;setAudit({records:d?.records||[],recentActivity:d?.recentActivity||[],blockers:d?.blockers||[]});},[]);
  useEffect(()=>{void load();const t=setInterval(()=>void load(),30000);return()=>clearInterval(t)},[load]);
  useEffect(()=>{const a=AGENTS.find(x=>x.id===selected)||AGENTS[0];void loadAudit(a)},[selected,loadAudit]);

  const agent=useMemo(()=>AGENTS.find(a=>a.id===selected)||AGENTS[0],[selected]);
  const messages=conversations[selected]||[welcome(agent)];
  const k=data?.kpis||{};
  const context=useMemo(()=>({kpis:data?.kpis,products:data?.products,orders:data?.orders?.slice?.(0,20),activityLogs:data?.activityLogs,refreshLogs:data?.refreshLogs,categoryDistribution:data?.categoryDistribution,truthPolicy:data?.truthPolicy}),[data]);

  function selectAgent(id:string){setSelected(id);setQuestion("");if(!conversations[id]){const a=AGENTS.find(x=>x.id===id)||AGENTS[0];setConversations(v=>({...v,[id]:[welcome(a)]}))}}
  async function ask(text?:string){
    const q=(text??question).trim();if(!q||busy)return;
    const current=conversations[selected]||[welcome(agent)],next=[...current,{role:"user" as const,content:q}];setConversations(v=>({...v,[selected]:next}));setQuestion("");setBusy(true);
    try{const r=await fetch("/api/ceo-chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:q,messages:next,context:{...context,selectedAgent:agent.name,agentRole:agent.role}})});const d=await r.json();setConversations(v=>({...v,[selected]:[...next,{role:"assistant",content:d.reply||d.error||"I couldn’t complete that request."}]}));await Promise.all([load(),loadAudit(agent)])}
    catch{setConversations(v=>({...v,[selected]:[...next,{role:"assistant",content:"I couldn’t reach the live service. I have not changed anything. Try again and I’ll continue from the current state."}]}))}
    finally{setBusy(false)}
  }
  async function auditAgent(a:Agent){
    setAuditing(a.id);setSelected(a.id);setNotice(`Auditing ${a.name} against live evidence…`);setBusy(true);
    try{const q="Audit this area like a senior operator. Tell me what is actually working, what is broken, the business impact, and exactly what should happen next. Keep raw tool telemetry out of the answer.";const current=conversations[a.id]||[welcome(a)],next=[...current,{role:"user" as const,content:q}];setConversations(v=>({...v,[a.id]:next}));const r=await fetch("/api/ceo-chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:q,messages:next,context:{...context,selectedAgent:a.name,agentRole:a.role}})});const d=await r.json();setConversations(v=>({...v,[a.id]:[...next,{role:"assistant",content:d.reply||d.error||"Audit unavailable."}]}));await Promise.all([load(),loadAudit(a)]);setNotice(`${a.name} audit completed.`)}finally{setBusy(false);setAuditing(null)}
  }
  async function decide(id:number,action:"approve"|"reject"){const r=await fetch("/api/ceo-approvals",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,action})});const d=await r.json().catch(()=>({}));setNotice(action==="approve"?(d.execution==="EXECUTED"?"Approved and executed.":d.error||"Approval recorded."):"Approval rejected.");await Promise.all([load(),loadAudit(agent)])}
  async function refresh(){setNotice("Refreshing live business data…");await Promise.all([load(),loadAudit(agent)]);setNotice("Live data refreshed.")}

  const cards=[
    ["Published live",k.publishedProductsCount??k.activeProductsCount??"—","Customer-visible products"],
    ["Total records",k.totalProductRecordsCount??"—","All database product records"],
    ["In pipeline",k.inPipelineProductsCount??"—","Draft, staged or under review"],
    ["Qikink fashion",k.fashionMadeToOrderCount??"—","Made-to-order Studio products"],
    ["Orders",data?.orders?.length??"—","Internal order records"],
    ["Approvals",approvals.length,"Human decisions waiting"],
  ];

  return <main className="min-h-screen bg-[#070b12] text-slate-100"><div className="max-w-[1600px] mx-auto p-4 md:p-7 space-y-5">
    <header className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><div className="text-orange-400 font-mono text-xs tracking-[.22em]">BHARATSHOP // LIVE COMMAND CENTRE</div><h1 className="text-3xl md:text-4xl font-black mt-1">AI Operations Command Centre</h1><p className="text-slate-400 mt-2 max-w-3xl">Live business truth first: published store, pipeline, orders, approvals and agent actions are shown separately.</p></div><div className="flex gap-2"><button onClick={()=>void refresh()} className="rounded-xl border border-slate-700 bg-slate-900 px-4 py-2.5 text-sm flex gap-2 items-center"><RefreshCw size={16}/> Refresh</button><a href="/" target="_blank" rel="noreferrer" className="rounded-xl bg-orange-500 text-slate-950 px-4 py-2.5 text-sm font-bold">Open Storefront</a></div></header>
    {notice&&<div className="rounded-xl border border-orange-500/20 bg-orange-500/5 px-4 py-3 text-sm text-orange-200">{notice}</div>}
    <section className="grid grid-cols-2 lg:grid-cols-6 gap-3">{cards.map(([label,value,sub])=><div className={`${card} p-4`} key={String(label)}><div className="text-[11px] uppercase tracking-wider text-slate-500">{label}</div><div className="text-2xl font-black mt-1">{value}</div><div className="text-[10px] text-slate-600 mt-1">{sub}</div></div>)}</section>
    <div className="grid xl:grid-cols-[320px_1fr_400px] gap-5 items-start">
      <aside className={`${card} overflow-hidden`}><div className="p-4 border-b border-slate-800 flex items-center justify-between"><div><h2 className="font-bold">AI Team</h2><p className="text-xs text-slate-500">Choose the specialist you want</p></div><Bot size={19} className="text-orange-400"/></div><div className="max-h-[760px] overflow-y-auto p-2">{AGENTS.map(a=><button key={a.id} onClick={()=>selectAgent(a.id)} className={`w-full text-left rounded-xl p-3 mb-1 border transition ${selected===a.id?"bg-orange-500/10 border-orange-500/25":"hover:bg-slate-800/70 border-transparent"}`}><div className="flex gap-3"><span className="text-xl">{a.icon}</span><div><span className="font-semibold text-sm">{a.name}</span><p className="text-[11px] text-slate-500 mt-1 leading-4">{a.role}</p></div></div></button>)}</div></aside>
      <section className={`${card} min-h-[760px] flex flex-col overflow-hidden`}><div className="p-5 border-b border-slate-800 flex items-center gap-3"><div className="h-11 w-11 rounded-xl bg-orange-500/10 border border-orange-500/20 flex items-center justify-center text-2xl">{agent.icon}</div><div className="flex-1"><h2 className="font-bold text-lg">{agent.name}</h2><p className="text-xs text-slate-500">{agent.role}</p></div><button onClick={()=>void auditAgent(agent)} disabled={busy||!!auditing} className="rounded-lg border border-slate-700 px-3 py-2 text-xs font-semibold flex items-center gap-2"><FileSearch size={14}/>{auditing===agent.id?"Auditing…":"Audit"}</button></div><div className="flex-1 overflow-y-auto p-4 space-y-3">{messages.map((m,i)=><div key={i} className={`max-w-[92%] rounded-2xl p-4 text-sm leading-6 whitespace-pre-wrap ${m.role==="assistant"?"bg-slate-950 border border-slate-800 mr-auto":"bg-orange-500 text-slate-950 ml-auto"}`}>{m.content}</div>)}{busy&&<div className="bg-slate-950 border border-slate-800 rounded-2xl p-4 text-sm text-slate-400">Working through the live data…</div>}</div><div className="p-4 border-t border-slate-800"><div className="flex flex-wrap gap-2 mb-3">{["What's actually live right now?","What is broken and why?","How many products are truly published?","What should you fix next?"].map(x=><button key={x} onClick={()=>void ask(x)} className="text-[11px] rounded-full border border-slate-700 px-3 py-1.5 text-slate-400 hover:text-white">{x}</button>)}</div><div className="flex gap-2"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void ask()}} placeholder={`Message ${agent.name}…`} className="flex-1 rounded-xl bg-slate-950 border border-slate-700 px-4 py-3 text-sm outline-none focus:border-orange-500"/><button onClick={()=>void ask()} disabled={!question.trim()||busy} className="rounded-xl bg-orange-500 text-slate-950 px-4 disabled:opacity-40"><MessageSquare size={18}/></button></div></div></section>
      <aside className="space-y-5">
        <section className={`${card} p-4`}><div className="flex items-center gap-2 mb-3"><Gauge size={17} className="text-orange-400"/><h2 className="font-bold">Catalog truth</h2></div><div className="space-y-2 text-sm">{[["Published live",k.publishedProductsCount],["Source verified",k.sourceVerifiedProductsCount],["CEO pending",k.ceoPendingProductsCount],["Staged / draft",k.stagedProductsCount],["Rejected / blocked",k.rejectedProductsCount],["Qikink fashion",k.fashionMadeToOrderCount]].map(([a,b])=><div key={String(a)} className="flex justify-between rounded-lg bg-slate-950 px-3 py-2"><span className="text-slate-400">{a}</span><b>{b??0}</b></div>)}</div><p className="text-[10px] text-slate-600 mt-3">Total records are never presented as live storefront products.</p></section>
        <section className={`${card} overflow-hidden`}><div className="p-4 border-b border-slate-800 flex items-center gap-2"><ShieldCheck size={18} className="text-emerald-400"/><div><h2 className="font-bold">Approval Desk</h2><p className="text-xs text-slate-500">Human gate for consequential actions</p></div></div><div className="p-3 space-y-2">{approvals.length===0?<div className="p-5 text-center text-sm text-slate-500">No pending approvals.</div>:approvals.map(a=><div key={a.id} className="rounded-xl bg-slate-950 border border-slate-800 p-3"><div className="font-semibold text-sm">{a.title}</div><div className="text-[11px] text-slate-500 mt-1">{a.reason}</div><div className="flex justify-between items-center mt-3"><span className="text-[9px] uppercase text-orange-300">{a.risk_level} · {a.action_type}</span><div className="flex gap-1"><button onClick={()=>void decide(a.id,"reject")} className="rounded-lg border border-slate-700 p-2"><X size={13}/></button><button onClick={()=>void decide(a.id,"approve")} className="rounded-lg bg-emerald-500 text-slate-950 p-2"><Check size={13}/></button></div></div></div>)}</div></section>
        <section className={`${card} p-4`}><div className="flex items-center gap-2 mb-3"><Activity size={17} className="text-orange-400"/><h2 className="font-bold">Recent evidence</h2></div><div className="space-y-2 max-h-72 overflow-y-auto">{(audit.recentActivity||[]).slice(0,10).map((l:any,i:number)=><div key={i} className="rounded-lg bg-slate-950/80 p-2.5 border border-slate-800"><div className="flex justify-between gap-2 text-[10px]"><span className="font-semibold text-slate-300">{l.agent_name||"AI Agent"}</span><span className={l.status==="SUCCESS"?"text-emerald-400":"text-orange-300"}>{l.status||"LOG"}</span></div><div className="text-[11px] text-slate-500 mt-1">{l.message||l.action_type}</div></div>)}{!(audit.recentActivity||[]).length&&<div className="text-xs text-slate-500">No evidence returned for this agent.</div>}</div></section>
      </aside>
    </div>
    <section className={`${card} p-4`}><div className="flex items-center gap-2 mb-3"><Terminal size={17} className="text-orange-400"/><h2 className="font-bold">Operational controls</h2></div><div className="grid md:grid-cols-4 gap-2"><button onClick={()=>void ask("Find the three biggest operational problems in BharatShop right now. Explain the business impact and the exact fix for each.")} className="rounded-xl border border-slate-700 p-3 text-left text-xs"><CircleAlert size={15} className="mb-2 text-orange-400"/>Find problems</button><button onClick={()=>void ask("Audit the live catalog. Separate published products from database records and tell me how to safely expand the storefront.")} className="rounded-xl border border-slate-700 p-3 text-left text-xs"><Sparkles size={15} className="mb-2 text-orange-400"/>Catalog audit</button><button onClick={()=>void ask("Review the Qikink fashion pipeline for men, women and kids. Tell me what is publishable and what still needs production integration.")} className="rounded-xl border border-slate-700 p-3 text-left text-xs"><Zap size={15} className="mb-2 text-orange-400"/>Fashion review</button><button onClick={()=>void ask("Give me a CEO-level plan for the next highest-value actions across products, orders, fashion and automation.")} className="rounded-xl border border-slate-700 p-3 text-left text-xs"><Gauge size={15} className="mb-2 text-orange-400"/>CEO plan</button></div></section>
  </div></main>
}
