"use client";
import { useCallback, useEffect, useState } from "react";

type Stage={key:string;title:string;icon:string;status:string;detail:string};
const tone=(s:string)=>s==="PASSED"||s==="OBSERVED"||s==="CONNECTED"||s==="PREPARED"?"border-emerald-500/30 bg-emerald-500/10 text-emerald-300":s==="FAILED"||s==="BLOCKED"?"border-red-500/30 bg-red-500/10 text-red-300":"border-slate-700 bg-slate-900 text-slate-300";
const money=(n:number)=>`₹${Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;

export default function OperationalDashboard(){
 const [data,setData]=useState<any>({orders:[],queue:[],tracking:[],learning:{recent:[]},ads:{channels:[]},milestone:{checks:{}}});
 const [busy,setBusy]=useState(false);
 const [msg,setMsg]=useState("");
 const load=useCallback(async()=>{try{const urls=["/api/milestone","/api/orders/purchase-queue","/api/agents/tracking","/api/agents/learning","/api/agents/advertising-status","/api/orders"];const rs=await Promise.all(urls.map(u=>fetch(u)));const js=await Promise.all(rs.map(async r=>{try{return await r.json()}catch{return {}}}));setData({milestone:js[0],queue:Array.isArray(js[1]?.queue)?js[1].queue:[],tracking:Array.isArray(js[2]?.orders)?js[2].orders:[],learning:js[3]||{recent:[]},ads:js[4]||{channels:[]},orders:Array.isArray(js[5]?.orders)?js[5].orders:[]})}catch{setMsg("Dashboard data unavailable; safe empty state shown.")}},[]);
 useEffect(()=>{load()},[load]);
 async function recheck(id:number){setBusy(true);setMsg("AI re-checking supplier price, stock, shipping and margin…");try{const r=await fetch("/api/agents/recheck",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId:id})});const d=await r.json().catch(()=>({}));setMsg(d.passed?"✓ Re-check passed.":"⚠ Re-check blocked.")}catch{setMsg("⚠ Re-check failed.")}finally{setBusy(false);load()}}
 async function purchase(x:any){const supplier=window.prompt(`Enter actual supplier order number for ${x.orderNumber}`);if(!supplier)return;const tracking=window.prompt("Enter actual supplier tracking number (optional)")||"";setBusy(true);try{const r=await fetch("/api/orders/purchase-queue",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId:x.orderId,action:"purchased",supplierOrderNumber:supplier,trackingCode:tracking})});const d=await r.json().catch(()=>({}));setMsg(d.error||"✓ Supplier purchase recorded.")}catch{setMsg("⚠ Purchase recording failed.")}finally{setBusy(false);load()}}
 async function test(){setBusy(true);setMsg("Running order pipeline…");try{const r=await fetch("/api/automation/order-pipeline",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:1})});const d=await r.json().catch(()=>({}));setMsg(d.error?`⚠ ${d.error}`:`✓ Processed ${d.processed||0} order(s).`)}catch{setMsg("⚠ Pipeline failed.")}finally{setBusy(false);load()}}
 const c=data.milestone?.checks||{};
 const stages:Stage[]=[
  {key:"source",title:"AI product discovery",icon:"🤖",status:c.source?.status||"NOT_OBSERVED",detail:c.source?.message||"Verified source-selection evidence."},
  {key:"verify",title:"Source verification",icon:"🔎",status:c.verify?.status||"NOT_OBSERVED",detail:c.verify?.message||"Stock, price and eligibility evidence."},
  {key:"calculate",title:"Cart price + margin",icon:"💰",status:c.calculate?.status||"NOT_OBSERVED",detail:c.calculate?.message||"Current customer/cart economics."},
  {key:"select",title:"AI source selection",icon:"🎯",status:c.select?.status||"NOT_OBSERVED",detail:c.select?.message||"AI selects the eligible source."},
  {key:"listingCreative",title:"Listing / creative generation",icon:"📝",status:c.listingCreative?.status||"NOT_OBSERVED",detail:c.listingCreative?.message||"Listing and marketing creative evidence."},
  {key:"advertise",title:"Advertising preparation",icon:"📣",status:c.advertise?.status||"NOT_OBSERVED",detail:c.advertise?.message||"Prepared; live ads require a connected account."},
  {key:"customerOrder",title:"Customer order received",icon:"🛒",status:c.customerOrder?.status||"NOT_OBSERVED",detail:c.customerOrder?.message||"A real customer order enters the loop."},
  {key:"recheckFulfillTrack",title:"Order-time re-check",icon:"🔄",status:c.recheckFulfillTrack?.status||"NOT_OBSERVED",detail:c.recheckFulfillTrack?.message||"Re-check → purchase → supplier tracking."}
 ];
 const queue=Array.isArray(data.queue)?data.queue:[];
 const pending=queue.filter((x:any)=>!String(x.fulfillmentStatus||"").startsWith("PURCHASED"));
 const tracking=Array.isArray(data.tracking)?data.tracking:[];
 const orders=Array.isArray(data.orders)?data.orders:[];
 const channels=Array.isArray(data.ads?.channels)?data.ads.channels:[];
 return <main className="min-h-screen bg-slate-950 text-slate-100 p-4 md:p-8"><div className="max-w-7xl mx-auto space-y-6">
  <header className="flex flex-col md:flex-row md:justify-between gap-4"><div><div className="text-orange-400 font-mono text-xs tracking-widest">BHARATSHOP // AI OPERATIONS</div><h1 className="text-3xl font-bold mt-1">Autonomous Product-to-Fulfilment Loop</h1><p className="text-slate-400 text-sm mt-1">AI selects products and sources. You only execute the real supplier purchase when an order is ready.</p></div><div className={`rounded-xl border px-5 py-4 ${mTone(data.milestone?.milestone)}`}><div className="text-xs opacity-70">MILESTONE</div><div className="font-bold mt-1">{data.milestone?.displayStatus||"🟡 NOT READY"}</div></div></header>
  {msg&&<div className="rounded-lg border border-slate-800 bg-slate-900 p-3 text-sm">{msg}</div>}
  <section className="grid grid-cols-2 md:grid-cols-5 gap-3">{[["Customer orders",orders.length],["AI purchase queue",pending.length],["Supplier tracked",tracking.length],["Learning events",data.learning?.recent?.length||0],["Connected ad channels",channels.filter((x:any)=>Boolean(x?.connected)).length]].map(([a,b])=><div key={String(a)} className="rounded-xl border border-slate-800 bg-slate-900/70 p-4"><div className="text-xs text-slate-500">{a}</div><div className="text-xl font-bold mt-1">{b}</div></div>)}</section>
  <section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><div className="flex justify-between items-center mb-4"><div><h2 className="text-xl font-bold">🤖 AI Operational Pipeline</h2><p className="text-xs text-slate-500">Every stage is evidence-driven.</p></div><button disabled={busy} onClick={()=>test()} className="px-4 py-2 rounded-lg bg-emerald-500 text-slate-950 font-bold text-sm">Test pipeline</button></div><div className="grid md:grid-cols-2 xl:grid-cols-4 gap-3">{stages.map((s,i)=><StageCard key={s.key} stage={s} index={i}/>)}</div></section>
  <section className="rounded-2xl border border-orange-500/20 bg-slate-900/70 overflow-hidden"><div className="p-5 border-b border-slate-800"><h2 className="text-xl font-bold">🧾 Orders to Purchase</h2><p className="text-xs text-slate-500 mt-1">Only real paid customer orders enter this queue. AI selects the supplier.</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-950/60 text-xs text-slate-500 text-left"><tr><th className="p-3">Customer</th><th>Product</th><th>Source</th><th>Cart price</th><th>Qty</th><th>Total purchase</th><th>Address</th><th>Re-check</th><th>Supplier order / tracking</th><th>Action</th></tr></thead><tbody>{queue.length===0?<tr><td colSpan={10} className="p-10 text-center text-slate-500">No AI-selected customer orders are waiting for purchase.</td></tr>:queue.map((x:any)=><QueueRow key={x.orderId} x={x} busy={busy} onRecheck={recheck} onPurchase={purchase}/>)}</tbody></table></div></section>
  <section className="grid md:grid-cols-3 gap-4"><div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="font-bold">📦 Supplier purchase + tracking</h2><p className="text-xs text-slate-400 mt-2">Purchase only after a real customer order and passed re-check. Enter actual supplier order/tracking numbers.</p></div><div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="font-bold">🚚 Tracking lifecycle</h2><div className="mt-3 space-y-2 text-xs">{tracking.slice(0,6).map((x:any)=><div key={x.orderId} className="flex justify-between border-b border-slate-800 pb-2"><span>{x.orderNumber}<br/><span className="text-slate-500">{x.supplierOrderOrTracking||"—"}</span></span><span>{x.status}<br/><span className="text-slate-500">{x.carrier||"Awaiting carrier"}</span></div>)}</div></div><div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="font-bold">📣 Advertising preparation</h2>{channels.map((x:any)=><div key={x.key} className="flex justify-between mt-3 text-xs"><span>{x.label}</span><span>{x.connected?"CONNECTED":"NOT CONNECTED — no LIVE claim"}</span></div>)}</div></section>
 </div></main>;
}

function mTone(s:string){return tone(s==="PASS"?"PASSED":"NOT_READY")}
function StageCard({stage,index}:{stage:Stage;index:number}){return <div className={`rounded-xl border p-4 ${tone(stage.status)}`}><div className="flex justify-between"><span className="text-2xl">{stage.icon}</span><span className="text-[10px] font-bold px-2 py-1 rounded bg-black/20">{stage.status}</span></div><h3 className="font-semibold mt-3">{index+1}. {stage.title}</h3><p className="text-xs opacity-70 mt-2 leading-5">{stage.detail}</p></div>}
function QueueRow({x,busy,onRecheck,onPurchase}:{x:any;busy:boolean;onRecheck:(id:number)=>void;onPurchase:(x:any)=>void}){return <tr className="border-t border-slate-800 align-top"><td className="p-3">{x.customer?.name}<div className="text-xs text-slate-500">{x.customer?.phone}</div></td><td className="p-3 max-w-56">{x.product?.title}</td><td className="p-3">{x.source?.name}<div className="text-xs text-slate-500">Stock {x.source?.stock}</div></td><td className="p-3">{money(x.currentCartPriceInr)}</td><td className="p-3">{x.quantity}</td><td className="p-3 font-bold">{money(x.totalPurchaseAmountInr)}</td><td className="p-3 max-w-56">{x.customer?.deliveryAddress}<div className="text-xs text-slate-500">{x.customer?.city}, {x.customer?.state} {x.customer?.pincode}</div></td><td className="p-3"><span className={`px-2 py-1 rounded text-[10px] ${tone(x.reCheckStatus)}`}>{x.reCheckStatus||"NOT_CHECKED"}</span></td><td className="p-3 text-xs">{x.supplierOrderNumber||"—"}<br/>{x.trackingCode||"No tracking yet"}</td><td className="p-3">{x.reCheckStatus==="PASSED"?<button disabled={busy} onClick={()=>onPurchase(x)} className="px-2 py-1 rounded bg-orange-500 text-slate-950 font-bold text-xs">Purchase</button>:<button disabled={busy} onClick={()=>onRecheck(x.orderId)} className="px-2 py-1 rounded bg-slate-800 text-xs">Re-check</button>}</td></tr>}
