"use client";
import { useCallback, useEffect, useState } from "react";

type QueueItem={orderId:number;orderNumber:string;customer:{name:string;phone:string;email:string;deliveryAddress:string;city:string;state:string;pincode:string};product:{title:string;quantity:number};source:{name:string;currentCartPriceInr:number;shippingInr:number|null;stock:number};currentCartPriceInr:number;quantity:number;totalPurchaseAmountInr:number;customerPaidInr:number;reCheckStatus:string;fulfillmentStatus:string;supplierOrderNumber:string|null;trackingCode:string|null;carrierName:string|null};
const money=(n:number)=>`₹${Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2})}`;
const badge=(s:string)=>s.includes("PASS")||s.includes("PURCHASED")||s==="SCHEDULED"?"bg-emerald-500/15 text-emerald-300":s.includes("BLOCK")||s==="DRAFT"?"bg-amber-500/15 text-amber-300":"bg-slate-800 text-slate-300";

export default function OperationalDashboard(){
 const [queue,setQueue]=useState<QueueItem[]>([]),[tracking,setTracking]=useState<any[]>([]),[learning,setLearning]=useState<any>(null),[ads,setAds]=useState<any>(null),[milestone,setMilestone]=useState<any>(null),[orders,setOrders]=useState<any[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 const load=useCallback(async()=>{const [q,t,l,a,m,o]=await Promise.all([fetch("/api/orders/purchase-queue"),fetch("/api/agents/tracking"),fetch("/api/agents/learning"),fetch("/api/agents/advertising-status"),fetch("/api/milestone"),fetch("/api/orders")]);setQueue((await q.json()).queue||[]);setTracking((await t.json()).orders||[]);setLearning(await l.json());setAds(await a.json());setMilestone(await m.json());setOrders((await o.json()).orders||[]);},[]);
 useEffect(()=>{load()},[load]);
 async function recheck(x:QueueItem){setBusy(true);setMsg("Re-checking stock, cart price, shipping, delivery and margin…");const r=await fetch("/api/agents/recheck",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId:x.orderId})});const d=await r.json();setMsg(d.passed?`✓ ${x.orderNumber} passed order-time re-check.`:`⚠ ${x.orderNumber} blocked: one or more checks failed.`);setBusy(false);load();}
 async function purchase(x:QueueItem){const supplier=window.prompt(`Supplier order number for ${x.orderNumber}:`);if(!supplier)return;const trackingNo=window.prompt("Supplier tracking number (optional):")||"";setBusy(true);const r=await fetch("/api/orders/purchase-queue",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId:x.orderId,action:"purchased",supplierOrderNumber:supplier,trackingCode:trackingNo})});const d=await r.json();setMsg(d.error||`✓ Purchase recorded for ${x.orderNumber}.`);setBusy(false);load();}
 async function milestoneTest(){setBusy(true);await load();const r=await fetch("/api/milestone");setMilestone(await r.json());setMsg("Milestone re-tested against live database records.");setBusy(false);}
 const pending=queue.filter(x=>!x.fulfillmentStatus.startsWith("PURCHASED"));
 return <div className="min-h-screen bg-slate-950 text-slate-100 p-4 md:p-8"><div className="max-w-7xl mx-auto space-y-6">
  <header className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><div className="text-orange-400 font-mono text-xs tracking-widest">BHARATSHOP // OPERATIONS</div><h1 className="text-2xl md:text-3xl font-bold mt-1">Full Operational Loop</h1><p className="text-slate-400 text-sm mt-1">Customer order → re-check → your purchase → supplier tracking → learning</p></div><div className={`rounded-xl px-4 py-3 border ${milestone?.milestone==="PASS"?"border-emerald-500/40 bg-emerald-500/10":"border-amber-500/30 bg-amber-500/10"}`}><div className="text-xs text-slate-400">Milestone gate</div><div className="font-bold">{milestone?.milestone==="PASS"?"🟢 FULL END-TO-END LIVE":"🟡 NOT READY"}</div></div></header>
  {msg&&<div className="rounded-lg border border-slate-800 bg-slate-900 p-3 text-sm">{msg}</div>}
  <section className="grid grid-cols-2 md:grid-cols-5 gap-3">{[["Orders",orders.length],["Purchase queue",pending.length],["Tracked",tracking.length],["Agent events",learning?.recent?.length||0],["Ad channels",ads?.channels?.filter((x:any)=>x.connected).length||0]].map(([a,b])=><div key={String(a)} className="rounded-xl border border-slate-800 bg-slate-900/70 p-4"><div className="text-xs text-slate-500">{a}</div><div className="text-xl font-bold mt-1">{b}</div></div>)}</section>
  <section className="rounded-2xl border border-orange-500/20 bg-slate-900/70 overflow-hidden"><div className="p-5 border-b border-slate-800 flex items-center justify-between"><div><h2 className="font-bold">Orders to Purchase</h2><p className="text-xs text-slate-500 mt-1">Actual customer/cart economics only. Re-check before you purchase.</p></div><span className="text-xs font-mono text-orange-300">{pending.length} ACTIONS</span></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-xs text-slate-500 bg-slate-950/50"><tr><th className="p-3">Customer</th><th>Product</th><th>Source</th><th>Cart price</th><th>Qty</th><th>Total purchase</th><th>Delivery</th><th>Re-check</th><th>Supplier order/tracking</th><th></th></tr></thead><tbody>{queue.length===0?<tr><td colSpan={10} className="p-8 text-center text-slate-500">No orders currently waiting for purchase.</td></tr>:queue.map(x=><tr key={x.orderId} className="border-t border-slate-800 align-top"><td className="p-3"><b>{x.customer.name}</b><div className="text-xs text-slate-500">{x.customer.phone}</div><div className="text-xs text-slate-400 mt-1 max-w-48">{x.customer.deliveryAddress}</div></td><td className="p-3 max-w-48">{x.product.title}</td><td className="p-3">{x.source.name}<div className="text-xs text-slate-500">Stock: {x.source.stock}</div></td><td className="p-3">{money(x.currentCartPriceInr)}</td><td className="p-3">{x.quantity}</td><td className="p-3 font-semibold">{money(x.totalPurchaseAmountInr)}</td><td className="p-3">{x.customer.city}<div className="text-xs text-slate-500">{x.customer.state} {x.customer.pincode}</div></td><td className="p-3"><span className={`px-2 py-1 rounded text-[10px] font-bold ${badge(x.reCheckStatus)}`}>{x.reCheckStatus}</span></td><td className="p-3 text-xs">{x.supplierOrderNumber||"—"}<br/>{x.trackingCode||"No tracking yet"}</td><td className="p-3"><div className="flex gap-2"><button disabled={busy} onClick={()=>recheck(x)} className="px-2 py-1 rounded bg-slate-800 hover:bg-slate-700 text-xs">Re-check</button>{x.reCheckStatus==="PASSED"&&<button disabled={busy} onClick={()=>purchase(x)} className="px-2 py-1 rounded bg-orange-500 text-slate-950 font-bold text-xs">Purchase</button>}</div></td></tr>)}</tbody></table></div></section>
  <div className="grid md:grid-cols-3 gap-4"><section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="font-bold">Multi-source discovery</h2><p className="text-xs text-slate-400 mt-2">Source selection is based on actual customer/cart price, shipping, stock, delivery and margin. Wholesale price is never substituted.</p><div className="mt-4 text-xs font-mono text-emerald-300">API: /api/agents/discovery</div></section><section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="font-bold">Listing + Creative Agent</h2><p className="text-xs text-slate-400 mt-2">Generates optimized title, description, selling price, margin, marketing copy and ad creative data per qualified product.</p><div className="mt-4 text-xs font-mono text-emerald-300">API: /api/agents/listing</div></section><section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="font-bold">Advertising Agent</h2><div className="space-y-2 mt-3">{(ads?.channels||[]).map((c:any)=><div key={c.key} className="flex justify-between text-sm"><span>{c.label}</span><span className={`px-2 py-1 rounded text-[10px] ${c.connected?"bg-emerald-500/15 text-emerald-300":"bg-slate-800 text-slate-500"}`}>{c.connected?"CONNECTED":"NOT CONNECTED"}</span></div>)}</div><p className="text-xs text-slate-500 mt-3">No connected account = no LIVE claim.</p></section></div>
  <section className="grid md:grid-cols-2 gap-4"><div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="font-bold">Tracking Agent</h2><div className="mt-3 space-y-2 max-h-56 overflow-auto">{tracking.length?tracking.slice(0,8).map(x=><div key={x.orderId} className="flex justify-between text-xs border-b border-slate-800 pb-2"><span>{x.orderNumber}<br/><span className="text-slate-500">{x.supplierOrderOrTracking}</span></span><span className="text-right">{x.status}<br/><span className="text-slate-500">{x.carrier||"—"}</span></span></div>):<span className="text-xs text-slate-500">No supplier tracking recorded yet.</span>}</div></div><div className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><h2 className="font-bold">Learning Agent</h2><p className="text-xs text-slate-400 mt-2">Feeds source price changes, delivery time, cancellations, returns/RTO, profit and advertising performance back into future decisions.</p><div className="mt-4 text-xs text-slate-500">Recent persisted events: {learning?.recent?.length||0}</div></div></section>
  <section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Functional Milestone Test</h2><p className="text-xs text-slate-400 mt-1">The green state must come from observable operational data, not a hard-coded status.</p></div><button onClick={milestoneTest} disabled={busy} className="px-4 py-2 rounded-lg bg-emerald-500 text-slate-950 font-bold text-sm">Test now</button></div><div className="mt-4 grid md:grid-cols-4 gap-3">{Object.entries(milestone?.checks||{}).map(([k,v]:any)=><div key={k} className="rounded-lg bg-slate-950 p-3"><div className="text-xs text-slate-500">{k}</div><div className="text-xs mt-1">{v.status}</div></div>)}</div></section>
 </div></div>
}
