"use client";
import { useEffect, useState } from "react";

const defaultStates=["Maharashtra","Delhi","Karnataka","Gujarat","Tamil Nadu","Telangana","West Bengal","Rajasthan","Uttar Pradesh","Kerala"];
export default function SellerIntelligencePanel(){
 const [state,setState]=useState("Maharashtra"),[city,setCity]=useState("Mumbai"),[category,setCategory]=useState("GenZ fashion"),[leads,setLeads]=useState<any[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 async function load(){try{const r=await fetch(`/api/agents/seller-discovery?state=${encodeURIComponent(state)}&city=${encodeURIComponent(city)}&category=${encodeURIComponent(category)}`,{cache:"no-store"});const j=await r.json();if(Array.isArray(j.leads))setLeads(j.leads);if(j.error)setMsg(j.error)}catch{setMsg("Seller intelligence is temporarily unavailable.")}}
 useEffect(()=>{void load()},[]);
 async function discover(){setBusy(true);setMsg("AI is researching this local market…");try{const r=await fetch("/api/agents/seller-discovery",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({state,city,category})});const j=await r.json();if(!r.ok)throw new Error(j.message||j.error||"Research unavailable");setLeads(j.leads||[]);setMsg(`Found ${j.discovered||0} potential seller opportunities in ${city}.`)}catch(e){setMsg(e instanceof Error?e.message:"Research failed.")}finally{setBusy(false)}}
 return <section className="rounded-2xl border border-fuchsia-500/20 bg-gradient-to-br from-slate-900 to-slate-950 overflow-hidden"><div className="p-5 border-b border-slate-800"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3"><div><div className="text-xs font-mono tracking-widest text-fuchsia-300">INDIA MARKET INTELLIGENCE</div><h2 className="text-xl font-bold mt-1">🤝 Seller Discovery</h2><p className="text-xs text-slate-500 mt-1">State → city → trend → category → potential sellers. Research is evidence-based.</p></div><button disabled={busy} onClick={()=>void discover()} className="px-4 py-2 rounded-lg bg-fuchsia-500 text-white font-bold text-sm disabled:opacity-50">{busy?"Researching…":"Find sellers"}</button></div><div className="grid md:grid-cols-3 gap-2 mt-4"><select value={state} onChange={e=>setState(e.target.value)} className="bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-sm">{defaultStates.map(x=><option key={x}>{x}</option>)}</select><input value={city} onChange={e=>setCity(e.target.value)} placeholder="City" className="bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-sm"/><input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Category / trend" className="bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-sm"/></div>{msg&&<div className="mt-3 text-xs text-slate-400">{msg}</div>}</div><div className="p-5 grid md:grid-cols-2 xl:grid-cols-3 gap-3">{leads.length===0?<div className="md:col-span-2 xl:col-span-3 rounded-xl border border-dashed border-slate-700 p-8 text-center text-sm text-slate-500">No seller opportunities saved for this market yet. Choose a market and run discovery.</div>:leads.slice(0,9).map((x:any)=><article key={x.id||x.sourceUrl} className="rounded-xl border border-slate-800 bg-slate-900/70 p-4"><div className="flex justify-between gap-3"><div><div className="font-semibold">{x.brandName||x.sellerName}</div><div className="text-xs text-slate-500 mt-1">{x.city}, {x.state} · {x.category}</div></div><div className="text-right"><div className="text-lg font-black text-fuchsia-300">{x.opportunityScore}</div><div className="text-[9px] text-slate-500">OPPORTUNITY</div></div></div><p className="text-xs text-slate-400 mt-3 line-clamp-3">{x.evidence||"Evidence available from source."}</p><div className="grid grid-cols-2 gap-2 mt-3 text-[10px]"><span className="rounded bg-slate-950 p-2">Trend fit <b>{x.trendFitScore}</b></span><span className="rounded bg-slate-950 p-2">Unique <b>{x.uniquenessScore}</b></span></div>{x.sourceUrl&&<a href={x.sourceUrl} target="_blank" rel="noreferrer" className="block mt-3 text-xs text-cyan-300 truncate">View source ↗</a>}</article>)}</div></section>
}