plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bharatshop.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.bharatshop.app'
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName '1.4.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix ''
            versionNameSuffix ''
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
