"use client";
import {useState} from "react";
import Link from "next/link";

export default function SignupPage(){
 const [mode,setMode]=useState<"shopper"|"seller">("shopper");
 const [done,setDone]=useState(false);
 const [form,setForm]=useState({name:"",email:"",phone:"",password:"",store:"",category:""});
 const set=(k:string,v:string)=>setForm({...form,[k]:v});
 function submit(e:React.FormEvent){e.preventDefault();setDone(true)}
 return <main className="min-h-screen bg-[#0b0614] text-white px-4 py-8 sm:py-14"><div className="mx-auto max-w-5xl">
 <header className="flex items-center justify-between mb-10"><Link href="/" className="text-2xl font-black tracking-tight bg-gradient-to-r from-fuchsia-400 via-violet-400 to-cyan-300 bg-clip-text text-transparent">BharatShop</Link><Link href="/" className="text-sm font-bold text-white/60">← Back to shop</Link></header>
 <div className="grid lg:grid-cols-2 gap-8"><section className="rounded-[2rem] p-7 sm:p-10 bg-gradient-to-br from-fuchsia-600/25 via-violet-600/15 to-cyan-400/10 border border-white/10"><p className="text-xs font-black uppercase tracking-[.25em] text-cyan-300">Welcome to the next drop</p><h1 className="text-4xl sm:text-6xl font-black leading-[.95] mt-4">Shop it.<br/>Sell it.<br/><span className="text-fuchsia-300">Make it yours.</span></h1><p className="mt-6 text-white/65 leading-7">Create your BharatShop account to save favourites and track orders. Have something worth selling? Join as a seller and bring your brand to the store.</p><div className="grid grid-cols-2 gap-3 mt-8"><div className="rounded-2xl bg-white/5 border border-white/10 p-4"><b>Fresh drops</b><p className="text-xs text-white/50 mt-1">New styles and useful finds.</p></div><div className="rounded-2xl bg-white/5 border border-white/10 p-4"><b>For sellers</b><p className="text-xs text-white/50 mt-1">Apply to sell your products.</p></div></div></section>
 <section className="rounded-[2rem] bg-white text-slate-900 p-6 sm:p-8 shadow-2xl"><div className="flex p-1 bg-slate-100 rounded-xl mb-6"><button type="button" onClick={()=>setMode("shopper")} className={`flex-1 h-10 rounded-lg text-sm font-black ${mode==="shopper"?"bg-slate-900 text-white":"text-slate-500"}`}>Customer</button><button type="button" onClick={()=>setMode("seller")} className={`flex-1 h-10 rounded-lg text-sm font-black ${mode==="seller"?"bg-fuchsia-600 text-white":"text-slate-500"}`}>I want to sell</button></div>
 {done?<div className="py-12 text-center"><div className="text-5xl">✨</div><h2 className="text-2xl font-black mt-4">{mode==="seller"?"Seller application started":"Welcome to BharatShop"}</h2><p className="text-slate-500 mt-2">Your details have been captured for the next step.</p></div>:<form onSubmit={submit} className="space-y-4"><p className="text-xs font-black uppercase tracking-widest text-fuchsia-600">{mode==="seller"?"Seller application":"Create your account"}</p><h2 className="text-3xl font-black -mt-2">{mode==="seller"?"Bring your products to BharatShop":"Join BharatShop"}</h2><input required value={form.name} onChange={e=>set("name",e.target.value)} placeholder="Full name" className="w-full h-12 rounded-xl border px-4"/><input required type="email" value={form.email} onChange={e=>set("email",e.target.value)} placeholder="Email address" className="w-full h-12 rounded-xl border px-4"/><input required value={form.phone} onChange={e=>set("phone",e.target.value)} placeholder="Phone number" className="w-full h-12 rounded-xl border px-4"/>{mode==="seller"&&<><input required value={form.store} onChange={e=>set("store",e.target.value)} placeholder="Brand / store name" className="w-full h-12 rounded-xl border px-4"/><input required value={form.category} onChange={e=>set("category",e.target.value)} placeholder="What do you sell? e.g. streetwear" className="w-full h-12 rounded-xl border px-4"/></>}<input required type="password" minLength={8} value={form.password} onChange={e=>set("password",e.target.value)} placeholder="Create password (8+ characters)" className="w-full h-12 rounded-xl border px-4"/><button className="w-full h-12 rounded-xl bg-gradient-to-r from-fuchsia-600 to-violet-600 text-white font-black">{mode==="seller"?"Apply to sell":"Create account"}</button><p className="text-xs text-center text-slate-400">By continuing, you agree to BharatShop's terms and privacy policy.</p></form>}
 </section></div></div></main>
}