// ─────────────────────────────────────────────────────────────────────────────
// MEDIA RESOLVER — single source of truth for product image resolution.
// Pipeline: PostgreSQL staging/cache -> SearXNG -> reachable image download
// -> Claude Vision -> >=4 verified images -> publication gate.
// No placeholder, stock fallback, or unverified image can be published.
// ─────────────────────────────────────────────────────────────────────────────
import { db } from "@/db";
import { productImages, products } from "@/db/schema";
import { asc, eq, ilike } from "drizzle-orm";
import { searxngImageSearch, SearXNGRateLimitError } from "@/lib/searxng";
const STOP=new Set(["the","with","and","for","from","pack","piece","pieces","new","best","online","india","buy","sale","free","exact","product","official","image","images","front","back","side","angle","box","packaging","contents","colour","colors","color","variants"]);
const BAD=/(unsplash|placeholder|placehold|picsum|loremflickr|placekitten|dummyimage|via\.placeholder)/i;
const FASHION=/(fashion|women|woman|men|man|saree|sari|kurti|kurta|dress|shirt|tshirt|t-shirt|jeans|trouser|petticoat|shapewear|lehenga|salwar|apparel|clothing|footwear|shoe|sandal|jewellery|jewelry)/i;
const ANTHROPIC_MODEL=process.env.ANTHROPIC_VISION_MODEL||"claude-sonnet-5";
const MIN_CONFIDENCE=Number(process.env.IMAGE_VERIFY_MIN_CONFIDENCE||0.75),MIN_IMAGES=4,MAX_IMAGES=8,MAX_VISION_CANDIDATES=8,SEARCH_LIMIT=8;
const FAILURE_CACHE_MS=10*60*1000;
const inFlight=new Map<number,Promise<any>>();
const recentFailures=new Map<number,{expiresAt:number;result:any}>();
type ImageCandidate={url:string;sourceUrl?:string;title?:string};type Product={id:number;title:string;brand:string;category:string;sellingPriceInr?:unknown;mrpInr?:unknown;stockCount?:unknown};type VisionVerdict={url:string;matches:boolean;confidence:number;reason:string};
function tokens(s:string){return String(s||"").toLowerCase().replace(/[^a-z0-9]+/g," ").split(/\s+/).filter(x=>x.length>2&&!STOP.has(x));}
function textScore(item:ImageCandidate,product:Product){const ts=tokens(`${product.brand!=="Generic"?product.brand:""} ${product.title}`),hay=`${item.title||""} ${item.sourceUrl||item.url||""}`.toLowerCase(),hits=ts.filter(t=>hay.includes(t)).length;return ts.length?hits/ts.length:0;}
function validPublicationData(product:Product){const selling=Number(product.sellingPriceInr),mrp=Number(product.mrpInr),stock=Number(product.stockCount);return selling>0&&mrp>=selling&&stock>0;}
function cacheFailure(productId:number,result:any){recentFailures.set(productId,{expiresAt:Date.now()+FAILURE_CACHE_MS,result});}
async function fetchImageAsBase64(url:string):Promise<{data:string;mediaType:string}|null>{try{const parsed=new URL(url);if(!["http:","https:"].includes(parsed.protocol))return null;const res=await fetch(parsed.toString(),{signal:AbortSignal.timeout(10000),redirect:"follow",cache:"no-store"});if(!res.ok)return null;const contentType=(res.headers.get("content-type")||"").split(";")[0].toLowerCase();if(!contentType.startsWith("image/"))return null;const buf=await res.arrayBuffer();if(!buf.byteLength||buf.byteLength>5_000_000)return null;return{data:Buffer.from(buf).toString("base64"),mediaType:contentType};}catch{return null;}}
async function verifyImagesWithClaude(candidates:ImageCandidate[],product:Product):Promise<VisionVerdict[]>{const apiKey=process.env.ANTHROPIC_API_KEY;if(!apiKey)throw new Error("ANTHROPIC_API_KEY is not configured");const downloaded=await Promise.all(candidates.map(async c=>({candidate:c,image:await fetchImageAsBase64(c.url)}))),usable=downloaded.filter(d=>d.image);if(!usable.length)return[];const content:any[]=[{type:"text",text:`Product: "${product.title}" | Brand: ${product.brand} | Category: ${product.category}\n\nEvaluate ${usable.length} candidate images labeled Image 1 through Image ${usable.length}. For EACH image decide whether it genuinely depicts the named product: correct product type, brand marks when visible, form factor, and stated color/variant. Reject generic stock photos, lifestyle images that do not clearly show the product, wrong variants, and unrelated collages. Respond ONLY with JSON: [{"index":1,"matches":true,"confidence":0.9,"reason":"..."}]`}];usable.forEach((d,i)=>{content.push({type:"text",text:`Image ${i+1}:`});content.push({type:"image",source:{type:"base64",media_type:d.image!.mediaType,data:d.image!.data}})});const res=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json","x-api-key":apiKey,"anthropic-version":"2023-06-01"},body:JSON.stringify({model:ANTHROPIC_MODEL,max_tokens:2000,messages:[{role:"user",content}]})});if(!res.ok)throw new Error(`Claude vision call returned ${res.status}`);const data=await res.json(),text=(data.content||[]).map((b:any)=>b.text||"").join("");let parsed:any[];try{const jsonMatch=text.match(/\[[\s\S]*\]/);parsed=JSON.parse(jsonMatch?jsonMatch[0]:text)}catch{throw new Error("Claude vision returned non-JSON output");}return parsed.map((v:any)=>{const idx=Number(v.index)-1,c=usable[idx]?.candidate;return{url:c?.url||"",matches:!!v.matches,confidence:Number(v.confidence)||0,reason:String(v.reason||"")}}).filter(v=>v.url);}
async function resolveOne(productId?:number,productName?:string){let product:any=null;if(productId)product=(await db.select().from(products).where(eq(products.id,productId)).limit(1))[0];if(!product&&productName)product=(await db.select().from(products).where(ilike(products.title,`%${productName}%`)).orderBy(asc(products.id)).limit(1))[0];if(!product)return{status:"NOT_FOUND",reason:"Product was not found in the catalogue"};
 const cachedFailure=recentFailures.get(product.id);if(cachedFailure&&cachedFailure.expiresAt>Date.now())return{...cachedFailure.result,cachedFailure:true};if(cachedFailure)recentFailures.delete(product.id);
 const existing=await db.select().from(productImages).where(eq(productImages.productId,product.id));const approved=existing.filter(x=>String(x.verificationStatus)==="AI_VISION_VERIFIED"&&!BAD.test(x.imageUrl)&&/^https:\/\//i.test(x.imageUrl)&&Number(x.verificationConfidence)>=MIN_CONFIDENCE&&String(x.verificationProvider)==="anthropic"&&String(x.verificationModel)===ANTHROPIC_MODEL&&!!x.verifiedAt).sort((a,b)=>a.sortOrder-b.sortOrder);
 if(approved.length>=MIN_IMAGES){const publishable=validPublicationData(product);if(publishable&&product.status!=="Published")await db.update(products).set({status:"Published",imageUrl:approved[0].imageUrl,updatedAt:new Date()}).where(eq(products.id,product.id));return{status:"COMPLETE_MEDIA_RESOLVED",provider:"postgres-cache",productId:product.id,product:product.title,imageCount:Math.min(approved.length,MAX_IMAGES),images:approved.slice(0,MAX_IMAGES).map(x=>({url:x.imageUrl,confidence:Number(x.verificationConfidence),reason:String((x.verificationMetadata as any)?.reason||"Previously AI-vision-verified")})),cached:true,publicationGate:publishable?"PASS":"BLOCK"};}
 const fashion=FASHION.test(`${product.category} ${product.title}`),base=`${product.title} ${product.brand!=="Generic"?product.brand:""}`.trim(),queries=fashion?[`${base} product photo`,`${base} front back colour variant`]:[`${base} official product image`,`${base} packaging front back product images`],found:ImageCandidate[]=[];for(const q of queries){try{const results=await searxngImageSearch(q,{limit:SEARCH_LIMIT,timeoutMs:15000});found.push(...results.map(r=>({url:r.url,sourceUrl:r.sourceUrl,title:r.title})));}catch(e){const result={status:"SEARCH_ERROR",productId:product.id,product:product.title,error:e instanceof Error?e.message:"SearXNG image search failed",retryAfterMs:e instanceof SearXNGRateLimitError?e.retryAfterMs:undefined,searched:queries,publicationGate:"BLOCK",message:"Image search is rate-limited or unavailable. Product remains staged."};cacheFailure(product.id,result);return result;}}
 const seen=new Set<string>(),preFiltered=found.filter(x=>x.url&&/^https?:\/\//i.test(x.url)&&!BAD.test(x.url)).filter(x=>seen.has(x.url)?false:(seen.add(x.url),true)).map(x=>({...x,textScore:textScore(x,product)})).sort((a,b)=>b.textScore-a.textScore).slice(0,MAX_VISION_CANDIDATES);
 if(!preFiltered.length){const result={status:"NEEDS_IMAGES",productId:product.id,product:product.title,imageCount:0,searched:queries,publicationGate:"BLOCK",message:"No reachable image candidates returned by SearXNG. Product remains staged."};cacheFailure(product.id,result);return result;}
 let verdicts:VisionVerdict[];try{verdicts=await verifyImagesWithClaude(preFiltered,product);}catch(e){const result={status:"VERIFICATION_FAILED",productId:product.id,product:product.title,error:e instanceof Error?e.message:"Claude vision verification failed",publicationGate:"BLOCK",message:"Vision verification could not run. Product remains staged."};cacheFailure(product.id,result);return result;}
 const accepted=verdicts.filter(v=>v.matches&&v.confidence>=MIN_CONFIDENCE&&!BAD.test(v.url)&&/^https:\/\//i.test(v.url)).sort((a,b)=>b.confidence-a.confidence).slice(0,MAX_IMAGES);if(accepted.length<MIN_IMAGES){const result={status:"NEEDS_IMAGES",productId:product.id,product:product.title,imageCount:accepted.length,verdicts,searched:queries,publicationGate:"BLOCK",message:`Only ${accepted.length} image(s) passed vision verification (need ${MIN_IMAGES}). Product remains staged.`};cacheFailure(product.id,result);return result;}
 const meta=accepted.map(v=>preFiltered.find(d=>d.url===v.url)),publishable=validPublicationData(product),verifiedAt=new Date();await db.transaction(async tx=>{await tx.delete(productImages).where(eq(productImages.productId,product.id));await tx.insert(productImages).values(accepted.map((v,index)=>({productId:product.id,imageUrl:v.url,sourceUrl:meta[index]?.sourceUrl||v.url,sortOrder:index,altText:meta[index]?.title||`${product.title} view ${index+1}`,verificationStatus:"AI_VISION_VERIFIED",verificationConfidence:v.confidence.toFixed(3),verificationModel:ANTHROPIC_MODEL,verificationProvider:"anthropic",verificationMetadata:{reason:v.reason,matches:v.matches,sourceTitle:meta[index]?.title||"",verifiedAt:verifiedAt.toISOString()},verifiedAt})));if(publishable)await tx.update(products).set({imageUrl:accepted[0].url,status:"Published",updatedAt:new Date()}).where(eq(products.id,product.id));});
 return{status:"COMPLETE_MEDIA_RESOLVED",provider:"searxng+claude-vision",productId:product.id,product:product.title,imageCount:accepted.length,images:accepted.map(v=>({url:v.url,confidence:v.confidence,reason:v.reason})),cached:false,publicationGate:publishable?"PASS":"BLOCK",message:publishable?`${accepted.length} images passed Claude vision verification and the product was published.`:`${accepted.length} images passed Claude vision verification, but the product failed pricing/stock publication validation and remains staged.`};}
export async function resolveVerifiedProductMedia(productId?:number,productName?:string){if(!productId)return resolveOne(productId,productName);const existing=inFlight.get(productId);if(existing)return existing;const work=resolveOne(productId,productName).finally(()=>inFlight.delete(productId));inFlight.set(productId,work);return work;}
export async function resolveVerifiedMediaForProducts(productList:Array<{id:number}>,maxBatch=25){const batch=productList.slice(0,maxBatch),out:any[]=[];for(const p of batch){try{out.push(await resolveVerifiedProductMedia(p.id));}catch(e){out.push({status:"ERROR",productId:p.id,error:e instanceof Error?e.message:"resolve failed",publicationGate:"BLOCK"});}}return out;}
