/**
 * Broad discovery queries used by the catalogue researcher.
 *
 * These queries are discovery hints only. A search result is NOT proof of
 * current stock, price, tax, delivery, serviceability, payment support, or
 * authorization to fulfil an order. Those facts must be re-checked by an
 * authorized source adapter before publication or purchase.
 */
export const UNIVERSAL_CATALOGUE_QUERIES = [
  "best selling smartphones India price",
  "best selling tablets India price",
  "best selling laptops India price",
  "best selling desktop computers India price",
  "gaming PCs India price",
  "computer monitors India price",
  "PC components India price",
  "computer accessories India price",
  "networking products India price",
  "SSD hard drives storage India price",
  "gaming consoles India price",
  "gaming accessories India price",
  "smart TVs India price",
  "speakers soundbars India price",
  "headphones earbuds India price",
  "cameras lenses India price",
  "smartwatches wearables India price",
  "refrigerators India price",
  "washing machines India price",
  "air conditioners India price",
  "fans air coolers India price",
  "kitchen appliances India price",
  "cookware kitchen storage India price",
  "furniture India price",
  "mattresses India price",
  "home decor lighting India price",
  "storage organizers India price",
  "men fashion India price",
  "women fashion India price",
  "kids fashion India price",
  "footwear India price",
  "bags luggage India price",
  "watches fashion accessories India price",
  "beauty products India price",
  "personal care products India price",
  "baby products India price",
  "toys games India price",
  "books stationery India price",
  "sports fitness products India price",
  "automotive accessories India price",
  "bike accessories India price",
  "car accessories India price",
  "tools hardware India price",
  "home improvement products India price",
  "office supplies India price",
  "pet supplies India price",
  "household essentials India price",
  "travel accessories India price",
  "garden outdoor products India price",
  "cleaning laundry products India price",
] as const;
