import { NextResponse } from "next/server";
import { db, pool } from "@/db";
import { aiActivityLogs, productDetails, productImages, products, storefrontOrders } from "@/db/schema";
import { desc, eq } from "drizzle-orm";
import { POST as runListingRoute } from "@/app/api/agents/listing/route";

export const dynamic="force-dynamic";
export const maxDuration=300;

const MIN_MARGIN_PCT=Number(process.env.CEO_MIN_MARGIN_PCT??25);
const MAX_LISTINGS_PER_CYCLE=Math.max(5,Math.min(40,Number(process.env.CEO_MAX_LISTINGS_PER_CYCLE??30)));
const RESEARCH_INTERVAL_MS=Math.max(15*60*1000,Number(process.env.CEO_RESEARCH_INTERVAL_MS??60*60*1000));
const MARKET_RETRY_MS=Math.max(15*60*1000,Number(process.env.CEO_MARKET_RETRY_MS??30*60*1000));
const PLACEHOLDER_HOSTS=["unsplash.com","placeholder.com","placehold.co","picsum.photos","dummyimage.com"];
const VERIFIED_MEDIA=new Set(["AI_VISION_VERIFIED","LOCAL_EVIDENCE_VERIFIED"]);
const VERIFIED_MEDIA_PROVIDERS=new Set(["local-ai","local-evidence"]);
const MIN_MEDIA_CONFIDENCE=.75;
const MTO_FASHION_BRANDS=new Set(["bharatshop studio","bharatdrip"]);

function realUrl(value:unknown){if(typeof value!=="string"||!/^https?:\/\//i.test(value))return false;const lower=value.toLowerCase();return!PLACEHOLDER_HOSTS.some(host=>lower.includes(host));}
function automationToken(){return process.env.BHARATSHOP_AUTOMATION_TOKEN||process.env.AUTOMATION_TOKEN||process.env.CRON_SECRET||"";}
function cronAuthorized(req:Request){const expected=automationToken();if(!expected)return true;return req.headers.get("authorization")===`Bearer ${expected}`||req.headers.get("x-automation-token")===expected;}
async function ensureCeoTables(){await pool.query(`CREATE TABLE IF NOT EXISTS ceo_approvals (id SERIAL PRIMARY KEY,title TEXT NOT NULL,action_type TEXT NOT NULL,payload JSONB NOT NULL DEFAULT '{}'::jsonb,reason TEXT NOT NULL DEFAULT '',risk_level TEXT NOT NULL DEFAULT 'MEDIUM',status TEXT NOT NULL DEFAULT 'PENDING',requested_by TEXT NOT NULL DEFAULT 'BHARATSHOP CEO',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),decided_at TIMESTAMPTZ,decision_note TEXT NOT NULL DEFAULT '')`);await pool.query(`CREATE TABLE IF NOT EXISTS agent_audit_records (id SERIAL PRIMARY KEY,agent_name TEXT NOT NULL,event_type TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'INFO',summary TEXT NOT NULL DEFAULT '',evidence JSONB NOT NULL DEFAULT '{}'::jsonb,approval_id INTEGER,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);}
async function audit(agent:string,event:string,status:string,summary:string,evidence:unknown,approvalId?:number){await pool.query(`INSERT INTO agent_audit_records(agent_name,event_type,status,summary,evidence,approval_id) VALUES($1,$2,$3,$4,$5,$6)`,[agent,event,status,summary,JSON.stringify(evidence??{}),approvalId??null]);}
async function parseResponse(response:Response){const raw=await response.text();let data:any;try{data=JSON.parse(raw)}catch{data={raw:raw.slice(0,2000)}}return{ok:response.ok,status:response.status,data};}
async function callAgent(origin:string,path:string,body:unknown){const token=automationToken();const response=await fetch(`${origin}${path}`,{method:"POST",headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`,"x-automation-token":token}:{})},body:JSON.stringify(body),cache:"no-store",signal:AbortSignal.timeout(90000)});return parseResponse(response);}
async function callListingInProcess(origin:string,body:unknown){const token=automationToken();const request=new Request(`${origin}/api/agents/listing`,{method:"POST",headers:{"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`,"x-automation-token":token}:{})},body:JSON.stringify(body)});return parseResponse(await runListingRoute(request));}
async function researchDue(){const result=await pool.query<{created_at:Date}>(`SELECT created_at FROM agent_audit_records WHERE agent_name=$1 AND event_type=$2 ORDER BY created_at DESC LIMIT 1`,["AI-Product-Research-Agent","CYCLE_EXECUTION"]);const last=result.rows[0]?.created_at?new Date(result.rows[0].created_at).getTime():0;return{due:!last||Date.now()-last>=RESEARCH_INTERVAL_MS,lastResearchAt:last?new Date(last).toISOString():null};}
function specsOf(details:any){return details?.specificationsJson&&typeof details.specificationsJson==="object"&&!Array.isArray(details.specificationsJson)?details.specificationsJson as Record<string,any>:{};}
function fashionOrigin(details:any,product:any){const s=specsOf(details);return String(s.designOrigin||product?.brand||"").trim();}
function isMadeToOrder(details:any,product:any){const s=specsOf(details),origin=fashionOrigin(details,product).toLowerCase();return String(product.supplierName||"").toLowerCase()==="qikink"&&MTO_FASHION_BRANDS.has(origin)&&String(s.inventoryMode||"").toUpperCase()==="MADE_TO_ORDER"&&String(s.productionSupplier||"").toLowerCase()==="qikink"&&Boolean(String(s.qikinkProductCode||"").trim());}
function validOriginalFashionImage(image:any,details:any,product:any){const s=specsOf(details),origin=fashionOrigin(details,product).toLowerCase();return String(image.verificationStatus)==="AI_GENERATED_ORIGINAL"&&String(image.verificationProvider)==="bharatshop-studio"&&Number(image.verificationConfidence)>=.99&&!!image.verifiedAt&&realUrl(image.imageUrl)&&MTO_FASHION_BRANDS.has(origin)&&String(s.productionSupplier||"").toLowerCase()==="qikink"&&Boolean(String(s.qikinkProductCode||"").trim());}
function queuePriority(status:string){return status==="CEO_PENDING"?0:status==="CEO_APPROVED"?1:2;}
function marketRetryDue(product:any){return String(product.status)!=="MARKET_RESEARCH_PENDING"||Date.now()-new Date(product.updatedAt).getTime()>=MARKET_RETRY_MS;}
function isRealClientOrder(order:any){
 const ref=String(order?.orderRef||"").trim(),source=String(order?.source||"").toLowerCase(),shopifyId=String(order?.shopifyOrderId||"").trim();
 const markers=`${ref} ${source} ${order?.notes||""} ${order?.customerName||""} ${order?.customerEmail||""}`.toLowerCase();
 if(/\b(test|demo|acceptance|synthetic|fixture|seed)\b/i.test(markers))return false;
 const ownWebsite=source==="own_website"&&/^BS-WEB-/i.test(ref),shopify=source.includes("shopify")||shopifyId.length>0;
 const email=String(order?.customerEmail||"").trim(),phone=String(order?.customerPhone||"").replace(/\D/g,"");
 return Boolean((ownWebsite||shopify)&&email.includes("@")&&phone.length>=10&&Number(order?.totalAmountInr)>0);
}

async function runCycle(req:Request){
 await ensureCeoTables();const url=new URL(req.url),origin=url.origin,skipResearch=url.searchParams.get("skipResearch")==="1",startedAt=Date.now();const results:any={research:null,ceo:null,listings:[],orders:null,errors:[] as string[]};
 try{if(skipResearch)results.research={skipped:true,reason:"explicit_skip"};else{const cadence=await researchDue();if(cadence.due){results.research=await callAgent(origin,"/api/automation/research-products",{userId:1,limit:Math.min(5,MAX_LISTINGS_PER_CYCLE)});await audit("AI-Product-Research-Agent","CYCLE_EXECUTION",results.research.ok?"SUCCESS":"WARNING","Scheduled research evidence cycle completed; candidates remain CEO-gated.",{...results.research.data,researchIntervalMs:RESEARCH_INTERVAL_MS});}else results.research={skipped:true,reason:"research_cooldown",researchIntervalMs:RESEARCH_INTERVAL_MS,lastResearchAt:cadence.lastResearchAt};}}catch(error){results.errors.push(`research: ${error instanceof Error?error.message:"failed"}`);}

 const allQueue=await db.select().from(products).orderBy(desc(products.aiScore));
 const queue=allQueue.filter(p=>["CEO_PENDING","CEO_APPROVED","MARKET_RESEARCH_PENDING"].includes(String(p.status))&&marketRetryDue(p)).sort((a,b)=>queuePriority(String(a.status))-queuePriority(String(b.status))||b.aiScore-a.aiScore).slice(0,MAX_LISTINGS_PER_CYCLE);
 const approved:any[]=[],blocked:any[]=[];
 for(const product of queue){
  const previousStatus=String(product.status);const images=await db.select().from(productImages).where(eq(productImages.productId,product.id));const[details]=await db.select().from(productDetails).where(eq(productDetails.productId,product.id)).limit(1);const mto=isMadeToOrder(details,product);
  const verifiedImages=images.filter(image=>mto?validOriginalFashionImage(image,details,product):(VERIFIED_MEDIA.has(String(image.verificationStatus))&&VERIFIED_MEDIA_PROVIDERS.has(String(image.verificationProvider))&&Number(image.verificationConfidence)>=MIN_MEDIA_CONFIDENCE&&!!image.verifiedAt&&realUrl(image.imageUrl)&&realUrl(image.sourceUrl)));
  const specs=details?.specificationsJson,hasSpecs=Boolean(specs&&typeof specs==="object"&&Object.keys(specs as Record<string,unknown>).length>0),sourceVerified=Boolean(details&&details.verificationStatus==="SOURCE_VERIFIED"&&realUrl(details.sourceUrl));
  const price=Number(product.sellingPriceInr),cost=Number(product.supplierCostInr),shipping=Number(product.shippingCostInr),gst=Number(product.gstPct),landed=cost+shipping+(cost*gst/100),profit=price-landed,margin=price>0?profit/price*100:0,availabilityValid=mto||Number(product.stockCount)>0;
  const requiredMargin=mto?Math.max(18,Number(specsOf(details).minMarginPct||22)):MIN_MARGIN_PCT;
  const valid=Boolean(product.title.trim()&&product.supplierName.trim()&&sourceVerified&&verifiedImages.length>=4&&verifiedImages.length<=8&&hasSpecs&&availabilityValid&&Number.isFinite(price)&&price>0&&Number.isFinite(cost)&&cost>=0&&Number.isFinite(profit)&&profit>0&&margin>=requiredMargin);
  const evidence={productId:product.id,title:product.title,sku:product.sku,previousStatus,brand:product.brand,designOrigin:fashionOrigin(details,product),source:product.supplierName,sourceUrl:details?.sourceUrl||"",sourceVerificationStatus:details?.verificationStatus||"NONE",sourceVerified,verifiedImageCount:verifiedImages.length,requiredImageRange:"4-8",hasSpecifications:hasSpecs,availabilityMode:mto?"MADE_TO_ORDER":"IN_STOCK",stockCount:product.stockCount,supplierCostInr:cost,shippingCostInr:shipping,gstPct:gst,sellingPriceInr:price,landedCostInr:Number(landed.toFixed(2)),netProfitInr:Number(profit.toFixed(2)),marginPct:Number(margin.toFixed(2)),minMarginPct:requiredMargin};
  const actionType=valid?(previousStatus==="CEO_PENDING"?"CEO_VERIFIED_PRODUCT":"CEO_REVALIDATED_PRODUCT"):"CEO_HELD_PRODUCT";
  const[approval]=await db.insert(aiActivityLogs).values({userId:product.userId,agentName:"CEO-Agent",actionType,message:valid?`CEO ${previousStatus==="CEO_PENDING"?"verified":"revalidated"} ${product.title}; releasing it to the listing gate.`:`CEO held ${product.title}; source/media/specification/economics evidence is incomplete.`,profitImpactInr:valid?profit.toFixed(2):"0.00",metadataJson:evidence,status:valid?"SUCCESS":"WARNING"}).returning({id:aiActivityLogs.id});
  if(valid){await db.update(products).set({status:"CEO_APPROVED",updatedAt:new Date()}).where(eq(products.id,product.id));approved.push({productId:product.id,auditId:approval.id,previousStatus,marginPct:Number(margin.toFixed(2)),imageCount:verifiedImages.length,madeToOrder:mto,designOrigin:fashionOrigin(details,product)});}
  else{await db.update(products).set({status:"STAGED",updatedAt:new Date()}).where(eq(products.id,product.id));blocked.push({productId:product.id,auditId:approval.id,previousStatus,imageCount:verifiedImages.length,hasSpecs,sourceVerified,madeToOrder:mto,designOrigin:fashionOrigin(details,product)});}
 }
 results.ceo={inspected:queue.length,approved:approved.length,blocked:blocked.length,awaitingInitialReview:queue.filter(p=>String(p.status)==="CEO_PENDING").length,retryCandidates:queue.filter(p=>String(p.status)!=="CEO_PENDING").length,approvedProducts:approved,blockedProducts:blocked};await audit("CEO-Agent","CEO_VERIFICATION_CYCLE","SUCCESS",`CEO inspected ${queue.length} candidates; ${approved.length} passed evidence validation and ${blocked.length} returned to staging.`,results.ceo);
 for(const item of approved){try{const listing=await callListingInProcess(origin,{productId:item.productId,ceoApproved:true});let nextStatus:string|null=null;if(!listing.ok||listing.data?.error){const marketUnverified=listing.data?.marketBenchmark?.status==="UNVERIFIED"||/market price could not be verified/i.test(String(listing.data?.error||""));nextStatus=marketUnverified?"MARKET_RESEARCH_PENDING":listing.status>=500?"CEO_APPROVED":"STAGED";await db.update(products).set({status:nextStatus,updatedAt:new Date()}).where(eq(products.id,item.productId));}results.listings.push({productId:item.productId,...listing,nextStatus});await audit("Listing-Creative-Agent","CEO_APPROVED_LISTING",listing.ok?"SUCCESS":"BLOCKED",listing.ok?`Listing execution completed for CEO-approved product ${item.productId}.`:`Listing execution blocked for product ${item.productId}; moved to ${nextStatus}.`,{...listing.data,nextStatus});}catch(error){results.errors.push(`listing:${item.productId}: ${error instanceof Error?error.message:"failed"}`);}}
 const orderCandidates=await db.select({id:storefrontOrders.id,orderRef:storefrontOrders.orderRef,customerName:storefrontOrders.customerName,customerEmail:storefrontOrders.customerEmail,customerPhone:storefrontOrders.customerPhone,totalAmountInr:storefrontOrders.totalAmountInr,fulfillmentStatus:storefrontOrders.fulfillmentStatus,source:storefrontOrders.source,shopifyOrderId:storefrontOrders.shopifyOrderId,notes:storefrontOrders.notes,orderedAt:storefrontOrders.orderedAt}).from(storefrontOrders).orderBy(desc(storefrontOrders.orderedAt)).limit(50);
 const realOrders=orderCandidates.filter(isRealClientOrder);
 results.orders=realOrders.length?{realOrderCount:realOrders.length,candidateOrderCount:orderCandidates.length,humanInteractionGate:true,orders:realOrders.map(o=>({id:o.id,orderRef:o.orderRef,fulfillmentStatus:o.fulfillmentStatus,source:o.source}))}:{realOrderCount:0,candidateOrderCount:orderCandidates.length,humanInteractionGate:false,policy:"No human order gate before a genuine BS-WEB/Shopify customer order."};
 if(realOrders.length)await audit("CEO-Agent","REAL_ORDER_HUMAN_GATE","READY","A genuine customer storefront order exists; consequential fulfillment remains human-gated before supplier purchase or production submission.",results.orders);
 results.durationMs=Date.now()-startedAt;await db.insert(aiActivityLogs).values({userId:1,agentName:"CEO-Agent",actionType:"FIVE_MINUTE_CYCLE_COMPLETED",message:`CEO cycle completed: ${queue.length} candidates inspected, ${approved.length} evidence-passed, ${blocked.length} held, ${realOrders.length} genuine client orders present.`,profitImpactInr:"0.00",metadataJson:results,status:results.errors.length?"WARNING":"SUCCESS"});return results;
}
export async function GET(req:Request){if(!cronAuthorized(req))return NextResponse.json({error:"Unauthorized"},{status:401});try{return NextResponse.json({status:"COMPLETED",schedule:"*/5 * * * *",agents24x7:true,ceoException:true,researchIntervalMs:RESEARCH_INTERVAL_MS,marketRetryMs:MARKET_RETRY_MS,maxListingsPerCycle:MAX_LISTINGS_PER_CYCLE,mediaPolicy:"Physical products: 4-8 verified source media; BharatShop Studio/BharatDrip: 4 original local design views + verified Qikink production mapping",pipelinePolicy:"CEO_PENDING is CEO review only. CEO_APPROVED is listing-ready. Unverified market pricing moves to MARKET_RESEARCH_PENDING and is retried after cooldown. Human order gating starts only when a genuine client order exists.",...(await runCycle(req))});}catch(error){return NextResponse.json({status:"FAILED",error:error instanceof Error?error.message:"CEO cycle failed"},{status:503});}}
export async function POST(req:Request){return GET(req);}